# Project Key (required)
sonar.projectKey=devstack-component-provisioner

# Project Name (optional)
sonar.projectName=devstack-component-provisioner

# Comma-separated paths to directories with sources (required)
sonar.sources=src/main/java

# Encoding of the source files (optional but recommended as default is ASCII)
sonar.sourceEncoding=UTF-8

# TODO Adapt this to the provisioner needs, just in case some generated classes should be excluded
sonar.exclusions=src/main/java/com/boehringer/componentprovisioner/client/awx/v2/**,src/main/java/com/boehringer/componentprovisioner/server/api/**,src/main/java/com/boehringer/componentprovisioner/server/model/**,src/main/java/com/boehringer/componentprovisioner/client/componentcatalog/v1/**
sonar.coverage.exclusions=src/main/java/com/boehringer/componentprovisioner/client/**,src/main/java/com/boehringer/componentprovisioner/server/api/**,src/main/java/com/boehringer/componentprovisioner/server/model/**

sonar.tests=src/test/java

# Plugin-specific settings
sonar.java.binaries=build/classes
sonar.java.libraries=build/dependencies/*.jar,docker/app.jar
sonar.junit.reportPaths=build/test-results/test
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
