/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentprovisioner.client.awx.v2.model.WorkflowJobNodeList;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ApiWorkflowJobNodesList200Response
 */
@JsonPropertyOrder({
  ApiWorkflowJobNodesList200Response.JSON_PROPERTY_COUNT,
  ApiWorkflowJobNodesList200Response.JSON_PROPERTY_NEXT,
  ApiWorkflowJobNodesList200Response.JSON_PROPERTY_PREVIOUS,
  ApiWorkflowJobNodesList200Response.JSON_PROPERTY_RESULTS
})
@JsonTypeName("api_workflow_job_nodes_list_200_response")
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ApiWorkflowJobNodesList200Response implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_COUNT = "count";
  @jakarta.annotation.Nonnull
  private Integer count;

  public static final String JSON_PROPERTY_NEXT = "next";
  @jakarta.annotation.Nullable
  private JsonNullable<URI> next = JsonNullable.<URI>undefined();

  public static final String JSON_PROPERTY_PREVIOUS = "previous";
  @jakarta.annotation.Nullable
  private JsonNullable<URI> previous = JsonNullable.<URI>undefined();

  public static final String JSON_PROPERTY_RESULTS = "results";
  @jakarta.annotation.Nonnull
  private List<WorkflowJobNodeList> results = new ArrayList<>();

  public ApiWorkflowJobNodesList200Response() {
  }

  public ApiWorkflowJobNodesList200Response count(@jakarta.annotation.Nonnull Integer count) {
    
    this.count = count;
    return this;
  }

  /**
   * Get count
   * @return count
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCount() {
    return count;
  }


  @JsonProperty(JSON_PROPERTY_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCount(@jakarta.annotation.Nonnull Integer count) {
    this.count = count;
  }

  public ApiWorkflowJobNodesList200Response next(@jakarta.annotation.Nullable URI next) {
    this.next = JsonNullable.<URI>of(next);
    
    return this;
  }

  /**
   * Get next
   * @return next
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public URI getNext() {
        return next.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<URI> getNext_JsonNullable() {
    return next;
  }
  
  @JsonProperty(JSON_PROPERTY_NEXT)
  public void setNext_JsonNullable(JsonNullable<URI> next) {
    this.next = next;
  }

  public void setNext(@jakarta.annotation.Nullable URI next) {
    this.next = JsonNullable.<URI>of(next);
  }

  public ApiWorkflowJobNodesList200Response previous(@jakarta.annotation.Nullable URI previous) {
    this.previous = JsonNullable.<URI>of(previous);
    
    return this;
  }

  /**
   * Get previous
   * @return previous
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public URI getPrevious() {
        return previous.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PREVIOUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<URI> getPrevious_JsonNullable() {
    return previous;
  }
  
  @JsonProperty(JSON_PROPERTY_PREVIOUS)
  public void setPrevious_JsonNullable(JsonNullable<URI> previous) {
    this.previous = previous;
  }

  public void setPrevious(@jakarta.annotation.Nullable URI previous) {
    this.previous = JsonNullable.<URI>of(previous);
  }

  public ApiWorkflowJobNodesList200Response results(@jakarta.annotation.Nonnull List<WorkflowJobNodeList> results) {
    
    this.results = results;
    return this;
  }

  public ApiWorkflowJobNodesList200Response addResultsItem(WorkflowJobNodeList resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<>();
    }
    this.results.add(resultsItem);
    return this;
  }

  /**
   * Get results
   * @return results
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESULTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<WorkflowJobNodeList> getResults() {
    return results;
  }


  @JsonProperty(JSON_PROPERTY_RESULTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResults(@jakarta.annotation.Nonnull List<WorkflowJobNodeList> results) {
    this.results = results;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiWorkflowJobNodesList200Response apiWorkflowJobNodesList200Response = (ApiWorkflowJobNodesList200Response) o;
    return Objects.equals(this.count, apiWorkflowJobNodesList200Response.count) &&
        equalsNullable(this.next, apiWorkflowJobNodesList200Response.next) &&
        equalsNullable(this.previous, apiWorkflowJobNodesList200Response.previous) &&
        Objects.equals(this.results, apiWorkflowJobNodesList200Response.results);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, hashCodeNullable(next), hashCodeNullable(previous), results);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiWorkflowJobNodesList200Response {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    previous: ").append(toIndentedString(previous)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ApiWorkflowJobNodesList200Response instance;

    public Builder() {
      this(new ApiWorkflowJobNodesList200Response());
    }

    protected Builder(ApiWorkflowJobNodesList200Response instance) {
      this.instance = instance;
    }

    public ApiWorkflowJobNodesList200Response.Builder count(Integer count) {
      this.instance.count = count;
      return this;
    }
    public ApiWorkflowJobNodesList200Response.Builder next(URI next) {
      this.instance.next = JsonNullable.<URI>of(next);
      return this;
    }
    public ApiWorkflowJobNodesList200Response.Builder next(JsonNullable<URI> next) {
      this.instance.next = next;
      return this;
    }
    public ApiWorkflowJobNodesList200Response.Builder previous(URI previous) {
      this.instance.previous = JsonNullable.<URI>of(previous);
      return this;
    }
    public ApiWorkflowJobNodesList200Response.Builder previous(JsonNullable<URI> previous) {
      this.instance.previous = previous;
      return this;
    }
    public ApiWorkflowJobNodesList200Response.Builder results(List<WorkflowJobNodeList> results) {
      this.instance.results = results;
      return this;
    }


    /**
    * returns a built ApiWorkflowJobNodesList200Response instance.
    *
    * The builder is not reusable.
    */
    public ApiWorkflowJobNodesList200Response build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ApiWorkflowJobNodesList200Response.Builder builder() {
    return new ApiWorkflowJobNodesList200Response.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ApiWorkflowJobNodesList200Response.Builder toBuilder() {
    return new ApiWorkflowJobNodesList200Response.Builder()
      .count(getCount())
      .next(getNext())
      .previous(getPrevious())
      .results(getResults());
  }


}

