/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentprovisioner.client.awx.v2.model.BulkHost;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BulkHostCreate
 */
@JsonPropertyOrder({
  BulkHostCreate.JSON_PROPERTY_HOSTS,
  BulkHostCreate.JSON_PROPERTY_INVENTORY
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class BulkHostCreate implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_HOSTS = "hosts";
  @jakarta.annotation.Nonnull
  private List<BulkHost> hosts = new ArrayList<>();

  public static final String JSON_PROPERTY_INVENTORY = "inventory";
  @jakarta.annotation.Nonnull
  private Integer inventory;

  public BulkHostCreate() {
  }

  public BulkHostCreate hosts(@jakarta.annotation.Nonnull List<BulkHost> hosts) {
    
    this.hosts = hosts;
    return this;
  }

  public BulkHostCreate addHostsItem(BulkHost hostsItem) {
    if (this.hosts == null) {
      this.hosts = new ArrayList<>();
    }
    this.hosts.add(hostsItem);
    return this;
  }

  /**
   * List of hosts to be created, JSON. e.g. [{\&quot;name\&quot;: \&quot;example.com\&quot;}, {\&quot;name\&quot;: \&quot;127.0.0.1\&quot;}]
   * @return hosts
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HOSTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<BulkHost> getHosts() {
    return hosts;
  }


  @JsonProperty(JSON_PROPERTY_HOSTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHosts(@jakarta.annotation.Nonnull List<BulkHost> hosts) {
    this.hosts = hosts;
  }

  public BulkHostCreate inventory(@jakarta.annotation.Nonnull Integer inventory) {
    
    this.inventory = inventory;
    return this;
  }

  /**
   * Primary Key ID of inventory to add hosts to.
   * @return inventory
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INVENTORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getInventory() {
    return inventory;
  }


  @JsonProperty(JSON_PROPERTY_INVENTORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInventory(@jakarta.annotation.Nonnull Integer inventory) {
    this.inventory = inventory;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkHostCreate bulkHostCreate = (BulkHostCreate) o;
    return Objects.equals(this.hosts, bulkHostCreate.hosts) &&
        Objects.equals(this.inventory, bulkHostCreate.inventory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hosts, inventory);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkHostCreate {\n");
    sb.append("    hosts: ").append(toIndentedString(hosts)).append("\n");
    sb.append("    inventory: ").append(toIndentedString(inventory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private BulkHostCreate instance;

    public Builder() {
      this(new BulkHostCreate());
    }

    protected Builder(BulkHostCreate instance) {
      this.instance = instance;
    }

    public BulkHostCreate.Builder hosts(List<BulkHost> hosts) {
      this.instance.hosts = hosts;
      return this;
    }
    public BulkHostCreate.Builder inventory(Integer inventory) {
      this.instance.inventory = inventory;
      return this;
    }


    /**
    * returns a built BulkHostCreate instance.
    *
    * The builder is not reusable.
    */
    public BulkHostCreate build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static BulkHostCreate.Builder builder() {
    return new BulkHostCreate.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public BulkHostCreate.Builder toBuilder() {
    return new BulkHostCreate.Builder()
      .hosts(getHosts())
      .inventory(getInventory());
  }


}

