/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BulkHostDelete
 */
@JsonPropertyOrder({
  BulkHostDelete.JSON_PROPERTY_HOSTS
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class BulkHostDelete implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_HOSTS = "hosts";
  @jakarta.annotation.Nonnull
  private List<String> hosts = new ArrayList<>();

  public BulkHostDelete() {
  }

  public BulkHostDelete hosts(@jakarta.annotation.Nonnull List<String> hosts) {
    
    this.hosts = hosts;
    return this;
  }

  public BulkHostDelete addHostsItem(String hostsItem) {
    if (this.hosts == null) {
      this.hosts = new ArrayList<>();
    }
    this.hosts.add(hostsItem);
    return this;
  }

  /**
   * List of hosts ids to be deleted, e.g. [105, 130, 131, 200]
   * @return hosts
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HOSTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getHosts() {
    return hosts;
  }


  @JsonProperty(JSON_PROPERTY_HOSTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHosts(@jakarta.annotation.Nonnull List<String> hosts) {
    this.hosts = hosts;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkHostDelete bulkHostDelete = (BulkHostDelete) o;
    return Objects.equals(this.hosts, bulkHostDelete.hosts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hosts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkHostDelete {\n");
    sb.append("    hosts: ").append(toIndentedString(hosts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private BulkHostDelete instance;

    public Builder() {
      this(new BulkHostDelete());
    }

    protected Builder(BulkHostDelete instance) {
      this.instance = instance;
    }

    public BulkHostDelete.Builder hosts(List<String> hosts) {
      this.instance.hosts = hosts;
      return this;
    }


    /**
    * returns a built BulkHostDelete instance.
    *
    * The builder is not reusable.
    */
    public BulkHostDelete build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static BulkHostDelete.Builder builder() {
    return new BulkHostDelete.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public BulkHostDelete.Builder toBuilder() {
    return new BulkHostDelete.Builder()
      .hosts(getHosts());
  }


}

