/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Credential
 */
@JsonPropertyOrder({
  Credential.JSON_PROPERTY_CLOUD,
  Credential.JSON_PROPERTY_CREATED,
  Credential.JSON_PROPERTY_CREDENTIAL_TYPE,
  Credential.JSON_PROPERTY_DESCRIPTION,
  Credential.JSON_PROPERTY_ID,
  Credential.JSON_PROPERTY_INPUTS,
  Credential.JSON_PROPERTY_KIND,
  Credential.JSON_PROPERTY_KUBERNETES,
  Credential.JSON_PROPERTY_MANAGED,
  Credential.JSON_PROPERTY_MODIFIED,
  Credential.JSON_PROPERTY_NAME,
  Credential.JSON_PROPERTY_ORGANIZATION,
  Credential.JSON_PROPERTY_RELATED,
  Credential.JSON_PROPERTY_SUMMARY_FIELDS,
  Credential.JSON_PROPERTY_TYPE,
  Credential.JSON_PROPERTY_URL
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class Credential implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CLOUD = "cloud";
  @jakarta.annotation.Nullable
  private String cloud;

  public static final String JSON_PROPERTY_CREATED = "created";
  @jakarta.annotation.Nullable
  private String created;

  public static final String JSON_PROPERTY_CREDENTIAL_TYPE = "credential_type";
  @jakarta.annotation.Nonnull
  private Integer credentialType;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private JsonNullable<String> description = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_INPUTS = "inputs";
  @jakarta.annotation.Nullable
  private Object inputs;

  public static final String JSON_PROPERTY_KIND = "kind";
  @jakarta.annotation.Nullable
  private String kind;

  public static final String JSON_PROPERTY_KUBERNETES = "kubernetes";
  @jakarta.annotation.Nullable
  private String kubernetes;

  public static final String JSON_PROPERTY_MANAGED = "managed";
  @jakarta.annotation.Nullable
  private String managed;

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  @jakarta.annotation.Nullable
  private String modified;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> organization = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_RELATED = "related";
  @jakarta.annotation.Nullable
  private String related;

  public static final String JSON_PROPERTY_SUMMARY_FIELDS = "summary_fields";
  @jakarta.annotation.Nullable
  private String summaryFields;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public Credential() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public Credential(
    @JsonProperty(JSON_PROPERTY_CLOUD) String cloud, 
    @JsonProperty(JSON_PROPERTY_CREATED) String created, 
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_KIND) String kind, 
    @JsonProperty(JSON_PROPERTY_KUBERNETES) String kubernetes, 
    @JsonProperty(JSON_PROPERTY_MANAGED) String managed, 
    @JsonProperty(JSON_PROPERTY_MODIFIED) String modified, 
    @JsonProperty(JSON_PROPERTY_RELATED) String related, 
    @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS) String summaryFields, 
    @JsonProperty(JSON_PROPERTY_TYPE) String type, 
    @JsonProperty(JSON_PROPERTY_URL) String url
  ) {
    this();
    this.cloud = cloud;
    this.created = created;
    this.id = id;
    this.kind = kind;
    this.kubernetes = kubernetes;
    this.managed = managed;
    this.modified = modified;
    this.related = related;
    this.summaryFields = summaryFields;
    this.type = type;
    this.url = url;
  }

  /**
   * Get cloud
   * @return cloud
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLOUD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCloud() {
    return cloud;
  }



  /**
   * Get created
   * @return created
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }



  public Credential credentialType(@jakarta.annotation.Nonnull Integer credentialType) {
    
    this.credentialType = credentialType;
    return this;
  }

  /**
   * Specify the type of credential you want to create. Refer to the documentation for details on each type.
   * @return credentialType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREDENTIAL_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCredentialType() {
    return credentialType;
  }


  @JsonProperty(JSON_PROPERTY_CREDENTIAL_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCredentialType(@jakarta.annotation.Nonnull Integer credentialType) {
    this.credentialType = credentialType;
  }

  public Credential description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  public Credential inputs(@jakarta.annotation.Nullable Object inputs) {
    
    this.inputs = inputs;
    return this;
  }

  /**
   * Enter inputs using either JSON or YAML syntax. Refer to the documentation for example syntax.
   * @return inputs
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPUTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getInputs() {
    return inputs;
  }


  @JsonProperty(JSON_PROPERTY_INPUTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInputs(@jakarta.annotation.Nullable Object inputs) {
    this.inputs = inputs;
  }

  /**
   * Get kind
   * @return kind
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKind() {
    return kind;
  }



  /**
   * Get kubernetes
   * @return kubernetes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KUBERNETES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKubernetes() {
    return kubernetes;
  }



  /**
   * Get managed
   * @return managed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getManaged() {
    return managed;
  }



  /**
   * Get modified
   * @return modified
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModified() {
    return modified;
  }



  public Credential name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public Credential organization(@jakarta.annotation.Nullable Integer organization) {
    this.organization = JsonNullable.<Integer>of(organization);
    
    return this;
  }

  /**
   * Get organization
   * @return organization
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getOrganization() {
        return organization.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getOrganization_JsonNullable() {
    return organization;
  }
  
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  public void setOrganization_JsonNullable(JsonNullable<Integer> organization) {
    this.organization = organization;
  }

  public void setOrganization(@jakarta.annotation.Nullable Integer organization) {
    this.organization = JsonNullable.<Integer>of(organization);
  }

  /**
   * Get related
   * @return related
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelated() {
    return related;
  }



  /**
   * Get summaryFields
   * @return summaryFields
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSummaryFields() {
    return summaryFields;
  }



  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }



  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Credential credential = (Credential) o;
    return Objects.equals(this.cloud, credential.cloud) &&
        Objects.equals(this.created, credential.created) &&
        Objects.equals(this.credentialType, credential.credentialType) &&
        equalsNullable(this.description, credential.description) &&
        Objects.equals(this.id, credential.id) &&
        Objects.equals(this.inputs, credential.inputs) &&
        Objects.equals(this.kind, credential.kind) &&
        Objects.equals(this.kubernetes, credential.kubernetes) &&
        Objects.equals(this.managed, credential.managed) &&
        Objects.equals(this.modified, credential.modified) &&
        Objects.equals(this.name, credential.name) &&
        equalsNullable(this.organization, credential.organization) &&
        Objects.equals(this.related, credential.related) &&
        Objects.equals(this.summaryFields, credential.summaryFields) &&
        Objects.equals(this.type, credential.type) &&
        Objects.equals(this.url, credential.url);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(cloud, created, credentialType, hashCodeNullable(description), id, inputs, kind, kubernetes, managed, modified, name, hashCodeNullable(organization), related, summaryFields, type, url);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Credential {\n");
    sb.append("    cloud: ").append(toIndentedString(cloud)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    credentialType: ").append(toIndentedString(credentialType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    kubernetes: ").append(toIndentedString(kubernetes)).append("\n");
    sb.append("    managed: ").append(toIndentedString(managed)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("    summaryFields: ").append(toIndentedString(summaryFields)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private Credential instance;

    public Builder() {
      this(new Credential());
    }

    protected Builder(Credential instance) {
      this.instance = instance;
    }

    public Credential.Builder cloud(String cloud) {
      this.instance.cloud = cloud;
      return this;
    }
    public Credential.Builder created(String created) {
      this.instance.created = created;
      return this;
    }
    public Credential.Builder credentialType(Integer credentialType) {
      this.instance.credentialType = credentialType;
      return this;
    }
    public Credential.Builder description(String description) {
      this.instance.description = JsonNullable.<String>of(description);
      return this;
    }
    public Credential.Builder description(JsonNullable<String> description) {
      this.instance.description = description;
      return this;
    }
    public Credential.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public Credential.Builder inputs(Object inputs) {
      this.instance.inputs = inputs;
      return this;
    }
    public Credential.Builder kind(String kind) {
      this.instance.kind = kind;
      return this;
    }
    public Credential.Builder kubernetes(String kubernetes) {
      this.instance.kubernetes = kubernetes;
      return this;
    }
    public Credential.Builder managed(String managed) {
      this.instance.managed = managed;
      return this;
    }
    public Credential.Builder modified(String modified) {
      this.instance.modified = modified;
      return this;
    }
    public Credential.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public Credential.Builder organization(Integer organization) {
      this.instance.organization = JsonNullable.<Integer>of(organization);
      return this;
    }
    public Credential.Builder organization(JsonNullable<Integer> organization) {
      this.instance.organization = organization;
      return this;
    }
    public Credential.Builder related(String related) {
      this.instance.related = related;
      return this;
    }
    public Credential.Builder summaryFields(String summaryFields) {
      this.instance.summaryFields = summaryFields;
      return this;
    }
    public Credential.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public Credential.Builder url(String url) {
      this.instance.url = url;
      return this;
    }


    /**
    * returns a built Credential instance.
    *
    * The builder is not reusable.
    */
    public Credential build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static Credential.Builder builder() {
    return new Credential.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public Credential.Builder toBuilder() {
    return new Credential.Builder()
      .cloud(getCloud())
      .created(getCreated())
      .credentialType(getCredentialType())
      .description(getDescription())
      .id(getId())
      .inputs(getInputs())
      .kind(getKind())
      .kubernetes(getKubernetes())
      .managed(getManaged())
      .modified(getModified())
      .name(getName())
      .organization(getOrganization())
      .related(getRelated())
      .summaryFields(getSummaryFields())
      .type(getType())
      .url(getUrl());
  }


}

