/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ExecutionEnvironment
 */
@JsonPropertyOrder({
  ExecutionEnvironment.JSON_PROPERTY_CREATED,
  ExecutionEnvironment.JSON_PROPERTY_CREDENTIAL,
  ExecutionEnvironment.JSON_PROPERTY_DESCRIPTION,
  ExecutionEnvironment.JSON_PROPERTY_ID,
  ExecutionEnvironment.JSON_PROPERTY_IMAGE,
  ExecutionEnvironment.JSON_PROPERTY_MANAGED,
  ExecutionEnvironment.JSON_PROPERTY_MODIFIED,
  ExecutionEnvironment.JSON_PROPERTY_NAME,
  ExecutionEnvironment.JSON_PROPERTY_ORGANIZATION,
  ExecutionEnvironment.JSON_PROPERTY_PULL,
  ExecutionEnvironment.JSON_PROPERTY_RELATED,
  ExecutionEnvironment.JSON_PROPERTY_SUMMARY_FIELDS,
  ExecutionEnvironment.JSON_PROPERTY_TYPE,
  ExecutionEnvironment.JSON_PROPERTY_URL
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ExecutionEnvironment implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CREATED = "created";
  @jakarta.annotation.Nullable
  private String created;

  public static final String JSON_PROPERTY_CREDENTIAL = "credential";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> credential = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private JsonNullable<String> description = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_IMAGE = "image";
  @jakarta.annotation.Nullable
  private String image;

  public static final String JSON_PROPERTY_MANAGED = "managed";
  @jakarta.annotation.Nullable
  private String managed;

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  @jakarta.annotation.Nullable
  private String modified;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> organization = JsonNullable.<Integer>undefined();

  /**
   * Pull image before running?
   */
  public enum PullEnum {
    ALWAYS(String.valueOf("always")),
    
    MISSING(String.valueOf("missing")),
    
    NEVER(String.valueOf("never"));

    private String value;

    PullEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PullEnum fromValue(String value) {
      for (PullEnum b : PullEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_PULL = "pull";
  @jakarta.annotation.Nullable
  private JsonNullable<PullEnum> pull = JsonNullable.<PullEnum>of(PullEnum.ALWAYS);

  public static final String JSON_PROPERTY_RELATED = "related";
  @jakarta.annotation.Nullable
  private String related;

  public static final String JSON_PROPERTY_SUMMARY_FIELDS = "summary_fields";
  @jakarta.annotation.Nullable
  private String summaryFields;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public ExecutionEnvironment() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public ExecutionEnvironment(
    @JsonProperty(JSON_PROPERTY_CREATED) String created, 
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_MANAGED) String managed, 
    @JsonProperty(JSON_PROPERTY_MODIFIED) String modified, 
    @JsonProperty(JSON_PROPERTY_RELATED) String related, 
    @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS) String summaryFields, 
    @JsonProperty(JSON_PROPERTY_TYPE) String type, 
    @JsonProperty(JSON_PROPERTY_URL) String url
  ) {
    this();
    this.created = created;
    this.id = id;
    this.managed = managed;
    this.modified = modified;
    this.related = related;
    this.summaryFields = summaryFields;
    this.type = type;
    this.url = url;
  }

  /**
   * Get created
   * @return created
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }



  public ExecutionEnvironment credential(@jakarta.annotation.Nullable Integer credential) {
    this.credential = JsonNullable.<Integer>of(credential);
    
    return this;
  }

  /**
   * Get credential
   * @return credential
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getCredential() {
        return credential.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CREDENTIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getCredential_JsonNullable() {
    return credential;
  }
  
  @JsonProperty(JSON_PROPERTY_CREDENTIAL)
  public void setCredential_JsonNullable(JsonNullable<Integer> credential) {
    this.credential = credential;
  }

  public void setCredential(@jakarta.annotation.Nullable Integer credential) {
    this.credential = JsonNullable.<Integer>of(credential);
  }

  public ExecutionEnvironment description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  public ExecutionEnvironment image(@jakarta.annotation.Nullable String image) {
    
    this.image = image;
    return this;
  }

  /**
   * The full image location, including the container registry, image name, and version tag.
   * @return image
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getImage() {
    return image;
  }


  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setImage(@jakarta.annotation.Nullable String image) {
    this.image = image;
  }

  /**
   * Get managed
   * @return managed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getManaged() {
    return managed;
  }



  /**
   * Get modified
   * @return modified
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModified() {
    return modified;
  }



  public ExecutionEnvironment name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public ExecutionEnvironment organization(@jakarta.annotation.Nullable Integer organization) {
    this.organization = JsonNullable.<Integer>of(organization);
    
    return this;
  }

  /**
   * The organization used to determine access to this execution environment.
   * @return organization
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getOrganization() {
        return organization.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getOrganization_JsonNullable() {
    return organization;
  }
  
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  public void setOrganization_JsonNullable(JsonNullable<Integer> organization) {
    this.organization = organization;
  }

  public void setOrganization(@jakarta.annotation.Nullable Integer organization) {
    this.organization = JsonNullable.<Integer>of(organization);
  }

  public ExecutionEnvironment pull(@jakarta.annotation.Nullable PullEnum pull) {
    this.pull = JsonNullable.<PullEnum>of(pull);
    
    return this;
  }

  /**
   * Pull image before running?
   * @return pull
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public PullEnum getPull() {
        return pull.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PULL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<PullEnum> getPull_JsonNullable() {
    return pull;
  }
  
  @JsonProperty(JSON_PROPERTY_PULL)
  public void setPull_JsonNullable(JsonNullable<PullEnum> pull) {
    this.pull = pull;
  }

  public void setPull(@jakarta.annotation.Nullable PullEnum pull) {
    this.pull = JsonNullable.<PullEnum>of(pull);
  }

  /**
   * Get related
   * @return related
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelated() {
    return related;
  }



  /**
   * Get summaryFields
   * @return summaryFields
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSummaryFields() {
    return summaryFields;
  }



  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }



  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecutionEnvironment executionEnvironment = (ExecutionEnvironment) o;
    return Objects.equals(this.created, executionEnvironment.created) &&
        equalsNullable(this.credential, executionEnvironment.credential) &&
        equalsNullable(this.description, executionEnvironment.description) &&
        Objects.equals(this.id, executionEnvironment.id) &&
        Objects.equals(this.image, executionEnvironment.image) &&
        Objects.equals(this.managed, executionEnvironment.managed) &&
        Objects.equals(this.modified, executionEnvironment.modified) &&
        Objects.equals(this.name, executionEnvironment.name) &&
        equalsNullable(this.organization, executionEnvironment.organization) &&
        equalsNullable(this.pull, executionEnvironment.pull) &&
        Objects.equals(this.related, executionEnvironment.related) &&
        Objects.equals(this.summaryFields, executionEnvironment.summaryFields) &&
        Objects.equals(this.type, executionEnvironment.type) &&
        Objects.equals(this.url, executionEnvironment.url);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, hashCodeNullable(credential), hashCodeNullable(description), id, image, managed, modified, name, hashCodeNullable(organization), hashCodeNullable(pull), related, summaryFields, type, url);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecutionEnvironment {\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    credential: ").append(toIndentedString(credential)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    managed: ").append(toIndentedString(managed)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    pull: ").append(toIndentedString(pull)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("    summaryFields: ").append(toIndentedString(summaryFields)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ExecutionEnvironment instance;

    public Builder() {
      this(new ExecutionEnvironment());
    }

    protected Builder(ExecutionEnvironment instance) {
      this.instance = instance;
    }

    public ExecutionEnvironment.Builder created(String created) {
      this.instance.created = created;
      return this;
    }
    public ExecutionEnvironment.Builder credential(Integer credential) {
      this.instance.credential = JsonNullable.<Integer>of(credential);
      return this;
    }
    public ExecutionEnvironment.Builder credential(JsonNullable<Integer> credential) {
      this.instance.credential = credential;
      return this;
    }
    public ExecutionEnvironment.Builder description(String description) {
      this.instance.description = JsonNullable.<String>of(description);
      return this;
    }
    public ExecutionEnvironment.Builder description(JsonNullable<String> description) {
      this.instance.description = description;
      return this;
    }
    public ExecutionEnvironment.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public ExecutionEnvironment.Builder image(String image) {
      this.instance.image = image;
      return this;
    }
    public ExecutionEnvironment.Builder managed(String managed) {
      this.instance.managed = managed;
      return this;
    }
    public ExecutionEnvironment.Builder modified(String modified) {
      this.instance.modified = modified;
      return this;
    }
    public ExecutionEnvironment.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public ExecutionEnvironment.Builder organization(Integer organization) {
      this.instance.organization = JsonNullable.<Integer>of(organization);
      return this;
    }
    public ExecutionEnvironment.Builder organization(JsonNullable<Integer> organization) {
      this.instance.organization = organization;
      return this;
    }
    public ExecutionEnvironment.Builder pull(PullEnum pull) {
      this.instance.pull = JsonNullable.<PullEnum>of(pull);
      return this;
    }
    public ExecutionEnvironment.Builder pull(JsonNullable<PullEnum> pull) {
      this.instance.pull = pull;
      return this;
    }
    public ExecutionEnvironment.Builder related(String related) {
      this.instance.related = related;
      return this;
    }
    public ExecutionEnvironment.Builder summaryFields(String summaryFields) {
      this.instance.summaryFields = summaryFields;
      return this;
    }
    public ExecutionEnvironment.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public ExecutionEnvironment.Builder url(String url) {
      this.instance.url = url;
      return this;
    }


    /**
    * returns a built ExecutionEnvironment instance.
    *
    * The builder is not reusable.
    */
    public ExecutionEnvironment build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ExecutionEnvironment.Builder builder() {
    return new ExecutionEnvironment.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ExecutionEnvironment.Builder toBuilder() {
    return new ExecutionEnvironment.Builder()
      .created(getCreated())
      .credential(getCredential())
      .description(getDescription())
      .id(getId())
      .image(getImage())
      .managed(getManaged())
      .modified(getModified())
      .name(getName())
      .organization(getOrganization())
      .pull(getPull())
      .related(getRelated())
      .summaryFields(getSummaryFields())
      .type(getType())
      .url(getUrl());
  }


}

