/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GroupTree
 */
@JsonPropertyOrder({
  GroupTree.JSON_PROPERTY_CHILDREN,
  GroupTree.JSON_PROPERTY_CREATED,
  GroupTree.JSON_PROPERTY_DESCRIPTION,
  GroupTree.JSON_PROPERTY_ID,
  GroupTree.JSON_PROPERTY_INVENTORY,
  GroupTree.JSON_PROPERTY_MODIFIED,
  GroupTree.JSON_PROPERTY_NAME,
  GroupTree.JSON_PROPERTY_RELATED,
  GroupTree.JSON_PROPERTY_SUMMARY_FIELDS,
  GroupTree.JSON_PROPERTY_TYPE,
  GroupTree.JSON_PROPERTY_URL,
  GroupTree.JSON_PROPERTY_VARIABLES
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class GroupTree implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CHILDREN = "children";
  @jakarta.annotation.Nullable
  private String children;

  public static final String JSON_PROPERTY_CREATED = "created";
  @jakarta.annotation.Nullable
  private String created;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private JsonNullable<String> description = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_INVENTORY = "inventory";
  @jakarta.annotation.Nonnull
  private Integer inventory;

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  @jakarta.annotation.Nullable
  private String modified;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_RELATED = "related";
  @jakarta.annotation.Nullable
  private String related;

  public static final String JSON_PROPERTY_SUMMARY_FIELDS = "summary_fields";
  @jakarta.annotation.Nullable
  private String summaryFields;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_VARIABLES = "variables";
  @jakarta.annotation.Nullable
  private JsonNullable<String> variables = JsonNullable.<String>of("");

  public GroupTree() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public GroupTree(
    @JsonProperty(JSON_PROPERTY_CHILDREN) String children, 
    @JsonProperty(JSON_PROPERTY_CREATED) String created, 
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_MODIFIED) String modified, 
    @JsonProperty(JSON_PROPERTY_RELATED) String related, 
    @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS) String summaryFields, 
    @JsonProperty(JSON_PROPERTY_TYPE) String type, 
    @JsonProperty(JSON_PROPERTY_URL) String url
  ) {
    this();
    this.children = children;
    this.created = created;
    this.id = id;
    this.modified = modified;
    this.related = related;
    this.summaryFields = summaryFields;
    this.type = type;
    this.url = url;
  }

  /**
   * Get children
   * @return children
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHILDREN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getChildren() {
    return children;
  }



  /**
   * Get created
   * @return created
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }



  public GroupTree description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  public GroupTree inventory(@jakarta.annotation.Nonnull Integer inventory) {
    
    this.inventory = inventory;
    return this;
  }

  /**
   * Get inventory
   * @return inventory
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INVENTORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getInventory() {
    return inventory;
  }


  @JsonProperty(JSON_PROPERTY_INVENTORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInventory(@jakarta.annotation.Nonnull Integer inventory) {
    this.inventory = inventory;
  }

  /**
   * Get modified
   * @return modified
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModified() {
    return modified;
  }



  public GroupTree name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  /**
   * Get related
   * @return related
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelated() {
    return related;
  }



  /**
   * Get summaryFields
   * @return summaryFields
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSummaryFields() {
    return summaryFields;
  }



  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }



  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }



  public GroupTree variables(@jakarta.annotation.Nullable String variables) {
    this.variables = JsonNullable.<String>of(variables);
    
    return this;
  }

  /**
   * Group variables in JSON or YAML format.
   * @return variables
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getVariables() {
        return variables.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VARIABLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getVariables_JsonNullable() {
    return variables;
  }
  
  @JsonProperty(JSON_PROPERTY_VARIABLES)
  public void setVariables_JsonNullable(JsonNullable<String> variables) {
    this.variables = variables;
  }

  public void setVariables(@jakarta.annotation.Nullable String variables) {
    this.variables = JsonNullable.<String>of(variables);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupTree groupTree = (GroupTree) o;
    return Objects.equals(this.children, groupTree.children) &&
        Objects.equals(this.created, groupTree.created) &&
        equalsNullable(this.description, groupTree.description) &&
        Objects.equals(this.id, groupTree.id) &&
        Objects.equals(this.inventory, groupTree.inventory) &&
        Objects.equals(this.modified, groupTree.modified) &&
        Objects.equals(this.name, groupTree.name) &&
        Objects.equals(this.related, groupTree.related) &&
        Objects.equals(this.summaryFields, groupTree.summaryFields) &&
        Objects.equals(this.type, groupTree.type) &&
        Objects.equals(this.url, groupTree.url) &&
        equalsNullable(this.variables, groupTree.variables);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(children, created, hashCodeNullable(description), id, inventory, modified, name, related, summaryFields, type, url, hashCodeNullable(variables));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupTree {\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    inventory: ").append(toIndentedString(inventory)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("    summaryFields: ").append(toIndentedString(summaryFields)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private GroupTree instance;

    public Builder() {
      this(new GroupTree());
    }

    protected Builder(GroupTree instance) {
      this.instance = instance;
    }

    public GroupTree.Builder children(String children) {
      this.instance.children = children;
      return this;
    }
    public GroupTree.Builder created(String created) {
      this.instance.created = created;
      return this;
    }
    public GroupTree.Builder description(String description) {
      this.instance.description = JsonNullable.<String>of(description);
      return this;
    }
    public GroupTree.Builder description(JsonNullable<String> description) {
      this.instance.description = description;
      return this;
    }
    public GroupTree.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public GroupTree.Builder inventory(Integer inventory) {
      this.instance.inventory = inventory;
      return this;
    }
    public GroupTree.Builder modified(String modified) {
      this.instance.modified = modified;
      return this;
    }
    public GroupTree.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public GroupTree.Builder related(String related) {
      this.instance.related = related;
      return this;
    }
    public GroupTree.Builder summaryFields(String summaryFields) {
      this.instance.summaryFields = summaryFields;
      return this;
    }
    public GroupTree.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public GroupTree.Builder url(String url) {
      this.instance.url = url;
      return this;
    }
    public GroupTree.Builder variables(String variables) {
      this.instance.variables = JsonNullable.<String>of(variables);
      return this;
    }
    public GroupTree.Builder variables(JsonNullable<String> variables) {
      this.instance.variables = variables;
      return this;
    }


    /**
    * returns a built GroupTree instance.
    *
    * The builder is not reusable.
    */
    public GroupTree build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static GroupTree.Builder builder() {
    return new GroupTree.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public GroupTree.Builder toBuilder() {
    return new GroupTree.Builder()
      .children(getChildren())
      .created(getCreated())
      .description(getDescription())
      .id(getId())
      .inventory(getInventory())
      .modified(getModified())
      .name(getName())
      .related(getRelated())
      .summaryFields(getSummaryFields())
      .type(getType())
      .url(getUrl())
      .variables(getVariables());
  }


}

