/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Host
 */
@JsonPropertyOrder({
  Host.JSON_PROPERTY_ANSIBLE_FACTS_MODIFIED,
  Host.JSON_PROPERTY_CREATED,
  Host.JSON_PROPERTY_DESCRIPTION,
  Host.JSON_PROPERTY_ENABLED,
  Host.JSON_PROPERTY_HAS_ACTIVE_FAILURES,
  Host.JSON_PROPERTY_HAS_INVENTORY_SOURCES,
  Host.JSON_PROPERTY_ID,
  Host.JSON_PROPERTY_INSTANCE_ID,
  Host.JSON_PROPERTY_INVENTORY,
  Host.JSON_PROPERTY_LAST_JOB,
  Host.JSON_PROPERTY_LAST_JOB_HOST_SUMMARY,
  Host.JSON_PROPERTY_MODIFIED,
  Host.JSON_PROPERTY_NAME,
  Host.JSON_PROPERTY_RELATED,
  Host.JSON_PROPERTY_SUMMARY_FIELDS,
  Host.JSON_PROPERTY_TYPE,
  Host.JSON_PROPERTY_URL,
  Host.JSON_PROPERTY_VARIABLES
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class Host implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ANSIBLE_FACTS_MODIFIED = "ansible_facts_modified";
  @jakarta.annotation.Nullable
  private JsonNullable<OffsetDateTime> ansibleFactsModified = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_CREATED = "created";
  @jakarta.annotation.Nullable
  private String created;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private JsonNullable<String> description = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> enabled = JsonNullable.<Boolean>of(true);

  public static final String JSON_PROPERTY_HAS_ACTIVE_FAILURES = "has_active_failures";
  @jakarta.annotation.Nullable
  private String hasActiveFailures;

  public static final String JSON_PROPERTY_HAS_INVENTORY_SOURCES = "has_inventory_sources";
  @jakarta.annotation.Nullable
  private String hasInventorySources;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_INSTANCE_ID = "instance_id";
  @jakarta.annotation.Nullable
  private JsonNullable<String> instanceId = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_INVENTORY = "inventory";
  @jakarta.annotation.Nonnull
  private Integer inventory;

  public static final String JSON_PROPERTY_LAST_JOB = "last_job";
  @jakarta.annotation.Nullable
  private JsonNullable<String> lastJob = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LAST_JOB_HOST_SUMMARY = "last_job_host_summary";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> lastJobHostSummary = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  @jakarta.annotation.Nullable
  private String modified;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_RELATED = "related";
  @jakarta.annotation.Nullable
  private String related;

  public static final String JSON_PROPERTY_SUMMARY_FIELDS = "summary_fields";
  @jakarta.annotation.Nullable
  private String summaryFields;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_VARIABLES = "variables";
  @jakarta.annotation.Nullable
  private JsonNullable<String> variables = JsonNullable.<String>of("");

  public Host() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public Host(
    @JsonProperty(JSON_PROPERTY_ANSIBLE_FACTS_MODIFIED) OffsetDateTime ansibleFactsModified, 
    @JsonProperty(JSON_PROPERTY_CREATED) String created, 
    @JsonProperty(JSON_PROPERTY_HAS_ACTIVE_FAILURES) String hasActiveFailures, 
    @JsonProperty(JSON_PROPERTY_HAS_INVENTORY_SOURCES) String hasInventorySources, 
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_LAST_JOB) String lastJob, 
    @JsonProperty(JSON_PROPERTY_LAST_JOB_HOST_SUMMARY) Integer lastJobHostSummary, 
    @JsonProperty(JSON_PROPERTY_MODIFIED) String modified, 
    @JsonProperty(JSON_PROPERTY_RELATED) String related, 
    @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS) String summaryFields, 
    @JsonProperty(JSON_PROPERTY_TYPE) String type, 
    @JsonProperty(JSON_PROPERTY_URL) String url
  ) {
    this();
    this.ansibleFactsModified = ansibleFactsModified == null ? JsonNullable.<OffsetDateTime>undefined() : JsonNullable.of(ansibleFactsModified);
    this.created = created;
    this.hasActiveFailures = hasActiveFailures;
    this.hasInventorySources = hasInventorySources;
    this.id = id;
    this.lastJob = lastJob == null ? JsonNullable.<String>undefined() : JsonNullable.of(lastJob);
    this.lastJobHostSummary = lastJobHostSummary == null ? JsonNullable.<Integer>undefined() : JsonNullable.of(lastJobHostSummary);
    this.modified = modified;
    this.related = related;
    this.summaryFields = summaryFields;
    this.type = type;
    this.url = url;
  }

  /**
   * The date and time ansible_facts was last modified.
   * @return ansibleFactsModified
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getAnsibleFactsModified() {
    
    if (ansibleFactsModified == null) {
      ansibleFactsModified = JsonNullable.<OffsetDateTime>undefined();
    }
    return ansibleFactsModified.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ANSIBLE_FACTS_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getAnsibleFactsModified_JsonNullable() {
    return ansibleFactsModified;
  }
  
  @JsonProperty(JSON_PROPERTY_ANSIBLE_FACTS_MODIFIED)
  private void setAnsibleFactsModified_JsonNullable(JsonNullable<OffsetDateTime> ansibleFactsModified) {
    this.ansibleFactsModified = ansibleFactsModified;
  }


  /**
   * Get created
   * @return created
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }



  public Host description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }

  public Host enabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = JsonNullable.<Boolean>of(enabled);
    
    return this;
  }

  /**
   * Is this host online and available for running jobs?
   * @return enabled
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getEnabled() {
        return enabled.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getEnabled_JsonNullable() {
    return enabled;
  }
  
  @JsonProperty(JSON_PROPERTY_ENABLED)
  public void setEnabled_JsonNullable(JsonNullable<Boolean> enabled) {
    this.enabled = enabled;
  }

  public void setEnabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = JsonNullable.<Boolean>of(enabled);
  }

  /**
   * Get hasActiveFailures
   * @return hasActiveFailures
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HAS_ACTIVE_FAILURES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHasActiveFailures() {
    return hasActiveFailures;
  }



  /**
   * Get hasInventorySources
   * @return hasInventorySources
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HAS_INVENTORY_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHasInventorySources() {
    return hasInventorySources;
  }



  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  public Host instanceId(@jakarta.annotation.Nullable String instanceId) {
    this.instanceId = JsonNullable.<String>of(instanceId);
    
    return this;
  }

  /**
   * The value used by the remote inventory source to uniquely identify the host
   * @return instanceId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getInstanceId() {
        return instanceId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getInstanceId_JsonNullable() {
    return instanceId;
  }
  
  @JsonProperty(JSON_PROPERTY_INSTANCE_ID)
  public void setInstanceId_JsonNullable(JsonNullable<String> instanceId) {
    this.instanceId = instanceId;
  }

  public void setInstanceId(@jakarta.annotation.Nullable String instanceId) {
    this.instanceId = JsonNullable.<String>of(instanceId);
  }

  public Host inventory(@jakarta.annotation.Nonnull Integer inventory) {
    
    this.inventory = inventory;
    return this;
  }

  /**
   * Get inventory
   * @return inventory
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INVENTORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getInventory() {
    return inventory;
  }


  @JsonProperty(JSON_PROPERTY_INVENTORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInventory(@jakarta.annotation.Nonnull Integer inventory) {
    this.inventory = inventory;
  }

  /**
   * Get lastJob
   * @return lastJob
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getLastJob() {
    
    if (lastJob == null) {
      lastJob = JsonNullable.<String>undefined();
    }
    return lastJob.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_JOB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLastJob_JsonNullable() {
    return lastJob;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_JOB)
  private void setLastJob_JsonNullable(JsonNullable<String> lastJob) {
    this.lastJob = lastJob;
  }


  /**
   * Get lastJobHostSummary
   * @return lastJobHostSummary
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getLastJobHostSummary() {
    
    if (lastJobHostSummary == null) {
      lastJobHostSummary = JsonNullable.<Integer>undefined();
    }
    return lastJobHostSummary.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_JOB_HOST_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getLastJobHostSummary_JsonNullable() {
    return lastJobHostSummary;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_JOB_HOST_SUMMARY)
  private void setLastJobHostSummary_JsonNullable(JsonNullable<Integer> lastJobHostSummary) {
    this.lastJobHostSummary = lastJobHostSummary;
  }


  /**
   * Get modified
   * @return modified
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModified() {
    return modified;
  }



  public Host name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  /**
   * Get related
   * @return related
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelated() {
    return related;
  }



  /**
   * Get summaryFields
   * @return summaryFields
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSummaryFields() {
    return summaryFields;
  }



  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }



  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }



  public Host variables(@jakarta.annotation.Nullable String variables) {
    this.variables = JsonNullable.<String>of(variables);
    
    return this;
  }

  /**
   * Host variables in JSON or YAML format.
   * @return variables
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getVariables() {
        return variables.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VARIABLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getVariables_JsonNullable() {
    return variables;
  }
  
  @JsonProperty(JSON_PROPERTY_VARIABLES)
  public void setVariables_JsonNullable(JsonNullable<String> variables) {
    this.variables = variables;
  }

  public void setVariables(@jakarta.annotation.Nullable String variables) {
    this.variables = JsonNullable.<String>of(variables);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Host host = (Host) o;
    return equalsNullable(this.ansibleFactsModified, host.ansibleFactsModified) &&
        Objects.equals(this.created, host.created) &&
        equalsNullable(this.description, host.description) &&
        equalsNullable(this.enabled, host.enabled) &&
        Objects.equals(this.hasActiveFailures, host.hasActiveFailures) &&
        Objects.equals(this.hasInventorySources, host.hasInventorySources) &&
        Objects.equals(this.id, host.id) &&
        equalsNullable(this.instanceId, host.instanceId) &&
        Objects.equals(this.inventory, host.inventory) &&
        equalsNullable(this.lastJob, host.lastJob) &&
        equalsNullable(this.lastJobHostSummary, host.lastJobHostSummary) &&
        Objects.equals(this.modified, host.modified) &&
        Objects.equals(this.name, host.name) &&
        Objects.equals(this.related, host.related) &&
        Objects.equals(this.summaryFields, host.summaryFields) &&
        Objects.equals(this.type, host.type) &&
        Objects.equals(this.url, host.url) &&
        equalsNullable(this.variables, host.variables);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(ansibleFactsModified), created, hashCodeNullable(description), hashCodeNullable(enabled), hasActiveFailures, hasInventorySources, id, hashCodeNullable(instanceId), inventory, hashCodeNullable(lastJob), hashCodeNullable(lastJobHostSummary), modified, name, related, summaryFields, type, url, hashCodeNullable(variables));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Host {\n");
    sb.append("    ansibleFactsModified: ").append(toIndentedString(ansibleFactsModified)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    hasActiveFailures: ").append(toIndentedString(hasActiveFailures)).append("\n");
    sb.append("    hasInventorySources: ").append(toIndentedString(hasInventorySources)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    inventory: ").append(toIndentedString(inventory)).append("\n");
    sb.append("    lastJob: ").append(toIndentedString(lastJob)).append("\n");
    sb.append("    lastJobHostSummary: ").append(toIndentedString(lastJobHostSummary)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("    summaryFields: ").append(toIndentedString(summaryFields)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private Host instance;

    public Builder() {
      this(new Host());
    }

    protected Builder(Host instance) {
      this.instance = instance;
    }

    public Host.Builder ansibleFactsModified(OffsetDateTime ansibleFactsModified) {
      this.instance.ansibleFactsModified = JsonNullable.<OffsetDateTime>of(ansibleFactsModified);
      return this;
    }
    public Host.Builder ansibleFactsModified(JsonNullable<OffsetDateTime> ansibleFactsModified) {
      this.instance.ansibleFactsModified = ansibleFactsModified;
      return this;
    }
    public Host.Builder created(String created) {
      this.instance.created = created;
      return this;
    }
    public Host.Builder description(String description) {
      this.instance.description = JsonNullable.<String>of(description);
      return this;
    }
    public Host.Builder description(JsonNullable<String> description) {
      this.instance.description = description;
      return this;
    }
    public Host.Builder enabled(Boolean enabled) {
      this.instance.enabled = JsonNullable.<Boolean>of(enabled);
      return this;
    }
    public Host.Builder enabled(JsonNullable<Boolean> enabled) {
      this.instance.enabled = enabled;
      return this;
    }
    public Host.Builder hasActiveFailures(String hasActiveFailures) {
      this.instance.hasActiveFailures = hasActiveFailures;
      return this;
    }
    public Host.Builder hasInventorySources(String hasInventorySources) {
      this.instance.hasInventorySources = hasInventorySources;
      return this;
    }
    public Host.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public Host.Builder instanceId(String instanceId) {
      this.instance.instanceId = JsonNullable.<String>of(instanceId);
      return this;
    }
    public Host.Builder instanceId(JsonNullable<String> instanceId) {
      this.instance.instanceId = instanceId;
      return this;
    }
    public Host.Builder inventory(Integer inventory) {
      this.instance.inventory = inventory;
      return this;
    }
    public Host.Builder lastJob(String lastJob) {
      this.instance.lastJob = JsonNullable.<String>of(lastJob);
      return this;
    }
    public Host.Builder lastJob(JsonNullable<String> lastJob) {
      this.instance.lastJob = lastJob;
      return this;
    }
    public Host.Builder lastJobHostSummary(Integer lastJobHostSummary) {
      this.instance.lastJobHostSummary = JsonNullable.<Integer>of(lastJobHostSummary);
      return this;
    }
    public Host.Builder lastJobHostSummary(JsonNullable<Integer> lastJobHostSummary) {
      this.instance.lastJobHostSummary = lastJobHostSummary;
      return this;
    }
    public Host.Builder modified(String modified) {
      this.instance.modified = modified;
      return this;
    }
    public Host.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public Host.Builder related(String related) {
      this.instance.related = related;
      return this;
    }
    public Host.Builder summaryFields(String summaryFields) {
      this.instance.summaryFields = summaryFields;
      return this;
    }
    public Host.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public Host.Builder url(String url) {
      this.instance.url = url;
      return this;
    }
    public Host.Builder variables(String variables) {
      this.instance.variables = JsonNullable.<String>of(variables);
      return this;
    }
    public Host.Builder variables(JsonNullable<String> variables) {
      this.instance.variables = variables;
      return this;
    }


    /**
    * returns a built Host instance.
    *
    * The builder is not reusable.
    */
    public Host build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static Host.Builder builder() {
    return new Host.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public Host.Builder toBuilder() {
    return new Host.Builder()
      .ansibleFactsModified(getAnsibleFactsModified())
      .created(getCreated())
      .description(getDescription())
      .enabled(getEnabled())
      .hasActiveFailures(getHasActiveFailures())
      .hasInventorySources(getHasInventorySources())
      .id(getId())
      .instanceId(getInstanceId())
      .inventory(getInventory())
      .lastJob(getLastJob())
      .lastJobHostSummary(getLastJobHostSummary())
      .modified(getModified())
      .name(getName())
      .related(getRelated())
      .summaryFields(getSummaryFields())
      .type(getType())
      .url(getUrl())
      .variables(getVariables());
  }


}

