/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * JobHostSummary
 */
@JsonPropertyOrder({
  JobHostSummary.JSON_PROPERTY_CHANGED,
  JobHostSummary.JSON_PROPERTY_CONSTRUCTED_HOST,
  JobHostSummary.JSON_PROPERTY_CREATED,
  JobHostSummary.JSON_PROPERTY_DARK,
  JobHostSummary.JSON_PROPERTY_FAILED,
  JobHostSummary.JSON_PROPERTY_FAILURES,
  JobHostSummary.JSON_PROPERTY_HOST,
  JobHostSummary.JSON_PROPERTY_HOST_NAME,
  JobHostSummary.JSON_PROPERTY_ID,
  JobHostSummary.JSON_PROPERTY_IGNORED,
  JobHostSummary.JSON_PROPERTY_JOB,
  JobHostSummary.JSON_PROPERTY_MODIFIED,
  JobHostSummary.JSON_PROPERTY_OK,
  JobHostSummary.JSON_PROPERTY_PROCESSED,
  JobHostSummary.JSON_PROPERTY_RELATED,
  JobHostSummary.JSON_PROPERTY_RESCUED,
  JobHostSummary.JSON_PROPERTY_SKIPPED,
  JobHostSummary.JSON_PROPERTY_SUMMARY_FIELDS,
  JobHostSummary.JSON_PROPERTY_TYPE,
  JobHostSummary.JSON_PROPERTY_URL
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class JobHostSummary implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CHANGED = "changed";
  @jakarta.annotation.Nullable
  private Integer changed;

  public static final String JSON_PROPERTY_CONSTRUCTED_HOST = "constructed_host";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> constructedHost = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_CREATED = "created";
  @jakarta.annotation.Nullable
  private String created;

  public static final String JSON_PROPERTY_DARK = "dark";
  @jakarta.annotation.Nullable
  private Integer dark;

  public static final String JSON_PROPERTY_FAILED = "failed";
  @jakarta.annotation.Nullable
  private Boolean failed;

  public static final String JSON_PROPERTY_FAILURES = "failures";
  @jakarta.annotation.Nullable
  private Integer failures;

  public static final String JSON_PROPERTY_HOST = "host";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> host = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_HOST_NAME = "host_name";
  @jakarta.annotation.Nullable
  private String hostName = "";

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_IGNORED = "ignored";
  @jakarta.annotation.Nullable
  private Integer ignored;

  public static final String JSON_PROPERTY_JOB = "job";
  @jakarta.annotation.Nullable
  private String job;

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  @jakarta.annotation.Nullable
  private String modified;

  public static final String JSON_PROPERTY_OK = "ok";
  @jakarta.annotation.Nullable
  private Integer ok;

  public static final String JSON_PROPERTY_PROCESSED = "processed";
  @jakarta.annotation.Nullable
  private Integer processed;

  public static final String JSON_PROPERTY_RELATED = "related";
  @jakarta.annotation.Nullable
  private String related;

  public static final String JSON_PROPERTY_RESCUED = "rescued";
  @jakarta.annotation.Nullable
  private Integer rescued;

  public static final String JSON_PROPERTY_SKIPPED = "skipped";
  @jakarta.annotation.Nullable
  private Integer skipped;

  public static final String JSON_PROPERTY_SUMMARY_FIELDS = "summary_fields";
  @jakarta.annotation.Nullable
  private String summaryFields;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public JobHostSummary() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public JobHostSummary(
    @JsonProperty(JSON_PROPERTY_CHANGED) Integer changed, 
    @JsonProperty(JSON_PROPERTY_CONSTRUCTED_HOST) Integer constructedHost, 
    @JsonProperty(JSON_PROPERTY_CREATED) String created, 
    @JsonProperty(JSON_PROPERTY_DARK) Integer dark, 
    @JsonProperty(JSON_PROPERTY_FAILED) Boolean failed, 
    @JsonProperty(JSON_PROPERTY_FAILURES) Integer failures, 
    @JsonProperty(JSON_PROPERTY_HOST) Integer host, 
    @JsonProperty(JSON_PROPERTY_HOST_NAME) String hostName, 
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_IGNORED) Integer ignored, 
    @JsonProperty(JSON_PROPERTY_JOB) String job, 
    @JsonProperty(JSON_PROPERTY_MODIFIED) String modified, 
    @JsonProperty(JSON_PROPERTY_OK) Integer ok, 
    @JsonProperty(JSON_PROPERTY_PROCESSED) Integer processed, 
    @JsonProperty(JSON_PROPERTY_RELATED) String related, 
    @JsonProperty(JSON_PROPERTY_RESCUED) Integer rescued, 
    @JsonProperty(JSON_PROPERTY_SKIPPED) Integer skipped, 
    @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS) String summaryFields, 
    @JsonProperty(JSON_PROPERTY_TYPE) String type, 
    @JsonProperty(JSON_PROPERTY_URL) String url
  ) {
    this();
    this.changed = changed;
    this.constructedHost = constructedHost == null ? JsonNullable.<Integer>undefined() : JsonNullable.of(constructedHost);
    this.created = created;
    this.dark = dark;
    this.failed = failed;
    this.failures = failures;
    this.host = host == null ? JsonNullable.<Integer>undefined() : JsonNullable.of(host);
    this.hostName = hostName;
    this.id = id;
    this.ignored = ignored;
    this.job = job;
    this.modified = modified;
    this.ok = ok;
    this.processed = processed;
    this.related = related;
    this.rescued = rescued;
    this.skipped = skipped;
    this.summaryFields = summaryFields;
    this.type = type;
    this.url = url;
  }

  /**
   * Get changed
   * minimum: 0
   * @return changed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHANGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getChanged() {
    return changed;
  }



  /**
   * Only for jobs run against constructed inventories, this links to the host inside the constructed inventory.
   * @return constructedHost
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getConstructedHost() {
    
    if (constructedHost == null) {
      constructedHost = JsonNullable.<Integer>undefined();
    }
    return constructedHost.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CONSTRUCTED_HOST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getConstructedHost_JsonNullable() {
    return constructedHost;
  }
  
  @JsonProperty(JSON_PROPERTY_CONSTRUCTED_HOST)
  private void setConstructedHost_JsonNullable(JsonNullable<Integer> constructedHost) {
    this.constructedHost = constructedHost;
  }


  /**
   * Get created
   * @return created
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }



  /**
   * Get dark
   * minimum: 0
   * @return dark
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DARK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDark() {
    return dark;
  }



  /**
   * Get failed
   * @return failed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FAILED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFailed() {
    return failed;
  }



  /**
   * Get failures
   * minimum: 0
   * @return failures
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FAILURES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFailures() {
    return failures;
  }



  /**
   * Get host
   * @return host
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getHost() {
    
    if (host == null) {
      host = JsonNullable.<Integer>undefined();
    }
    return host.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_HOST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getHost_JsonNullable() {
    return host;
  }
  
  @JsonProperty(JSON_PROPERTY_HOST)
  private void setHost_JsonNullable(JsonNullable<Integer> host) {
    this.host = host;
  }


  /**
   * Get hostName
   * @return hostName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HOST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHostName() {
    return hostName;
  }



  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  /**
   * Get ignored
   * minimum: 0
   * @return ignored
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IGNORED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIgnored() {
    return ignored;
  }



  /**
   * Get job
   * @return job
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJob() {
    return job;
  }



  /**
   * Get modified
   * @return modified
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModified() {
    return modified;
  }



  /**
   * Get ok
   * minimum: 0
   * @return ok
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOk() {
    return ok;
  }



  /**
   * Get processed
   * minimum: 0
   * @return processed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCESSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProcessed() {
    return processed;
  }



  /**
   * Get related
   * @return related
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelated() {
    return related;
  }



  /**
   * Get rescued
   * minimum: 0
   * @return rescued
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESCUED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRescued() {
    return rescued;
  }



  /**
   * Get skipped
   * minimum: 0
   * @return skipped
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SKIPPED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSkipped() {
    return skipped;
  }



  /**
   * Get summaryFields
   * @return summaryFields
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSummaryFields() {
    return summaryFields;
  }



  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }



  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobHostSummary jobHostSummary = (JobHostSummary) o;
    return Objects.equals(this.changed, jobHostSummary.changed) &&
        equalsNullable(this.constructedHost, jobHostSummary.constructedHost) &&
        Objects.equals(this.created, jobHostSummary.created) &&
        Objects.equals(this.dark, jobHostSummary.dark) &&
        Objects.equals(this.failed, jobHostSummary.failed) &&
        Objects.equals(this.failures, jobHostSummary.failures) &&
        equalsNullable(this.host, jobHostSummary.host) &&
        Objects.equals(this.hostName, jobHostSummary.hostName) &&
        Objects.equals(this.id, jobHostSummary.id) &&
        Objects.equals(this.ignored, jobHostSummary.ignored) &&
        Objects.equals(this.job, jobHostSummary.job) &&
        Objects.equals(this.modified, jobHostSummary.modified) &&
        Objects.equals(this.ok, jobHostSummary.ok) &&
        Objects.equals(this.processed, jobHostSummary.processed) &&
        Objects.equals(this.related, jobHostSummary.related) &&
        Objects.equals(this.rescued, jobHostSummary.rescued) &&
        Objects.equals(this.skipped, jobHostSummary.skipped) &&
        Objects.equals(this.summaryFields, jobHostSummary.summaryFields) &&
        Objects.equals(this.type, jobHostSummary.type) &&
        Objects.equals(this.url, jobHostSummary.url);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(changed, hashCodeNullable(constructedHost), created, dark, failed, failures, hashCodeNullable(host), hostName, id, ignored, job, modified, ok, processed, related, rescued, skipped, summaryFields, type, url);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobHostSummary {\n");
    sb.append("    changed: ").append(toIndentedString(changed)).append("\n");
    sb.append("    constructedHost: ").append(toIndentedString(constructedHost)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    dark: ").append(toIndentedString(dark)).append("\n");
    sb.append("    failed: ").append(toIndentedString(failed)).append("\n");
    sb.append("    failures: ").append(toIndentedString(failures)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    hostName: ").append(toIndentedString(hostName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ignored: ").append(toIndentedString(ignored)).append("\n");
    sb.append("    job: ").append(toIndentedString(job)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("    processed: ").append(toIndentedString(processed)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("    rescued: ").append(toIndentedString(rescued)).append("\n");
    sb.append("    skipped: ").append(toIndentedString(skipped)).append("\n");
    sb.append("    summaryFields: ").append(toIndentedString(summaryFields)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private JobHostSummary instance;

    public Builder() {
      this(new JobHostSummary());
    }

    protected Builder(JobHostSummary instance) {
      this.instance = instance;
    }

    public JobHostSummary.Builder changed(Integer changed) {
      this.instance.changed = changed;
      return this;
    }
    public JobHostSummary.Builder constructedHost(Integer constructedHost) {
      this.instance.constructedHost = JsonNullable.<Integer>of(constructedHost);
      return this;
    }
    public JobHostSummary.Builder constructedHost(JsonNullable<Integer> constructedHost) {
      this.instance.constructedHost = constructedHost;
      return this;
    }
    public JobHostSummary.Builder created(String created) {
      this.instance.created = created;
      return this;
    }
    public JobHostSummary.Builder dark(Integer dark) {
      this.instance.dark = dark;
      return this;
    }
    public JobHostSummary.Builder failed(Boolean failed) {
      this.instance.failed = failed;
      return this;
    }
    public JobHostSummary.Builder failures(Integer failures) {
      this.instance.failures = failures;
      return this;
    }
    public JobHostSummary.Builder host(Integer host) {
      this.instance.host = JsonNullable.<Integer>of(host);
      return this;
    }
    public JobHostSummary.Builder host(JsonNullable<Integer> host) {
      this.instance.host = host;
      return this;
    }
    public JobHostSummary.Builder hostName(String hostName) {
      this.instance.hostName = hostName;
      return this;
    }
    public JobHostSummary.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public JobHostSummary.Builder ignored(Integer ignored) {
      this.instance.ignored = ignored;
      return this;
    }
    public JobHostSummary.Builder job(String job) {
      this.instance.job = job;
      return this;
    }
    public JobHostSummary.Builder modified(String modified) {
      this.instance.modified = modified;
      return this;
    }
    public JobHostSummary.Builder ok(Integer ok) {
      this.instance.ok = ok;
      return this;
    }
    public JobHostSummary.Builder processed(Integer processed) {
      this.instance.processed = processed;
      return this;
    }
    public JobHostSummary.Builder related(String related) {
      this.instance.related = related;
      return this;
    }
    public JobHostSummary.Builder rescued(Integer rescued) {
      this.instance.rescued = rescued;
      return this;
    }
    public JobHostSummary.Builder skipped(Integer skipped) {
      this.instance.skipped = skipped;
      return this;
    }
    public JobHostSummary.Builder summaryFields(String summaryFields) {
      this.instance.summaryFields = summaryFields;
      return this;
    }
    public JobHostSummary.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public JobHostSummary.Builder url(String url) {
      this.instance.url = url;
      return this;
    }


    /**
    * returns a built JobHostSummary instance.
    *
    * The builder is not reusable.
    */
    public JobHostSummary build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static JobHostSummary.Builder builder() {
    return new JobHostSummary.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public JobHostSummary.Builder toBuilder() {
    return new JobHostSummary.Builder()
      .changed(getChanged())
      .constructedHost(getConstructedHost())
      .created(getCreated())
      .dark(getDark())
      .failed(getFailed())
      .failures(getFailures())
      .host(getHost())
      .hostName(getHostName())
      .id(getId())
      .ignored(getIgnored())
      .job(getJob())
      .modified(getModified())
      .ok(getOk())
      .processed(getProcessed())
      .related(getRelated())
      .rescued(getRescued())
      .skipped(getSkipped())
      .summaryFields(getSummaryFields())
      .type(getType())
      .url(getUrl());
  }


}

