/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * JobList
 */
@JsonPropertyOrder({
  JobList.JSON_PROPERTY_ALLOW_SIMULTANEOUS,
  JobList.JSON_PROPERTY_ARTIFACTS,
  JobList.JSON_PROPERTY_CANCELED_ON,
  JobList.JSON_PROPERTY_CONTROLLER_NODE,
  JobList.JSON_PROPERTY_CREATED,
  JobList.JSON_PROPERTY_DESCRIPTION,
  JobList.JSON_PROPERTY_DIFF_MODE,
  JobList.JSON_PROPERTY_ELAPSED,
  JobList.JSON_PROPERTY_EXECUTION_ENVIRONMENT,
  JobList.JSON_PROPERTY_EXECUTION_NODE,
  JobList.JSON_PROPERTY_EXTRA_VARS,
  JobList.JSON_PROPERTY_FAILED,
  JobList.JSON_PROPERTY_FINISHED,
  JobList.JSON_PROPERTY_FORCE_HANDLERS,
  JobList.JSON_PROPERTY_FORKS,
  JobList.JSON_PROPERTY_ID,
  JobList.JSON_PROPERTY_INSTANCE_GROUP,
  JobList.JSON_PROPERTY_INVENTORY,
  JobList.JSON_PROPERTY_JOB_EXPLANATION,
  JobList.JSON_PROPERTY_JOB_SLICE_COUNT,
  JobList.JSON_PROPERTY_JOB_SLICE_NUMBER,
  JobList.JSON_PROPERTY_JOB_TAGS,
  JobList.JSON_PROPERTY_JOB_TEMPLATE,
  JobList.JSON_PROPERTY_JOB_TYPE,
  JobList.JSON_PROPERTY_LAUNCH_TYPE,
  JobList.JSON_PROPERTY_LAUNCHED_BY,
  JobList.JSON_PROPERTY_LIMIT,
  JobList.JSON_PROPERTY_MODIFIED,
  JobList.JSON_PROPERTY_NAME,
  JobList.JSON_PROPERTY_ORGANIZATION,
  JobList.JSON_PROPERTY_PASSWORDS_NEEDED_TO_START,
  JobList.JSON_PROPERTY_PLAYBOOK,
  JobList.JSON_PROPERTY_PROJECT,
  JobList.JSON_PROPERTY_RELATED,
  JobList.JSON_PROPERTY_SCM_BRANCH,
  JobList.JSON_PROPERTY_SCM_REVISION,
  JobList.JSON_PROPERTY_SKIP_TAGS,
  JobList.JSON_PROPERTY_START_AT_TASK,
  JobList.JSON_PROPERTY_STARTED,
  JobList.JSON_PROPERTY_STATUS,
  JobList.JSON_PROPERTY_SUMMARY_FIELDS,
  JobList.JSON_PROPERTY_TIMEOUT,
  JobList.JSON_PROPERTY_TYPE,
  JobList.JSON_PROPERTY_UNIFIED_JOB_TEMPLATE,
  JobList.JSON_PROPERTY_URL,
  JobList.JSON_PROPERTY_USE_FACT_CACHE,
  JobList.JSON_PROPERTY_VERBOSITY,
  JobList.JSON_PROPERTY_WEBHOOK_CREDENTIAL,
  JobList.JSON_PROPERTY_WEBHOOK_GUID,
  JobList.JSON_PROPERTY_WEBHOOK_SERVICE,
  JobList.JSON_PROPERTY_WORK_UNIT_ID
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class JobList implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ALLOW_SIMULTANEOUS = "allow_simultaneous";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> allowSimultaneous = JsonNullable.<Boolean>of(false);

  public static final String JSON_PROPERTY_ARTIFACTS = "artifacts";
  @jakarta.annotation.Nullable
  private String artifacts;

  public static final String JSON_PROPERTY_CANCELED_ON = "canceled_on";
  @jakarta.annotation.Nullable
  private JsonNullable<OffsetDateTime> canceledOn = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_CONTROLLER_NODE = "controller_node";
  @jakarta.annotation.Nullable
  private String controllerNode;

  public static final String JSON_PROPERTY_CREATED = "created";
  @jakarta.annotation.Nullable
  private String created;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private JsonNullable<String> description = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_DIFF_MODE = "diff_mode";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> diffMode = JsonNullable.<Boolean>of(false);

  public static final String JSON_PROPERTY_ELAPSED = "elapsed";
  @jakarta.annotation.Nullable
  private BigDecimal elapsed;

  public static final String JSON_PROPERTY_EXECUTION_ENVIRONMENT = "execution_environment";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> executionEnvironment = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_EXECUTION_NODE = "execution_node";
  @jakarta.annotation.Nullable
  private String executionNode;

  public static final String JSON_PROPERTY_EXTRA_VARS = "extra_vars";
  @jakarta.annotation.Nullable
  private JsonNullable<String> extraVars = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_FAILED = "failed";
  @jakarta.annotation.Nullable
  private Boolean failed;

  public static final String JSON_PROPERTY_FINISHED = "finished";
  @jakarta.annotation.Nullable
  private JsonNullable<OffsetDateTime> finished = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_FORCE_HANDLERS = "force_handlers";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> forceHandlers = JsonNullable.<Boolean>of(false);

  public static final String JSON_PROPERTY_FORKS = "forks";
  @jakarta.annotation.Nullable
  private Integer forks;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_INSTANCE_GROUP = "instance_group";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> instanceGroup = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_INVENTORY = "inventory";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> inventory = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_JOB_EXPLANATION = "job_explanation";
  @jakarta.annotation.Nullable
  private String jobExplanation;

  public static final String JSON_PROPERTY_JOB_SLICE_COUNT = "job_slice_count";
  @jakarta.annotation.Nullable
  private Integer jobSliceCount;

  public static final String JSON_PROPERTY_JOB_SLICE_NUMBER = "job_slice_number";
  @jakarta.annotation.Nullable
  private Integer jobSliceNumber;

  public static final String JSON_PROPERTY_JOB_TAGS = "job_tags";
  @jakarta.annotation.Nullable
  private JsonNullable<String> jobTags = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_JOB_TEMPLATE = "job_template";
  @jakarta.annotation.Nullable
  private JsonNullable<String> jobTemplate = JsonNullable.<String>undefined();

  /**
   * Gets or Sets jobType
   */
  public enum JobTypeEnum {
    RUN(String.valueOf("run")),
    
    CHECK(String.valueOf("check")),
    
    SCAN(String.valueOf("scan"));

    private String value;

    JobTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static JobTypeEnum fromValue(String value) {
      for (JobTypeEnum b : JobTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_JOB_TYPE = "job_type";
  @jakarta.annotation.Nullable
  private JsonNullable<JobTypeEnum> jobType = JsonNullable.<JobTypeEnum>of(JobTypeEnum.RUN);

  /**
   * Gets or Sets launchType
   */
  public enum LaunchTypeEnum {
    MANUAL(String.valueOf("manual")),
    
    RELAUNCH(String.valueOf("relaunch")),
    
    CALLBACK(String.valueOf("callback")),
    
    SCHEDULED(String.valueOf("scheduled")),
    
    DEPENDENCY(String.valueOf("dependency")),
    
    WORKFLOW(String.valueOf("workflow")),
    
    WEBHOOK(String.valueOf("webhook")),
    
    SYNC(String.valueOf("sync")),
    
    SCM(String.valueOf("scm"));

    private String value;

    LaunchTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LaunchTypeEnum fromValue(String value) {
      for (LaunchTypeEnum b : LaunchTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LAUNCH_TYPE = "launch_type";
  @jakarta.annotation.Nullable
  private LaunchTypeEnum launchType;

  public static final String JSON_PROPERTY_LAUNCHED_BY = "launched_by";
  @jakarta.annotation.Nullable
  private String launchedBy;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @jakarta.annotation.Nullable
  private JsonNullable<String> limit = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  @jakarta.annotation.Nullable
  private String modified;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> organization = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_PASSWORDS_NEEDED_TO_START = "passwords_needed_to_start";
  @jakarta.annotation.Nullable
  private String passwordsNeededToStart;

  public static final String JSON_PROPERTY_PLAYBOOK = "playbook";
  @jakarta.annotation.Nullable
  private JsonNullable<String> playbook = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_PROJECT = "project";
  @jakarta.annotation.Nullable
  private JsonNullable<String> project = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_RELATED = "related";
  @jakarta.annotation.Nullable
  private String related;

  public static final String JSON_PROPERTY_SCM_BRANCH = "scm_branch";
  @jakarta.annotation.Nullable
  private JsonNullable<String> scmBranch = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_SCM_REVISION = "scm_revision";
  @jakarta.annotation.Nullable
  private String scmRevision;

  public static final String JSON_PROPERTY_SKIP_TAGS = "skip_tags";
  @jakarta.annotation.Nullable
  private JsonNullable<String> skipTags = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_START_AT_TASK = "start_at_task";
  @jakarta.annotation.Nullable
  private JsonNullable<String> startAtTask = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_STARTED = "started";
  @jakarta.annotation.Nullable
  private JsonNullable<OffsetDateTime> started = JsonNullable.<OffsetDateTime>undefined();

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    NEW(String.valueOf("new")),
    
    PENDING(String.valueOf("pending")),
    
    WAITING(String.valueOf("waiting")),
    
    RUNNING(String.valueOf("running")),
    
    SUCCESSFUL(String.valueOf("successful")),
    
    FAILED(String.valueOf("failed")),
    
    ERROR(String.valueOf("error")),
    
    CANCELED(String.valueOf("canceled"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_SUMMARY_FIELDS = "summary_fields";
  @jakarta.annotation.Nullable
  private String summaryFields;

  public static final String JSON_PROPERTY_TIMEOUT = "timeout";
  @jakarta.annotation.Nullable
  private Integer timeout;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_UNIFIED_JOB_TEMPLATE = "unified_job_template";
  @jakarta.annotation.Nullable
  private String unifiedJobTemplate;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_USE_FACT_CACHE = "use_fact_cache";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> useFactCache = JsonNullable.<Boolean>of(false);

  public static final String JSON_PROPERTY_VERBOSITY = "verbosity";
  @jakarta.annotation.Nullable
  private Integer verbosity;

  public static final String JSON_PROPERTY_WEBHOOK_CREDENTIAL = "webhook_credential";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> webhookCredential = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_WEBHOOK_GUID = "webhook_guid";
  @jakarta.annotation.Nullable
  private JsonNullable<String> webhookGuid = JsonNullable.<String>undefined();

  /**
   * Service that webhook requests will be accepted from
   */
  public enum WebhookServiceEnum {
    GITHUB(String.valueOf("github")),
    
    GITLAB(String.valueOf("gitlab")),
    
    BITBUCKET_DC(String.valueOf("bitbucket_dc"));

    private String value;

    WebhookServiceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static WebhookServiceEnum fromValue(String value) {
      for (WebhookServiceEnum b : WebhookServiceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_WEBHOOK_SERVICE = "webhook_service";
  @jakarta.annotation.Nullable
  private JsonNullable<WebhookServiceEnum> webhookService = JsonNullable.<WebhookServiceEnum>undefined();

  public static final String JSON_PROPERTY_WORK_UNIT_ID = "work_unit_id";
  @jakarta.annotation.Nullable
  private JsonNullable<String> workUnitId = JsonNullable.<String>undefined();

  public JobList() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public JobList(
    @JsonProperty(JSON_PROPERTY_ARTIFACTS) String artifacts, 
    @JsonProperty(JSON_PROPERTY_CANCELED_ON) OffsetDateTime canceledOn, 
    @JsonProperty(JSON_PROPERTY_CONTROLLER_NODE) String controllerNode, 
    @JsonProperty(JSON_PROPERTY_CREATED) String created, 
    @JsonProperty(JSON_PROPERTY_ELAPSED) BigDecimal elapsed, 
    @JsonProperty(JSON_PROPERTY_EXECUTION_NODE) String executionNode, 
    @JsonProperty(JSON_PROPERTY_FAILED) Boolean failed, 
    @JsonProperty(JSON_PROPERTY_FINISHED) OffsetDateTime finished, 
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_JOB_EXPLANATION) String jobExplanation, 
    @JsonProperty(JSON_PROPERTY_LAUNCH_TYPE) LaunchTypeEnum launchType, 
    @JsonProperty(JSON_PROPERTY_LAUNCHED_BY) String launchedBy, 
    @JsonProperty(JSON_PROPERTY_MODIFIED) String modified, 
    @JsonProperty(JSON_PROPERTY_ORGANIZATION) Integer organization, 
    @JsonProperty(JSON_PROPERTY_PASSWORDS_NEEDED_TO_START) String passwordsNeededToStart, 
    @JsonProperty(JSON_PROPERTY_RELATED) String related, 
    @JsonProperty(JSON_PROPERTY_SCM_REVISION) String scmRevision, 
    @JsonProperty(JSON_PROPERTY_STARTED) OffsetDateTime started, 
    @JsonProperty(JSON_PROPERTY_STATUS) StatusEnum status, 
    @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS) String summaryFields, 
    @JsonProperty(JSON_PROPERTY_TYPE) String type, 
    @JsonProperty(JSON_PROPERTY_UNIFIED_JOB_TEMPLATE) String unifiedJobTemplate, 
    @JsonProperty(JSON_PROPERTY_URL) String url, 
    @JsonProperty(JSON_PROPERTY_WORK_UNIT_ID) String workUnitId
  ) {
    this();
    this.artifacts = artifacts;
    this.canceledOn = canceledOn == null ? JsonNullable.<OffsetDateTime>undefined() : JsonNullable.of(canceledOn);
    this.controllerNode = controllerNode;
    this.created = created;
    this.elapsed = elapsed;
    this.executionNode = executionNode;
    this.failed = failed;
    this.finished = finished == null ? JsonNullable.<OffsetDateTime>undefined() : JsonNullable.of(finished);
    this.id = id;
    this.jobExplanation = jobExplanation;
    this.launchType = launchType;
    this.launchedBy = launchedBy;
    this.modified = modified;
    this.organization = organization == null ? JsonNullable.<Integer>undefined() : JsonNullable.of(organization);
    this.passwordsNeededToStart = passwordsNeededToStart;
    this.related = related;
    this.scmRevision = scmRevision;
    this.started = started == null ? JsonNullable.<OffsetDateTime>undefined() : JsonNullable.of(started);
    this.status = status;
    this.summaryFields = summaryFields;
    this.type = type;
    this.unifiedJobTemplate = unifiedJobTemplate;
    this.url = url;
    this.workUnitId = workUnitId == null ? JsonNullable.<String>undefined() : JsonNullable.of(workUnitId);
  }

  public JobList allowSimultaneous(@jakarta.annotation.Nullable Boolean allowSimultaneous) {
    this.allowSimultaneous = JsonNullable.<Boolean>of(allowSimultaneous);
    
    return this;
  }

  /**
   * Get allowSimultaneous
   * @return allowSimultaneous
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getAllowSimultaneous() {
        return allowSimultaneous.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ALLOW_SIMULTANEOUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getAllowSimultaneous_JsonNullable() {
    return allowSimultaneous;
  }
  
  @JsonProperty(JSON_PROPERTY_ALLOW_SIMULTANEOUS)
  public void setAllowSimultaneous_JsonNullable(JsonNullable<Boolean> allowSimultaneous) {
    this.allowSimultaneous = allowSimultaneous;
  }

  public void setAllowSimultaneous(@jakarta.annotation.Nullable Boolean allowSimultaneous) {
    this.allowSimultaneous = JsonNullable.<Boolean>of(allowSimultaneous);
  }

  /**
   * Get artifacts
   * @return artifacts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ARTIFACTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getArtifacts() {
    return artifacts;
  }



  /**
   * The date and time when the cancel request was sent.
   * @return canceledOn
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getCanceledOn() {
    
    if (canceledOn == null) {
      canceledOn = JsonNullable.<OffsetDateTime>undefined();
    }
    return canceledOn.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CANCELED_ON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getCanceledOn_JsonNullable() {
    return canceledOn;
  }
  
  @JsonProperty(JSON_PROPERTY_CANCELED_ON)
  private void setCanceledOn_JsonNullable(JsonNullable<OffsetDateTime> canceledOn) {
    this.canceledOn = canceledOn;
  }


  /**
   * The instance that managed the execution environment.
   * @return controllerNode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTROLLER_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getControllerNode() {
    return controllerNode;
  }



  /**
   * Get created
   * @return created
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }



  public JobList description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }

  public JobList diffMode(@jakarta.annotation.Nullable Boolean diffMode) {
    this.diffMode = JsonNullable.<Boolean>of(diffMode);
    
    return this;
  }

  /**
   * If enabled, textual changes made to any templated files on the host are shown in the standard output
   * @return diffMode
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getDiffMode() {
        return diffMode.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DIFF_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getDiffMode_JsonNullable() {
    return diffMode;
  }
  
  @JsonProperty(JSON_PROPERTY_DIFF_MODE)
  public void setDiffMode_JsonNullable(JsonNullable<Boolean> diffMode) {
    this.diffMode = diffMode;
  }

  public void setDiffMode(@jakarta.annotation.Nullable Boolean diffMode) {
    this.diffMode = JsonNullable.<Boolean>of(diffMode);
  }

  /**
   * Elapsed time in seconds that the job ran.
   * @return elapsed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ELAPSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getElapsed() {
    return elapsed;
  }



  public JobList executionEnvironment(@jakarta.annotation.Nullable Integer executionEnvironment) {
    this.executionEnvironment = JsonNullable.<Integer>of(executionEnvironment);
    
    return this;
  }

  /**
   * The container image to be used for execution.
   * @return executionEnvironment
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getExecutionEnvironment() {
        return executionEnvironment.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXECUTION_ENVIRONMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getExecutionEnvironment_JsonNullable() {
    return executionEnvironment;
  }
  
  @JsonProperty(JSON_PROPERTY_EXECUTION_ENVIRONMENT)
  public void setExecutionEnvironment_JsonNullable(JsonNullable<Integer> executionEnvironment) {
    this.executionEnvironment = executionEnvironment;
  }

  public void setExecutionEnvironment(@jakarta.annotation.Nullable Integer executionEnvironment) {
    this.executionEnvironment = JsonNullable.<Integer>of(executionEnvironment);
  }

  /**
   * The node the job executed on.
   * @return executionNode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXECUTION_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExecutionNode() {
    return executionNode;
  }



  public JobList extraVars(@jakarta.annotation.Nullable String extraVars) {
    this.extraVars = JsonNullable.<String>of(extraVars);
    
    return this;
  }

  /**
   * Get extraVars
   * @return extraVars
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getExtraVars() {
        return extraVars.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXTRA_VARS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getExtraVars_JsonNullable() {
    return extraVars;
  }
  
  @JsonProperty(JSON_PROPERTY_EXTRA_VARS)
  public void setExtraVars_JsonNullable(JsonNullable<String> extraVars) {
    this.extraVars = extraVars;
  }

  public void setExtraVars(@jakarta.annotation.Nullable String extraVars) {
    this.extraVars = JsonNullable.<String>of(extraVars);
  }

  /**
   * Get failed
   * @return failed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FAILED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFailed() {
    return failed;
  }



  /**
   * The date and time the job finished execution.
   * @return finished
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getFinished() {
    
    if (finished == null) {
      finished = JsonNullable.<OffsetDateTime>undefined();
    }
    return finished.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FINISHED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getFinished_JsonNullable() {
    return finished;
  }
  
  @JsonProperty(JSON_PROPERTY_FINISHED)
  private void setFinished_JsonNullable(JsonNullable<OffsetDateTime> finished) {
    this.finished = finished;
  }


  public JobList forceHandlers(@jakarta.annotation.Nullable Boolean forceHandlers) {
    this.forceHandlers = JsonNullable.<Boolean>of(forceHandlers);
    
    return this;
  }

  /**
   * Get forceHandlers
   * @return forceHandlers
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getForceHandlers() {
        return forceHandlers.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FORCE_HANDLERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getForceHandlers_JsonNullable() {
    return forceHandlers;
  }
  
  @JsonProperty(JSON_PROPERTY_FORCE_HANDLERS)
  public void setForceHandlers_JsonNullable(JsonNullable<Boolean> forceHandlers) {
    this.forceHandlers = forceHandlers;
  }

  public void setForceHandlers(@jakarta.annotation.Nullable Boolean forceHandlers) {
    this.forceHandlers = JsonNullable.<Boolean>of(forceHandlers);
  }

  public JobList forks(@jakarta.annotation.Nullable Integer forks) {
    
    this.forks = forks;
    return this;
  }

  /**
   * Get forks
   * minimum: 0
   * @return forks
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FORKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getForks() {
    return forks;
  }


  @JsonProperty(JSON_PROPERTY_FORKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setForks(@jakarta.annotation.Nullable Integer forks) {
    this.forks = forks;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  public JobList instanceGroup(@jakarta.annotation.Nullable Integer instanceGroup) {
    this.instanceGroup = JsonNullable.<Integer>of(instanceGroup);
    
    return this;
  }

  /**
   * The Instance group the job was run under
   * @return instanceGroup
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getInstanceGroup() {
        return instanceGroup.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INSTANCE_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getInstanceGroup_JsonNullable() {
    return instanceGroup;
  }
  
  @JsonProperty(JSON_PROPERTY_INSTANCE_GROUP)
  public void setInstanceGroup_JsonNullable(JsonNullable<Integer> instanceGroup) {
    this.instanceGroup = instanceGroup;
  }

  public void setInstanceGroup(@jakarta.annotation.Nullable Integer instanceGroup) {
    this.instanceGroup = JsonNullable.<Integer>of(instanceGroup);
  }

  public JobList inventory(@jakarta.annotation.Nullable Integer inventory) {
    this.inventory = JsonNullable.<Integer>of(inventory);
    
    return this;
  }

  /**
   * Get inventory
   * @return inventory
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getInventory() {
        return inventory.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INVENTORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getInventory_JsonNullable() {
    return inventory;
  }
  
  @JsonProperty(JSON_PROPERTY_INVENTORY)
  public void setInventory_JsonNullable(JsonNullable<Integer> inventory) {
    this.inventory = inventory;
  }

  public void setInventory(@jakarta.annotation.Nullable Integer inventory) {
    this.inventory = JsonNullable.<Integer>of(inventory);
  }

  /**
   * A status field to indicate the state of the job if it wasn&#39;t able to run and capture stdout
   * @return jobExplanation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOB_EXPLANATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJobExplanation() {
    return jobExplanation;
  }



  public JobList jobSliceCount(@jakarta.annotation.Nullable Integer jobSliceCount) {
    
    this.jobSliceCount = jobSliceCount;
    return this;
  }

  /**
   * If ran as part of sliced jobs, the total number of slices. If 1, job is not part of a sliced job.
   * minimum: 0
   * @return jobSliceCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOB_SLICE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getJobSliceCount() {
    return jobSliceCount;
  }


  @JsonProperty(JSON_PROPERTY_JOB_SLICE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJobSliceCount(@jakarta.annotation.Nullable Integer jobSliceCount) {
    this.jobSliceCount = jobSliceCount;
  }

  public JobList jobSliceNumber(@jakarta.annotation.Nullable Integer jobSliceNumber) {
    
    this.jobSliceNumber = jobSliceNumber;
    return this;
  }

  /**
   * If part of a sliced job, the ID of the inventory slice operated on. If not part of sliced job, parameter is not used.
   * minimum: 0
   * @return jobSliceNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOB_SLICE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getJobSliceNumber() {
    return jobSliceNumber;
  }


  @JsonProperty(JSON_PROPERTY_JOB_SLICE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJobSliceNumber(@jakarta.annotation.Nullable Integer jobSliceNumber) {
    this.jobSliceNumber = jobSliceNumber;
  }

  public JobList jobTags(@jakarta.annotation.Nullable String jobTags) {
    this.jobTags = JsonNullable.<String>of(jobTags);
    
    return this;
  }

  /**
   * Get jobTags
   * @return jobTags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getJobTags() {
        return jobTags.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_JOB_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getJobTags_JsonNullable() {
    return jobTags;
  }
  
  @JsonProperty(JSON_PROPERTY_JOB_TAGS)
  public void setJobTags_JsonNullable(JsonNullable<String> jobTags) {
    this.jobTags = jobTags;
  }

  public void setJobTags(@jakarta.annotation.Nullable String jobTags) {
    this.jobTags = JsonNullable.<String>of(jobTags);
  }

  public JobList jobTemplate(@jakarta.annotation.Nullable String jobTemplate) {
    this.jobTemplate = JsonNullable.<String>of(jobTemplate);
    
    return this;
  }

  /**
   * Get jobTemplate
   * @return jobTemplate
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getJobTemplate() {
        return jobTemplate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_JOB_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getJobTemplate_JsonNullable() {
    return jobTemplate;
  }
  
  @JsonProperty(JSON_PROPERTY_JOB_TEMPLATE)
  public void setJobTemplate_JsonNullable(JsonNullable<String> jobTemplate) {
    this.jobTemplate = jobTemplate;
  }

  public void setJobTemplate(@jakarta.annotation.Nullable String jobTemplate) {
    this.jobTemplate = JsonNullable.<String>of(jobTemplate);
  }

  public JobList jobType(@jakarta.annotation.Nullable JobTypeEnum jobType) {
    this.jobType = JsonNullable.<JobTypeEnum>of(jobType);
    
    return this;
  }

  /**
   * Get jobType
   * @return jobType
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public JobTypeEnum getJobType() {
        return jobType.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_JOB_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<JobTypeEnum> getJobType_JsonNullable() {
    return jobType;
  }
  
  @JsonProperty(JSON_PROPERTY_JOB_TYPE)
  public void setJobType_JsonNullable(JsonNullable<JobTypeEnum> jobType) {
    this.jobType = jobType;
  }

  public void setJobType(@jakarta.annotation.Nullable JobTypeEnum jobType) {
    this.jobType = JsonNullable.<JobTypeEnum>of(jobType);
  }

  /**
   * Get launchType
   * @return launchType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAUNCH_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LaunchTypeEnum getLaunchType() {
    return launchType;
  }



  /**
   * Get launchedBy
   * @return launchedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAUNCHED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLaunchedBy() {
    return launchedBy;
  }



  public JobList limit(@jakarta.annotation.Nullable String limit) {
    this.limit = JsonNullable.<String>of(limit);
    
    return this;
  }

  /**
   * Get limit
   * @return limit
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getLimit() {
        return limit.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLimit_JsonNullable() {
    return limit;
  }
  
  @JsonProperty(JSON_PROPERTY_LIMIT)
  public void setLimit_JsonNullable(JsonNullable<String> limit) {
    this.limit = limit;
  }

  public void setLimit(@jakarta.annotation.Nullable String limit) {
    this.limit = JsonNullable.<String>of(limit);
  }

  /**
   * Get modified
   * @return modified
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModified() {
    return modified;
  }



  public JobList name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  /**
   * The organization used to determine access to this unified job.
   * @return organization
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getOrganization() {
    
    if (organization == null) {
      organization = JsonNullable.<Integer>undefined();
    }
    return organization.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getOrganization_JsonNullable() {
    return organization;
  }
  
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  private void setOrganization_JsonNullable(JsonNullable<Integer> organization) {
    this.organization = organization;
  }


  /**
   * Get passwordsNeededToStart
   * @return passwordsNeededToStart
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORDS_NEEDED_TO_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPasswordsNeededToStart() {
    return passwordsNeededToStart;
  }



  public JobList playbook(@jakarta.annotation.Nullable String playbook) {
    this.playbook = JsonNullable.<String>of(playbook);
    
    return this;
  }

  /**
   * Get playbook
   * @return playbook
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getPlaybook() {
        return playbook.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PLAYBOOK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPlaybook_JsonNullable() {
    return playbook;
  }
  
  @JsonProperty(JSON_PROPERTY_PLAYBOOK)
  public void setPlaybook_JsonNullable(JsonNullable<String> playbook) {
    this.playbook = playbook;
  }

  public void setPlaybook(@jakarta.annotation.Nullable String playbook) {
    this.playbook = JsonNullable.<String>of(playbook);
  }

  public JobList project(@jakarta.annotation.Nullable String project) {
    this.project = JsonNullable.<String>of(project);
    
    return this;
  }

  /**
   * Get project
   * @return project
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getProject() {
        return project.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getProject_JsonNullable() {
    return project;
  }
  
  @JsonProperty(JSON_PROPERTY_PROJECT)
  public void setProject_JsonNullable(JsonNullable<String> project) {
    this.project = project;
  }

  public void setProject(@jakarta.annotation.Nullable String project) {
    this.project = JsonNullable.<String>of(project);
  }

  /**
   * Get related
   * @return related
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelated() {
    return related;
  }



  public JobList scmBranch(@jakarta.annotation.Nullable String scmBranch) {
    this.scmBranch = JsonNullable.<String>of(scmBranch);
    
    return this;
  }

  /**
   * Branch to use in job run. Project default used if blank. Only allowed if project allow_override field is set to true.
   * @return scmBranch
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getScmBranch() {
        return scmBranch.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SCM_BRANCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getScmBranch_JsonNullable() {
    return scmBranch;
  }
  
  @JsonProperty(JSON_PROPERTY_SCM_BRANCH)
  public void setScmBranch_JsonNullable(JsonNullable<String> scmBranch) {
    this.scmBranch = scmBranch;
  }

  public void setScmBranch(@jakarta.annotation.Nullable String scmBranch) {
    this.scmBranch = JsonNullable.<String>of(scmBranch);
  }

  /**
   * The SCM Revision from the Project used for this job, if available
   * @return scmRevision
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCM_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScmRevision() {
    return scmRevision;
  }



  public JobList skipTags(@jakarta.annotation.Nullable String skipTags) {
    this.skipTags = JsonNullable.<String>of(skipTags);
    
    return this;
  }

  /**
   * Get skipTags
   * @return skipTags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getSkipTags() {
        return skipTags.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SKIP_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSkipTags_JsonNullable() {
    return skipTags;
  }
  
  @JsonProperty(JSON_PROPERTY_SKIP_TAGS)
  public void setSkipTags_JsonNullable(JsonNullable<String> skipTags) {
    this.skipTags = skipTags;
  }

  public void setSkipTags(@jakarta.annotation.Nullable String skipTags) {
    this.skipTags = JsonNullable.<String>of(skipTags);
  }

  public JobList startAtTask(@jakarta.annotation.Nullable String startAtTask) {
    this.startAtTask = JsonNullable.<String>of(startAtTask);
    
    return this;
  }

  /**
   * Get startAtTask
   * @return startAtTask
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getStartAtTask() {
        return startAtTask.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_START_AT_TASK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getStartAtTask_JsonNullable() {
    return startAtTask;
  }
  
  @JsonProperty(JSON_PROPERTY_START_AT_TASK)
  public void setStartAtTask_JsonNullable(JsonNullable<String> startAtTask) {
    this.startAtTask = startAtTask;
  }

  public void setStartAtTask(@jakarta.annotation.Nullable String startAtTask) {
    this.startAtTask = JsonNullable.<String>of(startAtTask);
  }

  /**
   * The date and time the job was queued for starting.
   * @return started
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getStarted() {
    
    if (started == null) {
      started = JsonNullable.<OffsetDateTime>undefined();
    }
    return started.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STARTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getStarted_JsonNullable() {
    return started;
  }
  
  @JsonProperty(JSON_PROPERTY_STARTED)
  private void setStarted_JsonNullable(JsonNullable<OffsetDateTime> started) {
    this.started = started;
  }


  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }



  /**
   * Get summaryFields
   * @return summaryFields
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSummaryFields() {
    return summaryFields;
  }



  public JobList timeout(@jakarta.annotation.Nullable Integer timeout) {
    
    this.timeout = timeout;
    return this;
  }

  /**
   * The amount of time (in seconds) to run before the task is canceled.
   * @return timeout
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMEOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTimeout() {
    return timeout;
  }


  @JsonProperty(JSON_PROPERTY_TIMEOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeout(@jakarta.annotation.Nullable Integer timeout) {
    this.timeout = timeout;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }



  /**
   * Get unifiedJobTemplate
   * @return unifiedJobTemplate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNIFIED_JOB_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnifiedJobTemplate() {
    return unifiedJobTemplate;
  }



  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }



  public JobList useFactCache(@jakarta.annotation.Nullable Boolean useFactCache) {
    this.useFactCache = JsonNullable.<Boolean>of(useFactCache);
    
    return this;
  }

  /**
   * If enabled, the service will act as an Ansible Fact Cache Plugin; persisting facts at the end of a playbook run to the database and caching facts for use by Ansible.
   * @return useFactCache
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getUseFactCache() {
        return useFactCache.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_USE_FACT_CACHE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getUseFactCache_JsonNullable() {
    return useFactCache;
  }
  
  @JsonProperty(JSON_PROPERTY_USE_FACT_CACHE)
  public void setUseFactCache_JsonNullable(JsonNullable<Boolean> useFactCache) {
    this.useFactCache = useFactCache;
  }

  public void setUseFactCache(@jakarta.annotation.Nullable Boolean useFactCache) {
    this.useFactCache = JsonNullable.<Boolean>of(useFactCache);
  }

  public JobList verbosity(@jakarta.annotation.Nullable Integer verbosity) {
    
    this.verbosity = verbosity;
    return this;
  }

  /**
   * Get verbosity
   * @return verbosity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERBOSITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getVerbosity() {
    return verbosity;
  }


  @JsonProperty(JSON_PROPERTY_VERBOSITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVerbosity(@jakarta.annotation.Nullable Integer verbosity) {
    this.verbosity = verbosity;
  }

  public JobList webhookCredential(@jakarta.annotation.Nullable Integer webhookCredential) {
    this.webhookCredential = JsonNullable.<Integer>of(webhookCredential);
    
    return this;
  }

  /**
   * Personal Access Token for posting back the status to the service API
   * @return webhookCredential
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getWebhookCredential() {
        return webhookCredential.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_WEBHOOK_CREDENTIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getWebhookCredential_JsonNullable() {
    return webhookCredential;
  }
  
  @JsonProperty(JSON_PROPERTY_WEBHOOK_CREDENTIAL)
  public void setWebhookCredential_JsonNullable(JsonNullable<Integer> webhookCredential) {
    this.webhookCredential = webhookCredential;
  }

  public void setWebhookCredential(@jakarta.annotation.Nullable Integer webhookCredential) {
    this.webhookCredential = JsonNullable.<Integer>of(webhookCredential);
  }

  public JobList webhookGuid(@jakarta.annotation.Nullable String webhookGuid) {
    this.webhookGuid = JsonNullable.<String>of(webhookGuid);
    
    return this;
  }

  /**
   * Unique identifier of the event that triggered this webhook
   * @return webhookGuid
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getWebhookGuid() {
        return webhookGuid.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_WEBHOOK_GUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getWebhookGuid_JsonNullable() {
    return webhookGuid;
  }
  
  @JsonProperty(JSON_PROPERTY_WEBHOOK_GUID)
  public void setWebhookGuid_JsonNullable(JsonNullable<String> webhookGuid) {
    this.webhookGuid = webhookGuid;
  }

  public void setWebhookGuid(@jakarta.annotation.Nullable String webhookGuid) {
    this.webhookGuid = JsonNullable.<String>of(webhookGuid);
  }

  public JobList webhookService(@jakarta.annotation.Nullable WebhookServiceEnum webhookService) {
    this.webhookService = JsonNullable.<WebhookServiceEnum>of(webhookService);
    
    return this;
  }

  /**
   * Service that webhook requests will be accepted from
   * @return webhookService
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public WebhookServiceEnum getWebhookService() {
        return webhookService.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_WEBHOOK_SERVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<WebhookServiceEnum> getWebhookService_JsonNullable() {
    return webhookService;
  }
  
  @JsonProperty(JSON_PROPERTY_WEBHOOK_SERVICE)
  public void setWebhookService_JsonNullable(JsonNullable<WebhookServiceEnum> webhookService) {
    this.webhookService = webhookService;
  }

  public void setWebhookService(@jakarta.annotation.Nullable WebhookServiceEnum webhookService) {
    this.webhookService = JsonNullable.<WebhookServiceEnum>of(webhookService);
  }

  /**
   * The Receptor work unit ID associated with this job.
   * @return workUnitId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getWorkUnitId() {
    
    if (workUnitId == null) {
      workUnitId = JsonNullable.<String>undefined();
    }
    return workUnitId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_WORK_UNIT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getWorkUnitId_JsonNullable() {
    return workUnitId;
  }
  
  @JsonProperty(JSON_PROPERTY_WORK_UNIT_ID)
  private void setWorkUnitId_JsonNullable(JsonNullable<String> workUnitId) {
    this.workUnitId = workUnitId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobList jobList = (JobList) o;
    return equalsNullable(this.allowSimultaneous, jobList.allowSimultaneous) &&
        Objects.equals(this.artifacts, jobList.artifacts) &&
        equalsNullable(this.canceledOn, jobList.canceledOn) &&
        Objects.equals(this.controllerNode, jobList.controllerNode) &&
        Objects.equals(this.created, jobList.created) &&
        equalsNullable(this.description, jobList.description) &&
        equalsNullable(this.diffMode, jobList.diffMode) &&
        Objects.equals(this.elapsed, jobList.elapsed) &&
        equalsNullable(this.executionEnvironment, jobList.executionEnvironment) &&
        Objects.equals(this.executionNode, jobList.executionNode) &&
        equalsNullable(this.extraVars, jobList.extraVars) &&
        Objects.equals(this.failed, jobList.failed) &&
        equalsNullable(this.finished, jobList.finished) &&
        equalsNullable(this.forceHandlers, jobList.forceHandlers) &&
        Objects.equals(this.forks, jobList.forks) &&
        Objects.equals(this.id, jobList.id) &&
        equalsNullable(this.instanceGroup, jobList.instanceGroup) &&
        equalsNullable(this.inventory, jobList.inventory) &&
        Objects.equals(this.jobExplanation, jobList.jobExplanation) &&
        Objects.equals(this.jobSliceCount, jobList.jobSliceCount) &&
        Objects.equals(this.jobSliceNumber, jobList.jobSliceNumber) &&
        equalsNullable(this.jobTags, jobList.jobTags) &&
        equalsNullable(this.jobTemplate, jobList.jobTemplate) &&
        equalsNullable(this.jobType, jobList.jobType) &&
        Objects.equals(this.launchType, jobList.launchType) &&
        Objects.equals(this.launchedBy, jobList.launchedBy) &&
        equalsNullable(this.limit, jobList.limit) &&
        Objects.equals(this.modified, jobList.modified) &&
        Objects.equals(this.name, jobList.name) &&
        equalsNullable(this.organization, jobList.organization) &&
        Objects.equals(this.passwordsNeededToStart, jobList.passwordsNeededToStart) &&
        equalsNullable(this.playbook, jobList.playbook) &&
        equalsNullable(this.project, jobList.project) &&
        Objects.equals(this.related, jobList.related) &&
        equalsNullable(this.scmBranch, jobList.scmBranch) &&
        Objects.equals(this.scmRevision, jobList.scmRevision) &&
        equalsNullable(this.skipTags, jobList.skipTags) &&
        equalsNullable(this.startAtTask, jobList.startAtTask) &&
        equalsNullable(this.started, jobList.started) &&
        Objects.equals(this.status, jobList.status) &&
        Objects.equals(this.summaryFields, jobList.summaryFields) &&
        Objects.equals(this.timeout, jobList.timeout) &&
        Objects.equals(this.type, jobList.type) &&
        Objects.equals(this.unifiedJobTemplate, jobList.unifiedJobTemplate) &&
        Objects.equals(this.url, jobList.url) &&
        equalsNullable(this.useFactCache, jobList.useFactCache) &&
        Objects.equals(this.verbosity, jobList.verbosity) &&
        equalsNullable(this.webhookCredential, jobList.webhookCredential) &&
        equalsNullable(this.webhookGuid, jobList.webhookGuid) &&
        equalsNullable(this.webhookService, jobList.webhookService) &&
        equalsNullable(this.workUnitId, jobList.workUnitId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(allowSimultaneous), artifacts, hashCodeNullable(canceledOn), controllerNode, created, hashCodeNullable(description), hashCodeNullable(diffMode), elapsed, hashCodeNullable(executionEnvironment), executionNode, hashCodeNullable(extraVars), failed, hashCodeNullable(finished), hashCodeNullable(forceHandlers), forks, id, hashCodeNullable(instanceGroup), hashCodeNullable(inventory), jobExplanation, jobSliceCount, jobSliceNumber, hashCodeNullable(jobTags), hashCodeNullable(jobTemplate), hashCodeNullable(jobType), launchType, launchedBy, hashCodeNullable(limit), modified, name, hashCodeNullable(organization), passwordsNeededToStart, hashCodeNullable(playbook), hashCodeNullable(project), related, hashCodeNullable(scmBranch), scmRevision, hashCodeNullable(skipTags), hashCodeNullable(startAtTask), hashCodeNullable(started), status, summaryFields, timeout, type, unifiedJobTemplate, url, hashCodeNullable(useFactCache), verbosity, hashCodeNullable(webhookCredential), hashCodeNullable(webhookGuid), hashCodeNullable(webhookService), hashCodeNullable(workUnitId));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobList {\n");
    sb.append("    allowSimultaneous: ").append(toIndentedString(allowSimultaneous)).append("\n");
    sb.append("    artifacts: ").append(toIndentedString(artifacts)).append("\n");
    sb.append("    canceledOn: ").append(toIndentedString(canceledOn)).append("\n");
    sb.append("    controllerNode: ").append(toIndentedString(controllerNode)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    diffMode: ").append(toIndentedString(diffMode)).append("\n");
    sb.append("    elapsed: ").append(toIndentedString(elapsed)).append("\n");
    sb.append("    executionEnvironment: ").append(toIndentedString(executionEnvironment)).append("\n");
    sb.append("    executionNode: ").append(toIndentedString(executionNode)).append("\n");
    sb.append("    extraVars: ").append(toIndentedString(extraVars)).append("\n");
    sb.append("    failed: ").append(toIndentedString(failed)).append("\n");
    sb.append("    finished: ").append(toIndentedString(finished)).append("\n");
    sb.append("    forceHandlers: ").append(toIndentedString(forceHandlers)).append("\n");
    sb.append("    forks: ").append(toIndentedString(forks)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    instanceGroup: ").append(toIndentedString(instanceGroup)).append("\n");
    sb.append("    inventory: ").append(toIndentedString(inventory)).append("\n");
    sb.append("    jobExplanation: ").append(toIndentedString(jobExplanation)).append("\n");
    sb.append("    jobSliceCount: ").append(toIndentedString(jobSliceCount)).append("\n");
    sb.append("    jobSliceNumber: ").append(toIndentedString(jobSliceNumber)).append("\n");
    sb.append("    jobTags: ").append(toIndentedString(jobTags)).append("\n");
    sb.append("    jobTemplate: ").append(toIndentedString(jobTemplate)).append("\n");
    sb.append("    jobType: ").append(toIndentedString(jobType)).append("\n");
    sb.append("    launchType: ").append(toIndentedString(launchType)).append("\n");
    sb.append("    launchedBy: ").append(toIndentedString(launchedBy)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    passwordsNeededToStart: ").append(toIndentedString(passwordsNeededToStart)).append("\n");
    sb.append("    playbook: ").append(toIndentedString(playbook)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("    scmBranch: ").append(toIndentedString(scmBranch)).append("\n");
    sb.append("    scmRevision: ").append(toIndentedString(scmRevision)).append("\n");
    sb.append("    skipTags: ").append(toIndentedString(skipTags)).append("\n");
    sb.append("    startAtTask: ").append(toIndentedString(startAtTask)).append("\n");
    sb.append("    started: ").append(toIndentedString(started)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    summaryFields: ").append(toIndentedString(summaryFields)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    unifiedJobTemplate: ").append(toIndentedString(unifiedJobTemplate)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    useFactCache: ").append(toIndentedString(useFactCache)).append("\n");
    sb.append("    verbosity: ").append(toIndentedString(verbosity)).append("\n");
    sb.append("    webhookCredential: ").append(toIndentedString(webhookCredential)).append("\n");
    sb.append("    webhookGuid: ").append(toIndentedString(webhookGuid)).append("\n");
    sb.append("    webhookService: ").append(toIndentedString(webhookService)).append("\n");
    sb.append("    workUnitId: ").append(toIndentedString(workUnitId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private JobList instance;

    public Builder() {
      this(new JobList());
    }

    protected Builder(JobList instance) {
      this.instance = instance;
    }

    public JobList.Builder allowSimultaneous(Boolean allowSimultaneous) {
      this.instance.allowSimultaneous = JsonNullable.<Boolean>of(allowSimultaneous);
      return this;
    }
    public JobList.Builder allowSimultaneous(JsonNullable<Boolean> allowSimultaneous) {
      this.instance.allowSimultaneous = allowSimultaneous;
      return this;
    }
    public JobList.Builder artifacts(String artifacts) {
      this.instance.artifacts = artifacts;
      return this;
    }
    public JobList.Builder canceledOn(OffsetDateTime canceledOn) {
      this.instance.canceledOn = JsonNullable.<OffsetDateTime>of(canceledOn);
      return this;
    }
    public JobList.Builder canceledOn(JsonNullable<OffsetDateTime> canceledOn) {
      this.instance.canceledOn = canceledOn;
      return this;
    }
    public JobList.Builder controllerNode(String controllerNode) {
      this.instance.controllerNode = controllerNode;
      return this;
    }
    public JobList.Builder created(String created) {
      this.instance.created = created;
      return this;
    }
    public JobList.Builder description(String description) {
      this.instance.description = JsonNullable.<String>of(description);
      return this;
    }
    public JobList.Builder description(JsonNullable<String> description) {
      this.instance.description = description;
      return this;
    }
    public JobList.Builder diffMode(Boolean diffMode) {
      this.instance.diffMode = JsonNullable.<Boolean>of(diffMode);
      return this;
    }
    public JobList.Builder diffMode(JsonNullable<Boolean> diffMode) {
      this.instance.diffMode = diffMode;
      return this;
    }
    public JobList.Builder elapsed(BigDecimal elapsed) {
      this.instance.elapsed = elapsed;
      return this;
    }
    public JobList.Builder executionEnvironment(Integer executionEnvironment) {
      this.instance.executionEnvironment = JsonNullable.<Integer>of(executionEnvironment);
      return this;
    }
    public JobList.Builder executionEnvironment(JsonNullable<Integer> executionEnvironment) {
      this.instance.executionEnvironment = executionEnvironment;
      return this;
    }
    public JobList.Builder executionNode(String executionNode) {
      this.instance.executionNode = executionNode;
      return this;
    }
    public JobList.Builder extraVars(String extraVars) {
      this.instance.extraVars = JsonNullable.<String>of(extraVars);
      return this;
    }
    public JobList.Builder extraVars(JsonNullable<String> extraVars) {
      this.instance.extraVars = extraVars;
      return this;
    }
    public JobList.Builder failed(Boolean failed) {
      this.instance.failed = failed;
      return this;
    }
    public JobList.Builder finished(OffsetDateTime finished) {
      this.instance.finished = JsonNullable.<OffsetDateTime>of(finished);
      return this;
    }
    public JobList.Builder finished(JsonNullable<OffsetDateTime> finished) {
      this.instance.finished = finished;
      return this;
    }
    public JobList.Builder forceHandlers(Boolean forceHandlers) {
      this.instance.forceHandlers = JsonNullable.<Boolean>of(forceHandlers);
      return this;
    }
    public JobList.Builder forceHandlers(JsonNullable<Boolean> forceHandlers) {
      this.instance.forceHandlers = forceHandlers;
      return this;
    }
    public JobList.Builder forks(Integer forks) {
      this.instance.forks = forks;
      return this;
    }
    public JobList.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public JobList.Builder instanceGroup(Integer instanceGroup) {
      this.instance.instanceGroup = JsonNullable.<Integer>of(instanceGroup);
      return this;
    }
    public JobList.Builder instanceGroup(JsonNullable<Integer> instanceGroup) {
      this.instance.instanceGroup = instanceGroup;
      return this;
    }
    public JobList.Builder inventory(Integer inventory) {
      this.instance.inventory = JsonNullable.<Integer>of(inventory);
      return this;
    }
    public JobList.Builder inventory(JsonNullable<Integer> inventory) {
      this.instance.inventory = inventory;
      return this;
    }
    public JobList.Builder jobExplanation(String jobExplanation) {
      this.instance.jobExplanation = jobExplanation;
      return this;
    }
    public JobList.Builder jobSliceCount(Integer jobSliceCount) {
      this.instance.jobSliceCount = jobSliceCount;
      return this;
    }
    public JobList.Builder jobSliceNumber(Integer jobSliceNumber) {
      this.instance.jobSliceNumber = jobSliceNumber;
      return this;
    }
    public JobList.Builder jobTags(String jobTags) {
      this.instance.jobTags = JsonNullable.<String>of(jobTags);
      return this;
    }
    public JobList.Builder jobTags(JsonNullable<String> jobTags) {
      this.instance.jobTags = jobTags;
      return this;
    }
    public JobList.Builder jobTemplate(String jobTemplate) {
      this.instance.jobTemplate = JsonNullable.<String>of(jobTemplate);
      return this;
    }
    public JobList.Builder jobTemplate(JsonNullable<String> jobTemplate) {
      this.instance.jobTemplate = jobTemplate;
      return this;
    }
    public JobList.Builder jobType(JobTypeEnum jobType) {
      this.instance.jobType = JsonNullable.<JobTypeEnum>of(jobType);
      return this;
    }
    public JobList.Builder jobType(JsonNullable<JobTypeEnum> jobType) {
      this.instance.jobType = jobType;
      return this;
    }
    public JobList.Builder launchType(LaunchTypeEnum launchType) {
      this.instance.launchType = launchType;
      return this;
    }
    public JobList.Builder launchedBy(String launchedBy) {
      this.instance.launchedBy = launchedBy;
      return this;
    }
    public JobList.Builder limit(String limit) {
      this.instance.limit = JsonNullable.<String>of(limit);
      return this;
    }
    public JobList.Builder limit(JsonNullable<String> limit) {
      this.instance.limit = limit;
      return this;
    }
    public JobList.Builder modified(String modified) {
      this.instance.modified = modified;
      return this;
    }
    public JobList.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public JobList.Builder organization(Integer organization) {
      this.instance.organization = JsonNullable.<Integer>of(organization);
      return this;
    }
    public JobList.Builder organization(JsonNullable<Integer> organization) {
      this.instance.organization = organization;
      return this;
    }
    public JobList.Builder passwordsNeededToStart(String passwordsNeededToStart) {
      this.instance.passwordsNeededToStart = passwordsNeededToStart;
      return this;
    }
    public JobList.Builder playbook(String playbook) {
      this.instance.playbook = JsonNullable.<String>of(playbook);
      return this;
    }
    public JobList.Builder playbook(JsonNullable<String> playbook) {
      this.instance.playbook = playbook;
      return this;
    }
    public JobList.Builder project(String project) {
      this.instance.project = JsonNullable.<String>of(project);
      return this;
    }
    public JobList.Builder project(JsonNullable<String> project) {
      this.instance.project = project;
      return this;
    }
    public JobList.Builder related(String related) {
      this.instance.related = related;
      return this;
    }
    public JobList.Builder scmBranch(String scmBranch) {
      this.instance.scmBranch = JsonNullable.<String>of(scmBranch);
      return this;
    }
    public JobList.Builder scmBranch(JsonNullable<String> scmBranch) {
      this.instance.scmBranch = scmBranch;
      return this;
    }
    public JobList.Builder scmRevision(String scmRevision) {
      this.instance.scmRevision = scmRevision;
      return this;
    }
    public JobList.Builder skipTags(String skipTags) {
      this.instance.skipTags = JsonNullable.<String>of(skipTags);
      return this;
    }
    public JobList.Builder skipTags(JsonNullable<String> skipTags) {
      this.instance.skipTags = skipTags;
      return this;
    }
    public JobList.Builder startAtTask(String startAtTask) {
      this.instance.startAtTask = JsonNullable.<String>of(startAtTask);
      return this;
    }
    public JobList.Builder startAtTask(JsonNullable<String> startAtTask) {
      this.instance.startAtTask = startAtTask;
      return this;
    }
    public JobList.Builder started(OffsetDateTime started) {
      this.instance.started = JsonNullable.<OffsetDateTime>of(started);
      return this;
    }
    public JobList.Builder started(JsonNullable<OffsetDateTime> started) {
      this.instance.started = started;
      return this;
    }
    public JobList.Builder status(StatusEnum status) {
      this.instance.status = status;
      return this;
    }
    public JobList.Builder summaryFields(String summaryFields) {
      this.instance.summaryFields = summaryFields;
      return this;
    }
    public JobList.Builder timeout(Integer timeout) {
      this.instance.timeout = timeout;
      return this;
    }
    public JobList.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public JobList.Builder unifiedJobTemplate(String unifiedJobTemplate) {
      this.instance.unifiedJobTemplate = unifiedJobTemplate;
      return this;
    }
    public JobList.Builder url(String url) {
      this.instance.url = url;
      return this;
    }
    public JobList.Builder useFactCache(Boolean useFactCache) {
      this.instance.useFactCache = JsonNullable.<Boolean>of(useFactCache);
      return this;
    }
    public JobList.Builder useFactCache(JsonNullable<Boolean> useFactCache) {
      this.instance.useFactCache = useFactCache;
      return this;
    }
    public JobList.Builder verbosity(Integer verbosity) {
      this.instance.verbosity = verbosity;
      return this;
    }
    public JobList.Builder webhookCredential(Integer webhookCredential) {
      this.instance.webhookCredential = JsonNullable.<Integer>of(webhookCredential);
      return this;
    }
    public JobList.Builder webhookCredential(JsonNullable<Integer> webhookCredential) {
      this.instance.webhookCredential = webhookCredential;
      return this;
    }
    public JobList.Builder webhookGuid(String webhookGuid) {
      this.instance.webhookGuid = JsonNullable.<String>of(webhookGuid);
      return this;
    }
    public JobList.Builder webhookGuid(JsonNullable<String> webhookGuid) {
      this.instance.webhookGuid = webhookGuid;
      return this;
    }
    public JobList.Builder webhookService(WebhookServiceEnum webhookService) {
      this.instance.webhookService = JsonNullable.<WebhookServiceEnum>of(webhookService);
      return this;
    }
    public JobList.Builder webhookService(JsonNullable<WebhookServiceEnum> webhookService) {
      this.instance.webhookService = webhookService;
      return this;
    }
    public JobList.Builder workUnitId(String workUnitId) {
      this.instance.workUnitId = JsonNullable.<String>of(workUnitId);
      return this;
    }
    public JobList.Builder workUnitId(JsonNullable<String> workUnitId) {
      this.instance.workUnitId = workUnitId;
      return this;
    }


    /**
    * returns a built JobList instance.
    *
    * The builder is not reusable.
    */
    public JobList build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static JobList.Builder builder() {
    return new JobList.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public JobList.Builder toBuilder() {
    return new JobList.Builder()
      .allowSimultaneous(getAllowSimultaneous())
      .artifacts(getArtifacts())
      .canceledOn(getCanceledOn())
      .controllerNode(getControllerNode())
      .created(getCreated())
      .description(getDescription())
      .diffMode(getDiffMode())
      .elapsed(getElapsed())
      .executionEnvironment(getExecutionEnvironment())
      .executionNode(getExecutionNode())
      .extraVars(getExtraVars())
      .failed(getFailed())
      .finished(getFinished())
      .forceHandlers(getForceHandlers())
      .forks(getForks())
      .id(getId())
      .instanceGroup(getInstanceGroup())
      .inventory(getInventory())
      .jobExplanation(getJobExplanation())
      .jobSliceCount(getJobSliceCount())
      .jobSliceNumber(getJobSliceNumber())
      .jobTags(getJobTags())
      .jobTemplate(getJobTemplate())
      .jobType(getJobType())
      .launchType(getLaunchType())
      .launchedBy(getLaunchedBy())
      .limit(getLimit())
      .modified(getModified())
      .name(getName())
      .organization(getOrganization())
      .passwordsNeededToStart(getPasswordsNeededToStart())
      .playbook(getPlaybook())
      .project(getProject())
      .related(getRelated())
      .scmBranch(getScmBranch())
      .scmRevision(getScmRevision())
      .skipTags(getSkipTags())
      .startAtTask(getStartAtTask())
      .started(getStarted())
      .status(getStatus())
      .summaryFields(getSummaryFields())
      .timeout(getTimeout())
      .type(getType())
      .unifiedJobTemplate(getUnifiedJobTemplate())
      .url(getUrl())
      .useFactCache(getUseFactCache())
      .verbosity(getVerbosity())
      .webhookCredential(getWebhookCredential())
      .webhookGuid(getWebhookGuid())
      .webhookService(getWebhookService())
      .workUnitId(getWorkUnitId());
  }


}

