/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * JobRelaunch
 */
@JsonPropertyOrder({
  JobRelaunch.JSON_PROPERTY_CREDENTIAL_PASSWORDS,
  JobRelaunch.JSON_PROPERTY_HOSTS,
  JobRelaunch.JSON_PROPERTY_JOB_TYPE,
  JobRelaunch.JSON_PROPERTY_PASSWORDS_NEEDED_TO_START,
  JobRelaunch.JSON_PROPERTY_RETRY_COUNTS
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class JobRelaunch implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CREDENTIAL_PASSWORDS = "credential_passwords";
  @jakarta.annotation.Nonnull
  private String credentialPasswords;

  /**
   * Gets or Sets hosts
   */
  public enum HostsEnum {
    ALL(String.valueOf("all")),
    
    FAILED(String.valueOf("failed"));

    private String value;

    HostsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static HostsEnum fromValue(String value) {
      for (HostsEnum b : HostsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_HOSTS = "hosts";
  @jakarta.annotation.Nullable
  private JsonNullable<HostsEnum> hosts = JsonNullable.<HostsEnum>of(HostsEnum.ALL);

  /**
   * Gets or Sets jobType
   */
  public enum JobTypeEnum {
    RUN(String.valueOf("run")),
    
    CHECK(String.valueOf("check"));

    private String value;

    JobTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static JobTypeEnum fromValue(String value) {
      for (JobTypeEnum b : JobTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_JOB_TYPE = "job_type";
  @jakarta.annotation.Nullable
  private JsonNullable<JobTypeEnum> jobType = JsonNullable.<JobTypeEnum>undefined();

  public static final String JSON_PROPERTY_PASSWORDS_NEEDED_TO_START = "passwords_needed_to_start";
  @jakarta.annotation.Nullable
  private String passwordsNeededToStart;

  public static final String JSON_PROPERTY_RETRY_COUNTS = "retry_counts";
  @jakarta.annotation.Nullable
  private String retryCounts;

  public JobRelaunch() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public JobRelaunch(
    @JsonProperty(JSON_PROPERTY_PASSWORDS_NEEDED_TO_START) String passwordsNeededToStart, 
    @JsonProperty(JSON_PROPERTY_RETRY_COUNTS) String retryCounts
  ) {
    this();
    this.passwordsNeededToStart = passwordsNeededToStart;
    this.retryCounts = retryCounts;
  }

  public JobRelaunch credentialPasswords(@jakarta.annotation.Nonnull String credentialPasswords) {
    
    this.credentialPasswords = credentialPasswords;
    return this;
  }

  /**
   * Get credentialPasswords
   * @return credentialPasswords
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREDENTIAL_PASSWORDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCredentialPasswords() {
    return credentialPasswords;
  }


  @JsonProperty(JSON_PROPERTY_CREDENTIAL_PASSWORDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCredentialPasswords(@jakarta.annotation.Nonnull String credentialPasswords) {
    this.credentialPasswords = credentialPasswords;
  }

  public JobRelaunch hosts(@jakarta.annotation.Nullable HostsEnum hosts) {
    this.hosts = JsonNullable.<HostsEnum>of(hosts);
    
    return this;
  }

  /**
   * Get hosts
   * @return hosts
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public HostsEnum getHosts() {
        return hosts.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_HOSTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<HostsEnum> getHosts_JsonNullable() {
    return hosts;
  }
  
  @JsonProperty(JSON_PROPERTY_HOSTS)
  public void setHosts_JsonNullable(JsonNullable<HostsEnum> hosts) {
    this.hosts = hosts;
  }

  public void setHosts(@jakarta.annotation.Nullable HostsEnum hosts) {
    this.hosts = JsonNullable.<HostsEnum>of(hosts);
  }

  public JobRelaunch jobType(@jakarta.annotation.Nullable JobTypeEnum jobType) {
    this.jobType = JsonNullable.<JobTypeEnum>of(jobType);
    
    return this;
  }

  /**
   * Get jobType
   * @return jobType
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public JobTypeEnum getJobType() {
        return jobType.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_JOB_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<JobTypeEnum> getJobType_JsonNullable() {
    return jobType;
  }
  
  @JsonProperty(JSON_PROPERTY_JOB_TYPE)
  public void setJobType_JsonNullable(JsonNullable<JobTypeEnum> jobType) {
    this.jobType = jobType;
  }

  public void setJobType(@jakarta.annotation.Nullable JobTypeEnum jobType) {
    this.jobType = JsonNullable.<JobTypeEnum>of(jobType);
  }

  /**
   * Get passwordsNeededToStart
   * @return passwordsNeededToStart
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORDS_NEEDED_TO_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPasswordsNeededToStart() {
    return passwordsNeededToStart;
  }



  /**
   * Get retryCounts
   * @return retryCounts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RETRY_COUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRetryCounts() {
    return retryCounts;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobRelaunch jobRelaunch = (JobRelaunch) o;
    return Objects.equals(this.credentialPasswords, jobRelaunch.credentialPasswords) &&
        equalsNullable(this.hosts, jobRelaunch.hosts) &&
        equalsNullable(this.jobType, jobRelaunch.jobType) &&
        Objects.equals(this.passwordsNeededToStart, jobRelaunch.passwordsNeededToStart) &&
        Objects.equals(this.retryCounts, jobRelaunch.retryCounts);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(credentialPasswords, hashCodeNullable(hosts), hashCodeNullable(jobType), passwordsNeededToStart, retryCounts);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobRelaunch {\n");
    sb.append("    credentialPasswords: ").append(toIndentedString(credentialPasswords)).append("\n");
    sb.append("    hosts: ").append(toIndentedString(hosts)).append("\n");
    sb.append("    jobType: ").append(toIndentedString(jobType)).append("\n");
    sb.append("    passwordsNeededToStart: ").append(toIndentedString(passwordsNeededToStart)).append("\n");
    sb.append("    retryCounts: ").append(toIndentedString(retryCounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private JobRelaunch instance;

    public Builder() {
      this(new JobRelaunch());
    }

    protected Builder(JobRelaunch instance) {
      this.instance = instance;
    }

    public JobRelaunch.Builder credentialPasswords(String credentialPasswords) {
      this.instance.credentialPasswords = credentialPasswords;
      return this;
    }
    public JobRelaunch.Builder hosts(HostsEnum hosts) {
      this.instance.hosts = JsonNullable.<HostsEnum>of(hosts);
      return this;
    }
    public JobRelaunch.Builder hosts(JsonNullable<HostsEnum> hosts) {
      this.instance.hosts = hosts;
      return this;
    }
    public JobRelaunch.Builder jobType(JobTypeEnum jobType) {
      this.instance.jobType = JsonNullable.<JobTypeEnum>of(jobType);
      return this;
    }
    public JobRelaunch.Builder jobType(JsonNullable<JobTypeEnum> jobType) {
      this.instance.jobType = jobType;
      return this;
    }
    public JobRelaunch.Builder passwordsNeededToStart(String passwordsNeededToStart) {
      this.instance.passwordsNeededToStart = passwordsNeededToStart;
      return this;
    }
    public JobRelaunch.Builder retryCounts(String retryCounts) {
      this.instance.retryCounts = retryCounts;
      return this;
    }


    /**
    * returns a built JobRelaunch instance.
    *
    * The builder is not reusable.
    */
    public JobRelaunch build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static JobRelaunch.Builder builder() {
    return new JobRelaunch.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public JobRelaunch.Builder toBuilder() {
    return new JobRelaunch.Builder()
      .credentialPasswords(getCredentialPasswords())
      .hosts(getHosts())
      .jobType(getJobType())
      .passwordsNeededToStart(getPasswordsNeededToStart())
      .retryCounts(getRetryCounts());
  }


}

