/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Label
 */
@JsonPropertyOrder({
  Label.JSON_PROPERTY_CREATED,
  Label.JSON_PROPERTY_ID,
  Label.JSON_PROPERTY_MODIFIED,
  Label.JSON_PROPERTY_NAME,
  Label.JSON_PROPERTY_ORGANIZATION,
  Label.JSON_PROPERTY_RELATED,
  Label.JSON_PROPERTY_SUMMARY_FIELDS,
  Label.JSON_PROPERTY_TYPE,
  Label.JSON_PROPERTY_URL
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class Label implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CREATED = "created";
  @jakarta.annotation.Nullable
  private String created;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  @jakarta.annotation.Nullable
  private String modified;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  @jakarta.annotation.Nonnull
  private Integer organization;

  public static final String JSON_PROPERTY_RELATED = "related";
  @jakarta.annotation.Nullable
  private String related;

  public static final String JSON_PROPERTY_SUMMARY_FIELDS = "summary_fields";
  @jakarta.annotation.Nullable
  private String summaryFields;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public Label() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public Label(
    @JsonProperty(JSON_PROPERTY_CREATED) String created, 
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_MODIFIED) String modified, 
    @JsonProperty(JSON_PROPERTY_RELATED) String related, 
    @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS) String summaryFields, 
    @JsonProperty(JSON_PROPERTY_TYPE) String type, 
    @JsonProperty(JSON_PROPERTY_URL) String url
  ) {
    this();
    this.created = created;
    this.id = id;
    this.modified = modified;
    this.related = related;
    this.summaryFields = summaryFields;
    this.type = type;
    this.url = url;
  }

  /**
   * Get created
   * @return created
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }



  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  /**
   * Get modified
   * @return modified
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModified() {
    return modified;
  }



  public Label name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public Label organization(@jakarta.annotation.Nonnull Integer organization) {
    
    this.organization = organization;
    return this;
  }

  /**
   * Organization this label belongs to.
   * @return organization
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getOrganization() {
    return organization;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrganization(@jakarta.annotation.Nonnull Integer organization) {
    this.organization = organization;
  }

  /**
   * Get related
   * @return related
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelated() {
    return related;
  }



  /**
   * Get summaryFields
   * @return summaryFields
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSummaryFields() {
    return summaryFields;
  }



  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }



  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Label label = (Label) o;
    return Objects.equals(this.created, label.created) &&
        Objects.equals(this.id, label.id) &&
        Objects.equals(this.modified, label.modified) &&
        Objects.equals(this.name, label.name) &&
        Objects.equals(this.organization, label.organization) &&
        Objects.equals(this.related, label.related) &&
        Objects.equals(this.summaryFields, label.summaryFields) &&
        Objects.equals(this.type, label.type) &&
        Objects.equals(this.url, label.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, id, modified, name, organization, related, summaryFields, type, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Label {\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("    summaryFields: ").append(toIndentedString(summaryFields)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private Label instance;

    public Builder() {
      this(new Label());
    }

    protected Builder(Label instance) {
      this.instance = instance;
    }

    public Label.Builder created(String created) {
      this.instance.created = created;
      return this;
    }
    public Label.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public Label.Builder modified(String modified) {
      this.instance.modified = modified;
      return this;
    }
    public Label.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public Label.Builder organization(Integer organization) {
      this.instance.organization = organization;
      return this;
    }
    public Label.Builder related(String related) {
      this.instance.related = related;
      return this;
    }
    public Label.Builder summaryFields(String summaryFields) {
      this.instance.summaryFields = summaryFields;
      return this;
    }
    public Label.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public Label.Builder url(String url) {
      this.instance.url = url;
      return this;
    }


    /**
    * returns a built Label instance.
    *
    * The builder is not reusable.
    */
    public Label build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static Label.Builder builder() {
    return new Label.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public Label.Builder toBuilder() {
    return new Label.Builder()
      .created(getCreated())
      .id(getId())
      .modified(getModified())
      .name(getName())
      .organization(getOrganization())
      .related(getRelated())
      .summaryFields(getSummaryFields())
      .type(getType())
      .url(getUrl());
  }


}

