/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProjectUpdateDetail
 */
@JsonPropertyOrder({
  ProjectUpdateDetail.JSON_PROPERTY_CANCELED_ON,
  ProjectUpdateDetail.JSON_PROPERTY_CREATED,
  ProjectUpdateDetail.JSON_PROPERTY_CREDENTIAL,
  ProjectUpdateDetail.JSON_PROPERTY_DESCRIPTION,
  ProjectUpdateDetail.JSON_PROPERTY_ELAPSED,
  ProjectUpdateDetail.JSON_PROPERTY_EVENT_PROCESSING_FINISHED,
  ProjectUpdateDetail.JSON_PROPERTY_EXECUTION_ENVIRONMENT,
  ProjectUpdateDetail.JSON_PROPERTY_EXECUTION_NODE,
  ProjectUpdateDetail.JSON_PROPERTY_FAILED,
  ProjectUpdateDetail.JSON_PROPERTY_FINISHED,
  ProjectUpdateDetail.JSON_PROPERTY_HOST_STATUS_COUNTS,
  ProjectUpdateDetail.JSON_PROPERTY_ID,
  ProjectUpdateDetail.JSON_PROPERTY_JOB_ARGS,
  ProjectUpdateDetail.JSON_PROPERTY_JOB_CWD,
  ProjectUpdateDetail.JSON_PROPERTY_JOB_ENV,
  ProjectUpdateDetail.JSON_PROPERTY_JOB_EXPLANATION,
  ProjectUpdateDetail.JSON_PROPERTY_JOB_TAGS,
  ProjectUpdateDetail.JSON_PROPERTY_JOB_TYPE,
  ProjectUpdateDetail.JSON_PROPERTY_LAUNCH_TYPE,
  ProjectUpdateDetail.JSON_PROPERTY_LAUNCHED_BY,
  ProjectUpdateDetail.JSON_PROPERTY_LOCAL_PATH,
  ProjectUpdateDetail.JSON_PROPERTY_MODIFIED,
  ProjectUpdateDetail.JSON_PROPERTY_NAME,
  ProjectUpdateDetail.JSON_PROPERTY_PLAYBOOK_COUNTS,
  ProjectUpdateDetail.JSON_PROPERTY_PROJECT,
  ProjectUpdateDetail.JSON_PROPERTY_RELATED,
  ProjectUpdateDetail.JSON_PROPERTY_RESULT_TRACEBACK,
  ProjectUpdateDetail.JSON_PROPERTY_SCM_BRANCH,
  ProjectUpdateDetail.JSON_PROPERTY_SCM_CLEAN,
  ProjectUpdateDetail.JSON_PROPERTY_SCM_DELETE_ON_UPDATE,
  ProjectUpdateDetail.JSON_PROPERTY_SCM_REFSPEC,
  ProjectUpdateDetail.JSON_PROPERTY_SCM_REVISION,
  ProjectUpdateDetail.JSON_PROPERTY_SCM_TRACK_SUBMODULES,
  ProjectUpdateDetail.JSON_PROPERTY_SCM_TYPE,
  ProjectUpdateDetail.JSON_PROPERTY_SCM_URL,
  ProjectUpdateDetail.JSON_PROPERTY_STARTED,
  ProjectUpdateDetail.JSON_PROPERTY_STATUS,
  ProjectUpdateDetail.JSON_PROPERTY_SUMMARY_FIELDS,
  ProjectUpdateDetail.JSON_PROPERTY_TIMEOUT,
  ProjectUpdateDetail.JSON_PROPERTY_TYPE,
  ProjectUpdateDetail.JSON_PROPERTY_UNIFIED_JOB_TEMPLATE,
  ProjectUpdateDetail.JSON_PROPERTY_URL,
  ProjectUpdateDetail.JSON_PROPERTY_WORK_UNIT_ID
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ProjectUpdateDetail implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CANCELED_ON = "canceled_on";
  @jakarta.annotation.Nullable
  private JsonNullable<OffsetDateTime> canceledOn = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_CREATED = "created";
  @jakarta.annotation.Nullable
  private String created;

  public static final String JSON_PROPERTY_CREDENTIAL = "credential";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> credential = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private JsonNullable<String> description = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_ELAPSED = "elapsed";
  @jakarta.annotation.Nullable
  private BigDecimal elapsed;

  public static final String JSON_PROPERTY_EVENT_PROCESSING_FINISHED = "event_processing_finished";
  @jakarta.annotation.Nullable
  private Boolean eventProcessingFinished;

  public static final String JSON_PROPERTY_EXECUTION_ENVIRONMENT = "execution_environment";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> executionEnvironment = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_EXECUTION_NODE = "execution_node";
  @jakarta.annotation.Nullable
  private String executionNode;

  public static final String JSON_PROPERTY_FAILED = "failed";
  @jakarta.annotation.Nullable
  private Boolean failed;

  public static final String JSON_PROPERTY_FINISHED = "finished";
  @jakarta.annotation.Nullable
  private JsonNullable<OffsetDateTime> finished = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_HOST_STATUS_COUNTS = "host_status_counts";
  @jakarta.annotation.Nullable
  private JsonNullable<Object> hostStatusCounts = JsonNullable.<Object>undefined();

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_JOB_ARGS = "job_args";
  @jakarta.annotation.Nullable
  private String jobArgs;

  public static final String JSON_PROPERTY_JOB_CWD = "job_cwd";
  @jakarta.annotation.Nullable
  private String jobCwd;

  public static final String JSON_PROPERTY_JOB_ENV = "job_env";
  @jakarta.annotation.Nullable
  private Object jobEnv;

  public static final String JSON_PROPERTY_JOB_EXPLANATION = "job_explanation";
  @jakarta.annotation.Nullable
  private String jobExplanation;

  public static final String JSON_PROPERTY_JOB_TAGS = "job_tags";
  @jakarta.annotation.Nullable
  private JsonNullable<String> jobTags = JsonNullable.<String>of("");

  /**
   * Gets or Sets jobType
   */
  public enum JobTypeEnum {
    RUN(String.valueOf("run")),
    
    CHECK(String.valueOf("check"));

    private String value;

    JobTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static JobTypeEnum fromValue(String value) {
      for (JobTypeEnum b : JobTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_JOB_TYPE = "job_type";
  @jakarta.annotation.Nullable
  private JsonNullable<JobTypeEnum> jobType = JsonNullable.<JobTypeEnum>of(JobTypeEnum.CHECK);

  /**
   * Gets or Sets launchType
   */
  public enum LaunchTypeEnum {
    MANUAL(String.valueOf("manual")),
    
    RELAUNCH(String.valueOf("relaunch")),
    
    CALLBACK(String.valueOf("callback")),
    
    SCHEDULED(String.valueOf("scheduled")),
    
    DEPENDENCY(String.valueOf("dependency")),
    
    WORKFLOW(String.valueOf("workflow")),
    
    WEBHOOK(String.valueOf("webhook")),
    
    SYNC(String.valueOf("sync")),
    
    SCM(String.valueOf("scm"));

    private String value;

    LaunchTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LaunchTypeEnum fromValue(String value) {
      for (LaunchTypeEnum b : LaunchTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LAUNCH_TYPE = "launch_type";
  @jakarta.annotation.Nullable
  private LaunchTypeEnum launchType;

  public static final String JSON_PROPERTY_LAUNCHED_BY = "launched_by";
  @jakarta.annotation.Nullable
  private String launchedBy;

  public static final String JSON_PROPERTY_LOCAL_PATH = "local_path";
  @jakarta.annotation.Nullable
  private JsonNullable<String> localPath = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  @jakarta.annotation.Nullable
  private String modified;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_PLAYBOOK_COUNTS = "playbook_counts";
  @jakarta.annotation.Nullable
  private String playbookCounts;

  public static final String JSON_PROPERTY_PROJECT = "project";
  @jakarta.annotation.Nullable
  private String project;

  public static final String JSON_PROPERTY_RELATED = "related";
  @jakarta.annotation.Nullable
  private String related;

  public static final String JSON_PROPERTY_RESULT_TRACEBACK = "result_traceback";
  @jakarta.annotation.Nullable
  private String resultTraceback;

  public static final String JSON_PROPERTY_SCM_BRANCH = "scm_branch";
  @jakarta.annotation.Nullable
  private JsonNullable<String> scmBranch = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_SCM_CLEAN = "scm_clean";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> scmClean = JsonNullable.<Boolean>of(false);

  public static final String JSON_PROPERTY_SCM_DELETE_ON_UPDATE = "scm_delete_on_update";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> scmDeleteOnUpdate = JsonNullable.<Boolean>of(false);

  public static final String JSON_PROPERTY_SCM_REFSPEC = "scm_refspec";
  @jakarta.annotation.Nullable
  private JsonNullable<String> scmRefspec = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_SCM_REVISION = "scm_revision";
  @jakarta.annotation.Nullable
  private String scmRevision;

  public static final String JSON_PROPERTY_SCM_TRACK_SUBMODULES = "scm_track_submodules";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> scmTrackSubmodules = JsonNullable.<Boolean>of(false);

  /**
   * Specifies the source control system used to store the project.
   */
  public enum ScmTypeEnum {
    EMPTY(String.valueOf("")),
    
    GIT(String.valueOf("git")),
    
    SVN(String.valueOf("svn")),
    
    INSIGHTS(String.valueOf("insights")),
    
    ARCHIVE(String.valueOf("archive"));

    private String value;

    ScmTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ScmTypeEnum fromValue(String value) {
      for (ScmTypeEnum b : ScmTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_SCM_TYPE = "scm_type";
  @jakarta.annotation.Nullable
  private JsonNullable<ScmTypeEnum> scmType = JsonNullable.<ScmTypeEnum>of(ScmTypeEnum.EMPTY);

  public static final String JSON_PROPERTY_SCM_URL = "scm_url";
  @jakarta.annotation.Nullable
  private JsonNullable<String> scmUrl = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_STARTED = "started";
  @jakarta.annotation.Nullable
  private JsonNullable<OffsetDateTime> started = JsonNullable.<OffsetDateTime>undefined();

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    NEW(String.valueOf("new")),
    
    PENDING(String.valueOf("pending")),
    
    WAITING(String.valueOf("waiting")),
    
    RUNNING(String.valueOf("running")),
    
    SUCCESSFUL(String.valueOf("successful")),
    
    FAILED(String.valueOf("failed")),
    
    ERROR(String.valueOf("error")),
    
    CANCELED(String.valueOf("canceled"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_SUMMARY_FIELDS = "summary_fields";
  @jakarta.annotation.Nullable
  private String summaryFields;

  public static final String JSON_PROPERTY_TIMEOUT = "timeout";
  @jakarta.annotation.Nullable
  private Integer timeout;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_UNIFIED_JOB_TEMPLATE = "unified_job_template";
  @jakarta.annotation.Nullable
  private String unifiedJobTemplate;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_WORK_UNIT_ID = "work_unit_id";
  @jakarta.annotation.Nullable
  private JsonNullable<String> workUnitId = JsonNullable.<String>undefined();

  public ProjectUpdateDetail() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public ProjectUpdateDetail(
    @JsonProperty(JSON_PROPERTY_CANCELED_ON) OffsetDateTime canceledOn, 
    @JsonProperty(JSON_PROPERTY_CREATED) String created, 
    @JsonProperty(JSON_PROPERTY_ELAPSED) BigDecimal elapsed, 
    @JsonProperty(JSON_PROPERTY_EVENT_PROCESSING_FINISHED) Boolean eventProcessingFinished, 
    @JsonProperty(JSON_PROPERTY_EXECUTION_NODE) String executionNode, 
    @JsonProperty(JSON_PROPERTY_FAILED) Boolean failed, 
    @JsonProperty(JSON_PROPERTY_FINISHED) OffsetDateTime finished, 
    @JsonProperty(JSON_PROPERTY_HOST_STATUS_COUNTS) Object hostStatusCounts, 
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_JOB_ARGS) String jobArgs, 
    @JsonProperty(JSON_PROPERTY_JOB_CWD) String jobCwd, 
    @JsonProperty(JSON_PROPERTY_JOB_ENV) Object jobEnv, 
    @JsonProperty(JSON_PROPERTY_JOB_EXPLANATION) String jobExplanation, 
    @JsonProperty(JSON_PROPERTY_LAUNCH_TYPE) LaunchTypeEnum launchType, 
    @JsonProperty(JSON_PROPERTY_LAUNCHED_BY) String launchedBy, 
    @JsonProperty(JSON_PROPERTY_MODIFIED) String modified, 
    @JsonProperty(JSON_PROPERTY_PLAYBOOK_COUNTS) String playbookCounts, 
    @JsonProperty(JSON_PROPERTY_PROJECT) String project, 
    @JsonProperty(JSON_PROPERTY_RELATED) String related, 
    @JsonProperty(JSON_PROPERTY_RESULT_TRACEBACK) String resultTraceback, 
    @JsonProperty(JSON_PROPERTY_SCM_REVISION) String scmRevision, 
    @JsonProperty(JSON_PROPERTY_STARTED) OffsetDateTime started, 
    @JsonProperty(JSON_PROPERTY_STATUS) StatusEnum status, 
    @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS) String summaryFields, 
    @JsonProperty(JSON_PROPERTY_TYPE) String type, 
    @JsonProperty(JSON_PROPERTY_UNIFIED_JOB_TEMPLATE) String unifiedJobTemplate, 
    @JsonProperty(JSON_PROPERTY_URL) String url, 
    @JsonProperty(JSON_PROPERTY_WORK_UNIT_ID) String workUnitId
  ) {
    this();
    this.canceledOn = canceledOn == null ? JsonNullable.<OffsetDateTime>undefined() : JsonNullable.of(canceledOn);
    this.created = created;
    this.elapsed = elapsed;
    this.eventProcessingFinished = eventProcessingFinished;
    this.executionNode = executionNode;
    this.failed = failed;
    this.finished = finished == null ? JsonNullable.<OffsetDateTime>undefined() : JsonNullable.of(finished);
    this.hostStatusCounts = hostStatusCounts == null ? JsonNullable.<Object>undefined() : JsonNullable.of(hostStatusCounts);
    this.id = id;
    this.jobArgs = jobArgs;
    this.jobCwd = jobCwd;
    this.jobEnv = jobEnv;
    this.jobExplanation = jobExplanation;
    this.launchType = launchType;
    this.launchedBy = launchedBy;
    this.modified = modified;
    this.playbookCounts = playbookCounts;
    this.project = project;
    this.related = related;
    this.resultTraceback = resultTraceback;
    this.scmRevision = scmRevision;
    this.started = started == null ? JsonNullable.<OffsetDateTime>undefined() : JsonNullable.of(started);
    this.status = status;
    this.summaryFields = summaryFields;
    this.type = type;
    this.unifiedJobTemplate = unifiedJobTemplate;
    this.url = url;
    this.workUnitId = workUnitId == null ? JsonNullable.<String>undefined() : JsonNullable.of(workUnitId);
  }

  /**
   * The date and time when the cancel request was sent.
   * @return canceledOn
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getCanceledOn() {
    
    if (canceledOn == null) {
      canceledOn = JsonNullable.<OffsetDateTime>undefined();
    }
    return canceledOn.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CANCELED_ON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getCanceledOn_JsonNullable() {
    return canceledOn;
  }
  
  @JsonProperty(JSON_PROPERTY_CANCELED_ON)
  private void setCanceledOn_JsonNullable(JsonNullable<OffsetDateTime> canceledOn) {
    this.canceledOn = canceledOn;
  }


  /**
   * Get created
   * @return created
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }



  public ProjectUpdateDetail credential(@jakarta.annotation.Nullable Integer credential) {
    this.credential = JsonNullable.<Integer>of(credential);
    
    return this;
  }

  /**
   * Get credential
   * @return credential
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getCredential() {
        return credential.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CREDENTIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getCredential_JsonNullable() {
    return credential;
  }
  
  @JsonProperty(JSON_PROPERTY_CREDENTIAL)
  public void setCredential_JsonNullable(JsonNullable<Integer> credential) {
    this.credential = credential;
  }

  public void setCredential(@jakarta.annotation.Nullable Integer credential) {
    this.credential = JsonNullable.<Integer>of(credential);
  }

  public ProjectUpdateDetail description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }

  /**
   * Elapsed time in seconds that the job ran.
   * @return elapsed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ELAPSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getElapsed() {
    return elapsed;
  }



  /**
   * Indicates whether all of the events generated by this unified job have been saved to the database.
   * @return eventProcessingFinished
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_PROCESSING_FINISHED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEventProcessingFinished() {
    return eventProcessingFinished;
  }



  public ProjectUpdateDetail executionEnvironment(@jakarta.annotation.Nullable Integer executionEnvironment) {
    this.executionEnvironment = JsonNullable.<Integer>of(executionEnvironment);
    
    return this;
  }

  /**
   * The container image to be used for execution.
   * @return executionEnvironment
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getExecutionEnvironment() {
        return executionEnvironment.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXECUTION_ENVIRONMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getExecutionEnvironment_JsonNullable() {
    return executionEnvironment;
  }
  
  @JsonProperty(JSON_PROPERTY_EXECUTION_ENVIRONMENT)
  public void setExecutionEnvironment_JsonNullable(JsonNullable<Integer> executionEnvironment) {
    this.executionEnvironment = executionEnvironment;
  }

  public void setExecutionEnvironment(@jakarta.annotation.Nullable Integer executionEnvironment) {
    this.executionEnvironment = JsonNullable.<Integer>of(executionEnvironment);
  }

  /**
   * The node the job executed on.
   * @return executionNode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXECUTION_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExecutionNode() {
    return executionNode;
  }



  /**
   * Get failed
   * @return failed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FAILED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFailed() {
    return failed;
  }



  /**
   * The date and time the job finished execution.
   * @return finished
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getFinished() {
    
    if (finished == null) {
      finished = JsonNullable.<OffsetDateTime>undefined();
    }
    return finished.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FINISHED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getFinished_JsonNullable() {
    return finished;
  }
  
  @JsonProperty(JSON_PROPERTY_FINISHED)
  private void setFinished_JsonNullable(JsonNullable<OffsetDateTime> finished) {
    this.finished = finished;
  }


  /**
   * Playbook stats from the Ansible playbook_on_stats event.
   * @return hostStatusCounts
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Object getHostStatusCounts() {
    
    if (hostStatusCounts == null) {
      hostStatusCounts = JsonNullable.<Object>undefined();
    }
    return hostStatusCounts.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_HOST_STATUS_COUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getHostStatusCounts_JsonNullable() {
    return hostStatusCounts;
  }
  
  @JsonProperty(JSON_PROPERTY_HOST_STATUS_COUNTS)
  private void setHostStatusCounts_JsonNullable(JsonNullable<Object> hostStatusCounts) {
    this.hostStatusCounts = hostStatusCounts;
  }


  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  /**
   * Get jobArgs
   * @return jobArgs
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOB_ARGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJobArgs() {
    return jobArgs;
  }



  /**
   * Get jobCwd
   * @return jobCwd
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOB_CWD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJobCwd() {
    return jobCwd;
  }



  /**
   * Get jobEnv
   * @return jobEnv
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOB_ENV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getJobEnv() {
    return jobEnv;
  }



  /**
   * A status field to indicate the state of the job if it wasn&#39;t able to run and capture stdout
   * @return jobExplanation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOB_EXPLANATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJobExplanation() {
    return jobExplanation;
  }



  public ProjectUpdateDetail jobTags(@jakarta.annotation.Nullable String jobTags) {
    this.jobTags = JsonNullable.<String>of(jobTags);
    
    return this;
  }

  /**
   * Parts of the project update playbook that will be run.
   * @return jobTags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getJobTags() {
        return jobTags.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_JOB_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getJobTags_JsonNullable() {
    return jobTags;
  }
  
  @JsonProperty(JSON_PROPERTY_JOB_TAGS)
  public void setJobTags_JsonNullable(JsonNullable<String> jobTags) {
    this.jobTags = jobTags;
  }

  public void setJobTags(@jakarta.annotation.Nullable String jobTags) {
    this.jobTags = JsonNullable.<String>of(jobTags);
  }

  public ProjectUpdateDetail jobType(@jakarta.annotation.Nullable JobTypeEnum jobType) {
    this.jobType = JsonNullable.<JobTypeEnum>of(jobType);
    
    return this;
  }

  /**
   * Get jobType
   * @return jobType
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public JobTypeEnum getJobType() {
        return jobType.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_JOB_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<JobTypeEnum> getJobType_JsonNullable() {
    return jobType;
  }
  
  @JsonProperty(JSON_PROPERTY_JOB_TYPE)
  public void setJobType_JsonNullable(JsonNullable<JobTypeEnum> jobType) {
    this.jobType = jobType;
  }

  public void setJobType(@jakarta.annotation.Nullable JobTypeEnum jobType) {
    this.jobType = JsonNullable.<JobTypeEnum>of(jobType);
  }

  /**
   * Get launchType
   * @return launchType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAUNCH_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LaunchTypeEnum getLaunchType() {
    return launchType;
  }



  /**
   * Get launchedBy
   * @return launchedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAUNCHED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLaunchedBy() {
    return launchedBy;
  }



  public ProjectUpdateDetail localPath(@jakarta.annotation.Nullable String localPath) {
    this.localPath = JsonNullable.<String>of(localPath);
    
    return this;
  }

  /**
   * Local path (relative to PROJECTS_ROOT) containing playbooks and related files for this project.
   * @return localPath
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getLocalPath() {
        return localPath.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LOCAL_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLocalPath_JsonNullable() {
    return localPath;
  }
  
  @JsonProperty(JSON_PROPERTY_LOCAL_PATH)
  public void setLocalPath_JsonNullable(JsonNullable<String> localPath) {
    this.localPath = localPath;
  }

  public void setLocalPath(@jakarta.annotation.Nullable String localPath) {
    this.localPath = JsonNullable.<String>of(localPath);
  }

  /**
   * Get modified
   * @return modified
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModified() {
    return modified;
  }



  public ProjectUpdateDetail name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  /**
   * A count of all plays and tasks for the job run.
   * @return playbookCounts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PLAYBOOK_COUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPlaybookCounts() {
    return playbookCounts;
  }



  /**
   * Get project
   * @return project
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProject() {
    return project;
  }



  /**
   * Get related
   * @return related
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelated() {
    return related;
  }



  /**
   * Get resultTraceback
   * @return resultTraceback
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULT_TRACEBACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResultTraceback() {
    return resultTraceback;
  }



  public ProjectUpdateDetail scmBranch(@jakarta.annotation.Nullable String scmBranch) {
    this.scmBranch = JsonNullable.<String>of(scmBranch);
    
    return this;
  }

  /**
   * Specific branch, tag or commit to checkout.
   * @return scmBranch
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getScmBranch() {
        return scmBranch.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SCM_BRANCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getScmBranch_JsonNullable() {
    return scmBranch;
  }
  
  @JsonProperty(JSON_PROPERTY_SCM_BRANCH)
  public void setScmBranch_JsonNullable(JsonNullable<String> scmBranch) {
    this.scmBranch = scmBranch;
  }

  public void setScmBranch(@jakarta.annotation.Nullable String scmBranch) {
    this.scmBranch = JsonNullable.<String>of(scmBranch);
  }

  public ProjectUpdateDetail scmClean(@jakarta.annotation.Nullable Boolean scmClean) {
    this.scmClean = JsonNullable.<Boolean>of(scmClean);
    
    return this;
  }

  /**
   * Discard any local changes before syncing the project.
   * @return scmClean
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getScmClean() {
        return scmClean.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SCM_CLEAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getScmClean_JsonNullable() {
    return scmClean;
  }
  
  @JsonProperty(JSON_PROPERTY_SCM_CLEAN)
  public void setScmClean_JsonNullable(JsonNullable<Boolean> scmClean) {
    this.scmClean = scmClean;
  }

  public void setScmClean(@jakarta.annotation.Nullable Boolean scmClean) {
    this.scmClean = JsonNullable.<Boolean>of(scmClean);
  }

  public ProjectUpdateDetail scmDeleteOnUpdate(@jakarta.annotation.Nullable Boolean scmDeleteOnUpdate) {
    this.scmDeleteOnUpdate = JsonNullable.<Boolean>of(scmDeleteOnUpdate);
    
    return this;
  }

  /**
   * Delete the project before syncing.
   * @return scmDeleteOnUpdate
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getScmDeleteOnUpdate() {
        return scmDeleteOnUpdate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SCM_DELETE_ON_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getScmDeleteOnUpdate_JsonNullable() {
    return scmDeleteOnUpdate;
  }
  
  @JsonProperty(JSON_PROPERTY_SCM_DELETE_ON_UPDATE)
  public void setScmDeleteOnUpdate_JsonNullable(JsonNullable<Boolean> scmDeleteOnUpdate) {
    this.scmDeleteOnUpdate = scmDeleteOnUpdate;
  }

  public void setScmDeleteOnUpdate(@jakarta.annotation.Nullable Boolean scmDeleteOnUpdate) {
    this.scmDeleteOnUpdate = JsonNullable.<Boolean>of(scmDeleteOnUpdate);
  }

  public ProjectUpdateDetail scmRefspec(@jakarta.annotation.Nullable String scmRefspec) {
    this.scmRefspec = JsonNullable.<String>of(scmRefspec);
    
    return this;
  }

  /**
   * For git projects, an additional refspec to fetch.
   * @return scmRefspec
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getScmRefspec() {
        return scmRefspec.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SCM_REFSPEC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getScmRefspec_JsonNullable() {
    return scmRefspec;
  }
  
  @JsonProperty(JSON_PROPERTY_SCM_REFSPEC)
  public void setScmRefspec_JsonNullable(JsonNullable<String> scmRefspec) {
    this.scmRefspec = scmRefspec;
  }

  public void setScmRefspec(@jakarta.annotation.Nullable String scmRefspec) {
    this.scmRefspec = JsonNullable.<String>of(scmRefspec);
  }

  /**
   * The SCM Revision discovered by this update for the given project and branch.
   * @return scmRevision
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCM_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScmRevision() {
    return scmRevision;
  }



  public ProjectUpdateDetail scmTrackSubmodules(@jakarta.annotation.Nullable Boolean scmTrackSubmodules) {
    this.scmTrackSubmodules = JsonNullable.<Boolean>of(scmTrackSubmodules);
    
    return this;
  }

  /**
   * Track submodules latest commits on defined branch.
   * @return scmTrackSubmodules
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getScmTrackSubmodules() {
        return scmTrackSubmodules.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SCM_TRACK_SUBMODULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getScmTrackSubmodules_JsonNullable() {
    return scmTrackSubmodules;
  }
  
  @JsonProperty(JSON_PROPERTY_SCM_TRACK_SUBMODULES)
  public void setScmTrackSubmodules_JsonNullable(JsonNullable<Boolean> scmTrackSubmodules) {
    this.scmTrackSubmodules = scmTrackSubmodules;
  }

  public void setScmTrackSubmodules(@jakarta.annotation.Nullable Boolean scmTrackSubmodules) {
    this.scmTrackSubmodules = JsonNullable.<Boolean>of(scmTrackSubmodules);
  }

  public ProjectUpdateDetail scmType(@jakarta.annotation.Nullable ScmTypeEnum scmType) {
    this.scmType = JsonNullable.<ScmTypeEnum>of(scmType);
    
    return this;
  }

  /**
   * Specifies the source control system used to store the project.
   * @return scmType
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public ScmTypeEnum getScmType() {
        return scmType.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SCM_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<ScmTypeEnum> getScmType_JsonNullable() {
    return scmType;
  }
  
  @JsonProperty(JSON_PROPERTY_SCM_TYPE)
  public void setScmType_JsonNullable(JsonNullable<ScmTypeEnum> scmType) {
    this.scmType = scmType;
  }

  public void setScmType(@jakarta.annotation.Nullable ScmTypeEnum scmType) {
    this.scmType = JsonNullable.<ScmTypeEnum>of(scmType);
  }

  public ProjectUpdateDetail scmUrl(@jakarta.annotation.Nullable String scmUrl) {
    this.scmUrl = JsonNullable.<String>of(scmUrl);
    
    return this;
  }

  /**
   * The location where the project is stored.
   * @return scmUrl
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getScmUrl() {
        return scmUrl.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SCM_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getScmUrl_JsonNullable() {
    return scmUrl;
  }
  
  @JsonProperty(JSON_PROPERTY_SCM_URL)
  public void setScmUrl_JsonNullable(JsonNullable<String> scmUrl) {
    this.scmUrl = scmUrl;
  }

  public void setScmUrl(@jakarta.annotation.Nullable String scmUrl) {
    this.scmUrl = JsonNullable.<String>of(scmUrl);
  }

  /**
   * The date and time the job was queued for starting.
   * @return started
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getStarted() {
    
    if (started == null) {
      started = JsonNullable.<OffsetDateTime>undefined();
    }
    return started.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STARTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getStarted_JsonNullable() {
    return started;
  }
  
  @JsonProperty(JSON_PROPERTY_STARTED)
  private void setStarted_JsonNullable(JsonNullable<OffsetDateTime> started) {
    this.started = started;
  }


  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }



  /**
   * Get summaryFields
   * @return summaryFields
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSummaryFields() {
    return summaryFields;
  }



  public ProjectUpdateDetail timeout(@jakarta.annotation.Nullable Integer timeout) {
    
    this.timeout = timeout;
    return this;
  }

  /**
   * The amount of time (in seconds) to run before the task is canceled.
   * @return timeout
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMEOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTimeout() {
    return timeout;
  }


  @JsonProperty(JSON_PROPERTY_TIMEOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeout(@jakarta.annotation.Nullable Integer timeout) {
    this.timeout = timeout;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }



  /**
   * Get unifiedJobTemplate
   * @return unifiedJobTemplate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNIFIED_JOB_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnifiedJobTemplate() {
    return unifiedJobTemplate;
  }



  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }



  /**
   * The Receptor work unit ID associated with this job.
   * @return workUnitId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getWorkUnitId() {
    
    if (workUnitId == null) {
      workUnitId = JsonNullable.<String>undefined();
    }
    return workUnitId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_WORK_UNIT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getWorkUnitId_JsonNullable() {
    return workUnitId;
  }
  
  @JsonProperty(JSON_PROPERTY_WORK_UNIT_ID)
  private void setWorkUnitId_JsonNullable(JsonNullable<String> workUnitId) {
    this.workUnitId = workUnitId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectUpdateDetail projectUpdateDetail = (ProjectUpdateDetail) o;
    return equalsNullable(this.canceledOn, projectUpdateDetail.canceledOn) &&
        Objects.equals(this.created, projectUpdateDetail.created) &&
        equalsNullable(this.credential, projectUpdateDetail.credential) &&
        equalsNullable(this.description, projectUpdateDetail.description) &&
        Objects.equals(this.elapsed, projectUpdateDetail.elapsed) &&
        Objects.equals(this.eventProcessingFinished, projectUpdateDetail.eventProcessingFinished) &&
        equalsNullable(this.executionEnvironment, projectUpdateDetail.executionEnvironment) &&
        Objects.equals(this.executionNode, projectUpdateDetail.executionNode) &&
        Objects.equals(this.failed, projectUpdateDetail.failed) &&
        equalsNullable(this.finished, projectUpdateDetail.finished) &&
        equalsNullable(this.hostStatusCounts, projectUpdateDetail.hostStatusCounts) &&
        Objects.equals(this.id, projectUpdateDetail.id) &&
        Objects.equals(this.jobArgs, projectUpdateDetail.jobArgs) &&
        Objects.equals(this.jobCwd, projectUpdateDetail.jobCwd) &&
        Objects.equals(this.jobEnv, projectUpdateDetail.jobEnv) &&
        Objects.equals(this.jobExplanation, projectUpdateDetail.jobExplanation) &&
        equalsNullable(this.jobTags, projectUpdateDetail.jobTags) &&
        equalsNullable(this.jobType, projectUpdateDetail.jobType) &&
        Objects.equals(this.launchType, projectUpdateDetail.launchType) &&
        Objects.equals(this.launchedBy, projectUpdateDetail.launchedBy) &&
        equalsNullable(this.localPath, projectUpdateDetail.localPath) &&
        Objects.equals(this.modified, projectUpdateDetail.modified) &&
        Objects.equals(this.name, projectUpdateDetail.name) &&
        Objects.equals(this.playbookCounts, projectUpdateDetail.playbookCounts) &&
        Objects.equals(this.project, projectUpdateDetail.project) &&
        Objects.equals(this.related, projectUpdateDetail.related) &&
        Objects.equals(this.resultTraceback, projectUpdateDetail.resultTraceback) &&
        equalsNullable(this.scmBranch, projectUpdateDetail.scmBranch) &&
        equalsNullable(this.scmClean, projectUpdateDetail.scmClean) &&
        equalsNullable(this.scmDeleteOnUpdate, projectUpdateDetail.scmDeleteOnUpdate) &&
        equalsNullable(this.scmRefspec, projectUpdateDetail.scmRefspec) &&
        Objects.equals(this.scmRevision, projectUpdateDetail.scmRevision) &&
        equalsNullable(this.scmTrackSubmodules, projectUpdateDetail.scmTrackSubmodules) &&
        equalsNullable(this.scmType, projectUpdateDetail.scmType) &&
        equalsNullable(this.scmUrl, projectUpdateDetail.scmUrl) &&
        equalsNullable(this.started, projectUpdateDetail.started) &&
        Objects.equals(this.status, projectUpdateDetail.status) &&
        Objects.equals(this.summaryFields, projectUpdateDetail.summaryFields) &&
        Objects.equals(this.timeout, projectUpdateDetail.timeout) &&
        Objects.equals(this.type, projectUpdateDetail.type) &&
        Objects.equals(this.unifiedJobTemplate, projectUpdateDetail.unifiedJobTemplate) &&
        Objects.equals(this.url, projectUpdateDetail.url) &&
        equalsNullable(this.workUnitId, projectUpdateDetail.workUnitId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(canceledOn), created, hashCodeNullable(credential), hashCodeNullable(description), elapsed, eventProcessingFinished, hashCodeNullable(executionEnvironment), executionNode, failed, hashCodeNullable(finished), hashCodeNullable(hostStatusCounts), id, jobArgs, jobCwd, jobEnv, jobExplanation, hashCodeNullable(jobTags), hashCodeNullable(jobType), launchType, launchedBy, hashCodeNullable(localPath), modified, name, playbookCounts, project, related, resultTraceback, hashCodeNullable(scmBranch), hashCodeNullable(scmClean), hashCodeNullable(scmDeleteOnUpdate), hashCodeNullable(scmRefspec), scmRevision, hashCodeNullable(scmTrackSubmodules), hashCodeNullable(scmType), hashCodeNullable(scmUrl), hashCodeNullable(started), status, summaryFields, timeout, type, unifiedJobTemplate, url, hashCodeNullable(workUnitId));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectUpdateDetail {\n");
    sb.append("    canceledOn: ").append(toIndentedString(canceledOn)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    credential: ").append(toIndentedString(credential)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    elapsed: ").append(toIndentedString(elapsed)).append("\n");
    sb.append("    eventProcessingFinished: ").append(toIndentedString(eventProcessingFinished)).append("\n");
    sb.append("    executionEnvironment: ").append(toIndentedString(executionEnvironment)).append("\n");
    sb.append("    executionNode: ").append(toIndentedString(executionNode)).append("\n");
    sb.append("    failed: ").append(toIndentedString(failed)).append("\n");
    sb.append("    finished: ").append(toIndentedString(finished)).append("\n");
    sb.append("    hostStatusCounts: ").append(toIndentedString(hostStatusCounts)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    jobArgs: ").append(toIndentedString(jobArgs)).append("\n");
    sb.append("    jobCwd: ").append(toIndentedString(jobCwd)).append("\n");
    sb.append("    jobEnv: ").append(toIndentedString(jobEnv)).append("\n");
    sb.append("    jobExplanation: ").append(toIndentedString(jobExplanation)).append("\n");
    sb.append("    jobTags: ").append(toIndentedString(jobTags)).append("\n");
    sb.append("    jobType: ").append(toIndentedString(jobType)).append("\n");
    sb.append("    launchType: ").append(toIndentedString(launchType)).append("\n");
    sb.append("    launchedBy: ").append(toIndentedString(launchedBy)).append("\n");
    sb.append("    localPath: ").append(toIndentedString(localPath)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    playbookCounts: ").append(toIndentedString(playbookCounts)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("    resultTraceback: ").append(toIndentedString(resultTraceback)).append("\n");
    sb.append("    scmBranch: ").append(toIndentedString(scmBranch)).append("\n");
    sb.append("    scmClean: ").append(toIndentedString(scmClean)).append("\n");
    sb.append("    scmDeleteOnUpdate: ").append(toIndentedString(scmDeleteOnUpdate)).append("\n");
    sb.append("    scmRefspec: ").append(toIndentedString(scmRefspec)).append("\n");
    sb.append("    scmRevision: ").append(toIndentedString(scmRevision)).append("\n");
    sb.append("    scmTrackSubmodules: ").append(toIndentedString(scmTrackSubmodules)).append("\n");
    sb.append("    scmType: ").append(toIndentedString(scmType)).append("\n");
    sb.append("    scmUrl: ").append(toIndentedString(scmUrl)).append("\n");
    sb.append("    started: ").append(toIndentedString(started)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    summaryFields: ").append(toIndentedString(summaryFields)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    unifiedJobTemplate: ").append(toIndentedString(unifiedJobTemplate)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    workUnitId: ").append(toIndentedString(workUnitId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ProjectUpdateDetail instance;

    public Builder() {
      this(new ProjectUpdateDetail());
    }

    protected Builder(ProjectUpdateDetail instance) {
      this.instance = instance;
    }

    public ProjectUpdateDetail.Builder canceledOn(OffsetDateTime canceledOn) {
      this.instance.canceledOn = JsonNullable.<OffsetDateTime>of(canceledOn);
      return this;
    }
    public ProjectUpdateDetail.Builder canceledOn(JsonNullable<OffsetDateTime> canceledOn) {
      this.instance.canceledOn = canceledOn;
      return this;
    }
    public ProjectUpdateDetail.Builder created(String created) {
      this.instance.created = created;
      return this;
    }
    public ProjectUpdateDetail.Builder credential(Integer credential) {
      this.instance.credential = JsonNullable.<Integer>of(credential);
      return this;
    }
    public ProjectUpdateDetail.Builder credential(JsonNullable<Integer> credential) {
      this.instance.credential = credential;
      return this;
    }
    public ProjectUpdateDetail.Builder description(String description) {
      this.instance.description = JsonNullable.<String>of(description);
      return this;
    }
    public ProjectUpdateDetail.Builder description(JsonNullable<String> description) {
      this.instance.description = description;
      return this;
    }
    public ProjectUpdateDetail.Builder elapsed(BigDecimal elapsed) {
      this.instance.elapsed = elapsed;
      return this;
    }
    public ProjectUpdateDetail.Builder eventProcessingFinished(Boolean eventProcessingFinished) {
      this.instance.eventProcessingFinished = eventProcessingFinished;
      return this;
    }
    public ProjectUpdateDetail.Builder executionEnvironment(Integer executionEnvironment) {
      this.instance.executionEnvironment = JsonNullable.<Integer>of(executionEnvironment);
      return this;
    }
    public ProjectUpdateDetail.Builder executionEnvironment(JsonNullable<Integer> executionEnvironment) {
      this.instance.executionEnvironment = executionEnvironment;
      return this;
    }
    public ProjectUpdateDetail.Builder executionNode(String executionNode) {
      this.instance.executionNode = executionNode;
      return this;
    }
    public ProjectUpdateDetail.Builder failed(Boolean failed) {
      this.instance.failed = failed;
      return this;
    }
    public ProjectUpdateDetail.Builder finished(OffsetDateTime finished) {
      this.instance.finished = JsonNullable.<OffsetDateTime>of(finished);
      return this;
    }
    public ProjectUpdateDetail.Builder finished(JsonNullable<OffsetDateTime> finished) {
      this.instance.finished = finished;
      return this;
    }
    public ProjectUpdateDetail.Builder hostStatusCounts(Object hostStatusCounts) {
      this.instance.hostStatusCounts = JsonNullable.<Object>of(hostStatusCounts);
      return this;
    }
    public ProjectUpdateDetail.Builder hostStatusCounts(JsonNullable<Object> hostStatusCounts) {
      this.instance.hostStatusCounts = hostStatusCounts;
      return this;
    }
    public ProjectUpdateDetail.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public ProjectUpdateDetail.Builder jobArgs(String jobArgs) {
      this.instance.jobArgs = jobArgs;
      return this;
    }
    public ProjectUpdateDetail.Builder jobCwd(String jobCwd) {
      this.instance.jobCwd = jobCwd;
      return this;
    }
    public ProjectUpdateDetail.Builder jobEnv(Object jobEnv) {
      this.instance.jobEnv = jobEnv;
      return this;
    }
    public ProjectUpdateDetail.Builder jobExplanation(String jobExplanation) {
      this.instance.jobExplanation = jobExplanation;
      return this;
    }
    public ProjectUpdateDetail.Builder jobTags(String jobTags) {
      this.instance.jobTags = JsonNullable.<String>of(jobTags);
      return this;
    }
    public ProjectUpdateDetail.Builder jobTags(JsonNullable<String> jobTags) {
      this.instance.jobTags = jobTags;
      return this;
    }
    public ProjectUpdateDetail.Builder jobType(JobTypeEnum jobType) {
      this.instance.jobType = JsonNullable.<JobTypeEnum>of(jobType);
      return this;
    }
    public ProjectUpdateDetail.Builder jobType(JsonNullable<JobTypeEnum> jobType) {
      this.instance.jobType = jobType;
      return this;
    }
    public ProjectUpdateDetail.Builder launchType(LaunchTypeEnum launchType) {
      this.instance.launchType = launchType;
      return this;
    }
    public ProjectUpdateDetail.Builder launchedBy(String launchedBy) {
      this.instance.launchedBy = launchedBy;
      return this;
    }
    public ProjectUpdateDetail.Builder localPath(String localPath) {
      this.instance.localPath = JsonNullable.<String>of(localPath);
      return this;
    }
    public ProjectUpdateDetail.Builder localPath(JsonNullable<String> localPath) {
      this.instance.localPath = localPath;
      return this;
    }
    public ProjectUpdateDetail.Builder modified(String modified) {
      this.instance.modified = modified;
      return this;
    }
    public ProjectUpdateDetail.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public ProjectUpdateDetail.Builder playbookCounts(String playbookCounts) {
      this.instance.playbookCounts = playbookCounts;
      return this;
    }
    public ProjectUpdateDetail.Builder project(String project) {
      this.instance.project = project;
      return this;
    }
    public ProjectUpdateDetail.Builder related(String related) {
      this.instance.related = related;
      return this;
    }
    public ProjectUpdateDetail.Builder resultTraceback(String resultTraceback) {
      this.instance.resultTraceback = resultTraceback;
      return this;
    }
    public ProjectUpdateDetail.Builder scmBranch(String scmBranch) {
      this.instance.scmBranch = JsonNullable.<String>of(scmBranch);
      return this;
    }
    public ProjectUpdateDetail.Builder scmBranch(JsonNullable<String> scmBranch) {
      this.instance.scmBranch = scmBranch;
      return this;
    }
    public ProjectUpdateDetail.Builder scmClean(Boolean scmClean) {
      this.instance.scmClean = JsonNullable.<Boolean>of(scmClean);
      return this;
    }
    public ProjectUpdateDetail.Builder scmClean(JsonNullable<Boolean> scmClean) {
      this.instance.scmClean = scmClean;
      return this;
    }
    public ProjectUpdateDetail.Builder scmDeleteOnUpdate(Boolean scmDeleteOnUpdate) {
      this.instance.scmDeleteOnUpdate = JsonNullable.<Boolean>of(scmDeleteOnUpdate);
      return this;
    }
    public ProjectUpdateDetail.Builder scmDeleteOnUpdate(JsonNullable<Boolean> scmDeleteOnUpdate) {
      this.instance.scmDeleteOnUpdate = scmDeleteOnUpdate;
      return this;
    }
    public ProjectUpdateDetail.Builder scmRefspec(String scmRefspec) {
      this.instance.scmRefspec = JsonNullable.<String>of(scmRefspec);
      return this;
    }
    public ProjectUpdateDetail.Builder scmRefspec(JsonNullable<String> scmRefspec) {
      this.instance.scmRefspec = scmRefspec;
      return this;
    }
    public ProjectUpdateDetail.Builder scmRevision(String scmRevision) {
      this.instance.scmRevision = scmRevision;
      return this;
    }
    public ProjectUpdateDetail.Builder scmTrackSubmodules(Boolean scmTrackSubmodules) {
      this.instance.scmTrackSubmodules = JsonNullable.<Boolean>of(scmTrackSubmodules);
      return this;
    }
    public ProjectUpdateDetail.Builder scmTrackSubmodules(JsonNullable<Boolean> scmTrackSubmodules) {
      this.instance.scmTrackSubmodules = scmTrackSubmodules;
      return this;
    }
    public ProjectUpdateDetail.Builder scmType(ScmTypeEnum scmType) {
      this.instance.scmType = JsonNullable.<ScmTypeEnum>of(scmType);
      return this;
    }
    public ProjectUpdateDetail.Builder scmType(JsonNullable<ScmTypeEnum> scmType) {
      this.instance.scmType = scmType;
      return this;
    }
    public ProjectUpdateDetail.Builder scmUrl(String scmUrl) {
      this.instance.scmUrl = JsonNullable.<String>of(scmUrl);
      return this;
    }
    public ProjectUpdateDetail.Builder scmUrl(JsonNullable<String> scmUrl) {
      this.instance.scmUrl = scmUrl;
      return this;
    }
    public ProjectUpdateDetail.Builder started(OffsetDateTime started) {
      this.instance.started = JsonNullable.<OffsetDateTime>of(started);
      return this;
    }
    public ProjectUpdateDetail.Builder started(JsonNullable<OffsetDateTime> started) {
      this.instance.started = started;
      return this;
    }
    public ProjectUpdateDetail.Builder status(StatusEnum status) {
      this.instance.status = status;
      return this;
    }
    public ProjectUpdateDetail.Builder summaryFields(String summaryFields) {
      this.instance.summaryFields = summaryFields;
      return this;
    }
    public ProjectUpdateDetail.Builder timeout(Integer timeout) {
      this.instance.timeout = timeout;
      return this;
    }
    public ProjectUpdateDetail.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public ProjectUpdateDetail.Builder unifiedJobTemplate(String unifiedJobTemplate) {
      this.instance.unifiedJobTemplate = unifiedJobTemplate;
      return this;
    }
    public ProjectUpdateDetail.Builder url(String url) {
      this.instance.url = url;
      return this;
    }
    public ProjectUpdateDetail.Builder workUnitId(String workUnitId) {
      this.instance.workUnitId = JsonNullable.<String>of(workUnitId);
      return this;
    }
    public ProjectUpdateDetail.Builder workUnitId(JsonNullable<String> workUnitId) {
      this.instance.workUnitId = workUnitId;
      return this;
    }


    /**
    * returns a built ProjectUpdateDetail instance.
    *
    * The builder is not reusable.
    */
    public ProjectUpdateDetail build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ProjectUpdateDetail.Builder builder() {
    return new ProjectUpdateDetail.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ProjectUpdateDetail.Builder toBuilder() {
    return new ProjectUpdateDetail.Builder()
      .canceledOn(getCanceledOn())
      .created(getCreated())
      .credential(getCredential())
      .description(getDescription())
      .elapsed(getElapsed())
      .eventProcessingFinished(getEventProcessingFinished())
      .executionEnvironment(getExecutionEnvironment())
      .executionNode(getExecutionNode())
      .failed(getFailed())
      .finished(getFinished())
      .hostStatusCounts(getHostStatusCounts())
      .id(getId())
      .jobArgs(getJobArgs())
      .jobCwd(getJobCwd())
      .jobEnv(getJobEnv())
      .jobExplanation(getJobExplanation())
      .jobTags(getJobTags())
      .jobType(getJobType())
      .launchType(getLaunchType())
      .launchedBy(getLaunchedBy())
      .localPath(getLocalPath())
      .modified(getModified())
      .name(getName())
      .playbookCounts(getPlaybookCounts())
      .project(getProject())
      .related(getRelated())
      .resultTraceback(getResultTraceback())
      .scmBranch(getScmBranch())
      .scmClean(getScmClean())
      .scmDeleteOnUpdate(getScmDeleteOnUpdate())
      .scmRefspec(getScmRefspec())
      .scmRevision(getScmRevision())
      .scmTrackSubmodules(getScmTrackSubmodules())
      .scmType(getScmType())
      .scmUrl(getScmUrl())
      .started(getStarted())
      .status(getStatus())
      .summaryFields(getSummaryFields())
      .timeout(getTimeout())
      .type(getType())
      .unifiedJobTemplate(getUnifiedJobTemplate())
      .url(getUrl())
      .workUnitId(getWorkUnitId());
  }


}

