/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Resource
 */
@JsonPropertyOrder({
  Resource.JSON_PROPERTY_ADDITIONAL_DATA,
  Resource.JSON_PROPERTY_ANSIBLE_ID,
  Resource.JSON_PROPERTY_HAS_SERIALIZER,
  Resource.JSON_PROPERTY_IS_PARTIALLY_MIGRATED,
  Resource.JSON_PROPERTY_NAME,
  Resource.JSON_PROPERTY_OBJECT_ID,
  Resource.JSON_PROPERTY_RESOURCE_DATA,
  Resource.JSON_PROPERTY_RESOURCE_TYPE,
  Resource.JSON_PROPERTY_SERVICE_ID,
  Resource.JSON_PROPERTY_URL
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class Resource implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ADDITIONAL_DATA = "additional_data";
  @jakarta.annotation.Nullable
  private String additionalData;

  public static final String JSON_PROPERTY_ANSIBLE_ID = "ansible_id";
  @jakarta.annotation.Nullable
  private UUID ansibleId;

  public static final String JSON_PROPERTY_HAS_SERIALIZER = "has_serializer";
  @jakarta.annotation.Nullable
  private Boolean hasSerializer;

  public static final String JSON_PROPERTY_IS_PARTIALLY_MIGRATED = "is_partially_migrated";
  @jakarta.annotation.Nullable
  private Boolean isPartiallyMigrated;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_OBJECT_ID = "object_id";
  @jakarta.annotation.Nullable
  private String objectId;

  public static final String JSON_PROPERTY_RESOURCE_DATA = "resource_data";
  @jakarta.annotation.Nonnull
  private Object resourceData;

  public static final String JSON_PROPERTY_RESOURCE_TYPE = "resource_type";
  @jakarta.annotation.Nullable
  private String resourceType;

  public static final String JSON_PROPERTY_SERVICE_ID = "service_id";
  @jakarta.annotation.Nullable
  private UUID serviceId;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public Resource() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public Resource(
    @JsonProperty(JSON_PROPERTY_ADDITIONAL_DATA) String additionalData, 
    @JsonProperty(JSON_PROPERTY_HAS_SERIALIZER) Boolean hasSerializer, 
    @JsonProperty(JSON_PROPERTY_NAME) String name, 
    @JsonProperty(JSON_PROPERTY_OBJECT_ID) String objectId, 
    @JsonProperty(JSON_PROPERTY_URL) String url
  ) {
    this();
    this.additionalData = additionalData;
    this.hasSerializer = hasSerializer;
    this.name = name == null ? JsonNullable.<String>undefined() : JsonNullable.of(name);
    this.objectId = objectId;
    this.url = url;
  }

  /**
   * Get additionalData
   * @return additionalData
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdditionalData() {
    return additionalData;
  }



  public Resource ansibleId(@jakarta.annotation.Nullable UUID ansibleId) {
    
    this.ansibleId = ansibleId;
    return this;
  }

  /**
   * A unique ID identifying this resource by the resource server.
   * @return ansibleId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ANSIBLE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getAnsibleId() {
    return ansibleId;
  }


  @JsonProperty(JSON_PROPERTY_ANSIBLE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnsibleId(@jakarta.annotation.Nullable UUID ansibleId) {
    this.ansibleId = ansibleId;
  }

  /**
   * Get hasSerializer
   * @return hasSerializer
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HAS_SERIALIZER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasSerializer() {
    return hasSerializer;
  }



  public Resource isPartiallyMigrated(@jakarta.annotation.Nullable Boolean isPartiallyMigrated) {
    
    this.isPartiallyMigrated = isPartiallyMigrated;
    return this;
  }

  /**
   * A flag indicating that the resource has been copied into the resource server, but the service_id hasn&#39;t been updated yet.
   * @return isPartiallyMigrated
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_PARTIALLY_MIGRATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsPartiallyMigrated() {
    return isPartiallyMigrated;
  }


  @JsonProperty(JSON_PROPERTY_IS_PARTIALLY_MIGRATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsPartiallyMigrated(@jakarta.annotation.Nullable Boolean isPartiallyMigrated) {
    this.isPartiallyMigrated = isPartiallyMigrated;
  }

  /**
   * The name of this resource.
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getName() {
    
    if (name == null) {
      name = JsonNullable.<String>undefined();
    }
    return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  private void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }


  /**
   * The object id for this resource.
   * @return objectId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OBJECT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getObjectId() {
    return objectId;
  }



  public Resource resourceData(@jakarta.annotation.Nonnull Object resourceData) {
    
    this.resourceData = resourceData;
    return this;
  }

  /**
   * Get resourceData
   * @return resourceData
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESOURCE_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getResourceData() {
    return resourceData;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCE_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResourceData(@jakarta.annotation.Nonnull Object resourceData) {
    this.resourceData = resourceData;
  }

  public Resource resourceType(@jakarta.annotation.Nullable String resourceType) {
    
    this.resourceType = resourceType;
    return this;
  }

  /**
   * Get resourceType
   * @return resourceType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResourceType() {
    return resourceType;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResourceType(@jakarta.annotation.Nullable String resourceType) {
    this.resourceType = resourceType;
  }

  public Resource serviceId(@jakarta.annotation.Nullable UUID serviceId) {
    
    this.serviceId = serviceId;
    return this;
  }

  /**
   * ID of the service responsible for managing this resource.
   * @return serviceId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVICE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getServiceId() {
    return serviceId;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceId(@jakarta.annotation.Nullable UUID serviceId) {
    this.serviceId = serviceId;
  }

  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Resource resource = (Resource) o;
    return Objects.equals(this.additionalData, resource.additionalData) &&
        Objects.equals(this.ansibleId, resource.ansibleId) &&
        Objects.equals(this.hasSerializer, resource.hasSerializer) &&
        Objects.equals(this.isPartiallyMigrated, resource.isPartiallyMigrated) &&
        equalsNullable(this.name, resource.name) &&
        Objects.equals(this.objectId, resource.objectId) &&
        Objects.equals(this.resourceData, resource.resourceData) &&
        Objects.equals(this.resourceType, resource.resourceType) &&
        Objects.equals(this.serviceId, resource.serviceId) &&
        Objects.equals(this.url, resource.url);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalData, ansibleId, hasSerializer, isPartiallyMigrated, hashCodeNullable(name), objectId, resourceData, resourceType, serviceId, url);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Resource {\n");
    sb.append("    additionalData: ").append(toIndentedString(additionalData)).append("\n");
    sb.append("    ansibleId: ").append(toIndentedString(ansibleId)).append("\n");
    sb.append("    hasSerializer: ").append(toIndentedString(hasSerializer)).append("\n");
    sb.append("    isPartiallyMigrated: ").append(toIndentedString(isPartiallyMigrated)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n");
    sb.append("    resourceData: ").append(toIndentedString(resourceData)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private Resource instance;

    public Builder() {
      this(new Resource());
    }

    protected Builder(Resource instance) {
      this.instance = instance;
    }

    public Resource.Builder additionalData(String additionalData) {
      this.instance.additionalData = additionalData;
      return this;
    }
    public Resource.Builder ansibleId(UUID ansibleId) {
      this.instance.ansibleId = ansibleId;
      return this;
    }
    public Resource.Builder hasSerializer(Boolean hasSerializer) {
      this.instance.hasSerializer = hasSerializer;
      return this;
    }
    public Resource.Builder isPartiallyMigrated(Boolean isPartiallyMigrated) {
      this.instance.isPartiallyMigrated = isPartiallyMigrated;
      return this;
    }
    public Resource.Builder name(String name) {
      this.instance.name = JsonNullable.<String>of(name);
      return this;
    }
    public Resource.Builder name(JsonNullable<String> name) {
      this.instance.name = name;
      return this;
    }
    public Resource.Builder objectId(String objectId) {
      this.instance.objectId = objectId;
      return this;
    }
    public Resource.Builder resourceData(Object resourceData) {
      this.instance.resourceData = resourceData;
      return this;
    }
    public Resource.Builder resourceType(String resourceType) {
      this.instance.resourceType = resourceType;
      return this;
    }
    public Resource.Builder serviceId(UUID serviceId) {
      this.instance.serviceId = serviceId;
      return this;
    }
    public Resource.Builder url(String url) {
      this.instance.url = url;
      return this;
    }


    /**
    * returns a built Resource instance.
    *
    * The builder is not reusable.
    */
    public Resource build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static Resource.Builder builder() {
    return new Resource.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public Resource.Builder toBuilder() {
    return new Resource.Builder()
      .additionalData(getAdditionalData())
      .ansibleId(getAnsibleId())
      .hasSerializer(getHasSerializer())
      .isPartiallyMigrated(getIsPartiallyMigrated())
      .name(getName())
      .objectId(getObjectId())
      .resourceData(getResourceData())
      .resourceType(getResourceType())
      .serviceId(getServiceId())
      .url(getUrl());
  }


}

