/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SettingCategory
 */
@JsonPropertyOrder({
  SettingCategory.JSON_PROPERTY_NAME,
  SettingCategory.JSON_PROPERTY_SLUG,
  SettingCategory.JSON_PROPERTY_URL
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SettingCategory implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_SLUG = "slug";
  @jakarta.annotation.Nullable
  private String slug;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public SettingCategory() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public SettingCategory(
    @JsonProperty(JSON_PROPERTY_NAME) String name, 
    @JsonProperty(JSON_PROPERTY_SLUG) String slug, 
    @JsonProperty(JSON_PROPERTY_URL) String url
  ) {
    this();
    this.name = name;
    this.slug = slug;
    this.url = url;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }



  /**
   * Get slug
   * @return slug
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SLUG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSlug() {
    return slug;
  }



  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SettingCategory settingCategory = (SettingCategory) o;
    return Objects.equals(this.name, settingCategory.name) &&
        Objects.equals(this.slug, settingCategory.slug) &&
        Objects.equals(this.url, settingCategory.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, slug, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SettingCategory {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private SettingCategory instance;

    public Builder() {
      this(new SettingCategory());
    }

    protected Builder(SettingCategory instance) {
      this.instance = instance;
    }

    public SettingCategory.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public SettingCategory.Builder slug(String slug) {
      this.instance.slug = slug;
      return this;
    }
    public SettingCategory.Builder url(String url) {
      this.instance.url = url;
      return this;
    }


    /**
    * returns a built SettingCategory instance.
    *
    * The builder is not reusable.
    */
    public SettingCategory build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SettingCategory.Builder builder() {
    return new SettingCategory.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SettingCategory.Builder toBuilder() {
    return new SettingCategory.Builder()
      .name(getName())
      .slug(getSlug())
      .url(getUrl());
  }


}

