/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UnifiedJobList
 */
@JsonPropertyOrder({
  UnifiedJobList.JSON_PROPERTY_CANCELED_ON,
  UnifiedJobList.JSON_PROPERTY_CONTROLLER_NODE,
  UnifiedJobList.JSON_PROPERTY_CREATED,
  UnifiedJobList.JSON_PROPERTY_DESCRIPTION,
  UnifiedJobList.JSON_PROPERTY_ELAPSED,
  UnifiedJobList.JSON_PROPERTY_EXECUTION_ENVIRONMENT,
  UnifiedJobList.JSON_PROPERTY_EXECUTION_NODE,
  UnifiedJobList.JSON_PROPERTY_FAILED,
  UnifiedJobList.JSON_PROPERTY_FINISHED,
  UnifiedJobList.JSON_PROPERTY_ID,
  UnifiedJobList.JSON_PROPERTY_JOB_EXPLANATION,
  UnifiedJobList.JSON_PROPERTY_LAUNCH_TYPE,
  UnifiedJobList.JSON_PROPERTY_LAUNCHED_BY,
  UnifiedJobList.JSON_PROPERTY_MODIFIED,
  UnifiedJobList.JSON_PROPERTY_NAME,
  UnifiedJobList.JSON_PROPERTY_RELATED,
  UnifiedJobList.JSON_PROPERTY_STARTED,
  UnifiedJobList.JSON_PROPERTY_STATUS,
  UnifiedJobList.JSON_PROPERTY_SUMMARY_FIELDS,
  UnifiedJobList.JSON_PROPERTY_TYPE,
  UnifiedJobList.JSON_PROPERTY_UNIFIED_JOB_TEMPLATE,
  UnifiedJobList.JSON_PROPERTY_URL,
  UnifiedJobList.JSON_PROPERTY_WORK_UNIT_ID
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class UnifiedJobList implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CANCELED_ON = "canceled_on";
  @jakarta.annotation.Nullable
  private JsonNullable<OffsetDateTime> canceledOn = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_CONTROLLER_NODE = "controller_node";
  @jakarta.annotation.Nullable
  private String controllerNode;

  public static final String JSON_PROPERTY_CREATED = "created";
  @jakarta.annotation.Nullable
  private String created;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private JsonNullable<String> description = JsonNullable.<String>of("");

  public static final String JSON_PROPERTY_ELAPSED = "elapsed";
  @jakarta.annotation.Nullable
  private BigDecimal elapsed;

  public static final String JSON_PROPERTY_EXECUTION_ENVIRONMENT = "execution_environment";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> executionEnvironment = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_EXECUTION_NODE = "execution_node";
  @jakarta.annotation.Nullable
  private String executionNode;

  public static final String JSON_PROPERTY_FAILED = "failed";
  @jakarta.annotation.Nullable
  private Boolean failed;

  public static final String JSON_PROPERTY_FINISHED = "finished";
  @jakarta.annotation.Nullable
  private JsonNullable<OffsetDateTime> finished = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_JOB_EXPLANATION = "job_explanation";
  @jakarta.annotation.Nullable
  private String jobExplanation;

  /**
   * Gets or Sets launchType
   */
  public enum LaunchTypeEnum {
    MANUAL(String.valueOf("manual")),
    
    RELAUNCH(String.valueOf("relaunch")),
    
    CALLBACK(String.valueOf("callback")),
    
    SCHEDULED(String.valueOf("scheduled")),
    
    DEPENDENCY(String.valueOf("dependency")),
    
    WORKFLOW(String.valueOf("workflow")),
    
    WEBHOOK(String.valueOf("webhook")),
    
    SYNC(String.valueOf("sync")),
    
    SCM(String.valueOf("scm"));

    private String value;

    LaunchTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LaunchTypeEnum fromValue(String value) {
      for (LaunchTypeEnum b : LaunchTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LAUNCH_TYPE = "launch_type";
  @jakarta.annotation.Nullable
  private LaunchTypeEnum launchType;

  public static final String JSON_PROPERTY_LAUNCHED_BY = "launched_by";
  @jakarta.annotation.Nullable
  private String launchedBy;

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  @jakarta.annotation.Nullable
  private String modified;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_RELATED = "related";
  @jakarta.annotation.Nullable
  private String related;

  public static final String JSON_PROPERTY_STARTED = "started";
  @jakarta.annotation.Nullable
  private JsonNullable<OffsetDateTime> started = JsonNullable.<OffsetDateTime>undefined();

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    NEW(String.valueOf("new")),
    
    PENDING(String.valueOf("pending")),
    
    WAITING(String.valueOf("waiting")),
    
    RUNNING(String.valueOf("running")),
    
    SUCCESSFUL(String.valueOf("successful")),
    
    FAILED(String.valueOf("failed")),
    
    ERROR(String.valueOf("error")),
    
    CANCELED(String.valueOf("canceled"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_SUMMARY_FIELDS = "summary_fields";
  @jakarta.annotation.Nullable
  private String summaryFields;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_UNIFIED_JOB_TEMPLATE = "unified_job_template";
  @jakarta.annotation.Nullable
  private String unifiedJobTemplate;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_WORK_UNIT_ID = "work_unit_id";
  @jakarta.annotation.Nullable
  private JsonNullable<String> workUnitId = JsonNullable.<String>undefined();

  public UnifiedJobList() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public UnifiedJobList(
    @JsonProperty(JSON_PROPERTY_CANCELED_ON) OffsetDateTime canceledOn, 
    @JsonProperty(JSON_PROPERTY_CONTROLLER_NODE) String controllerNode, 
    @JsonProperty(JSON_PROPERTY_CREATED) String created, 
    @JsonProperty(JSON_PROPERTY_ELAPSED) BigDecimal elapsed, 
    @JsonProperty(JSON_PROPERTY_EXECUTION_NODE) String executionNode, 
    @JsonProperty(JSON_PROPERTY_FAILED) Boolean failed, 
    @JsonProperty(JSON_PROPERTY_FINISHED) OffsetDateTime finished, 
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_JOB_EXPLANATION) String jobExplanation, 
    @JsonProperty(JSON_PROPERTY_LAUNCH_TYPE) LaunchTypeEnum launchType, 
    @JsonProperty(JSON_PROPERTY_LAUNCHED_BY) String launchedBy, 
    @JsonProperty(JSON_PROPERTY_MODIFIED) String modified, 
    @JsonProperty(JSON_PROPERTY_RELATED) String related, 
    @JsonProperty(JSON_PROPERTY_STARTED) OffsetDateTime started, 
    @JsonProperty(JSON_PROPERTY_STATUS) StatusEnum status, 
    @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS) String summaryFields, 
    @JsonProperty(JSON_PROPERTY_TYPE) String type, 
    @JsonProperty(JSON_PROPERTY_UNIFIED_JOB_TEMPLATE) String unifiedJobTemplate, 
    @JsonProperty(JSON_PROPERTY_URL) String url, 
    @JsonProperty(JSON_PROPERTY_WORK_UNIT_ID) String workUnitId
  ) {
    this();
    this.canceledOn = canceledOn == null ? JsonNullable.<OffsetDateTime>undefined() : JsonNullable.of(canceledOn);
    this.controllerNode = controllerNode;
    this.created = created;
    this.elapsed = elapsed;
    this.executionNode = executionNode;
    this.failed = failed;
    this.finished = finished == null ? JsonNullable.<OffsetDateTime>undefined() : JsonNullable.of(finished);
    this.id = id;
    this.jobExplanation = jobExplanation;
    this.launchType = launchType;
    this.launchedBy = launchedBy;
    this.modified = modified;
    this.related = related;
    this.started = started == null ? JsonNullable.<OffsetDateTime>undefined() : JsonNullable.of(started);
    this.status = status;
    this.summaryFields = summaryFields;
    this.type = type;
    this.unifiedJobTemplate = unifiedJobTemplate;
    this.url = url;
    this.workUnitId = workUnitId == null ? JsonNullable.<String>undefined() : JsonNullable.of(workUnitId);
  }

  /**
   * The date and time when the cancel request was sent.
   * @return canceledOn
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getCanceledOn() {
    
    if (canceledOn == null) {
      canceledOn = JsonNullable.<OffsetDateTime>undefined();
    }
    return canceledOn.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CANCELED_ON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getCanceledOn_JsonNullable() {
    return canceledOn;
  }
  
  @JsonProperty(JSON_PROPERTY_CANCELED_ON)
  private void setCanceledOn_JsonNullable(JsonNullable<OffsetDateTime> canceledOn) {
    this.canceledOn = canceledOn;
  }


  /**
   * The instance that managed the execution environment.
   * @return controllerNode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTROLLER_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getControllerNode() {
    return controllerNode;
  }



  /**
   * Get created
   * @return created
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }



  public UnifiedJobList description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }

  /**
   * Elapsed time in seconds that the job ran.
   * @return elapsed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ELAPSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getElapsed() {
    return elapsed;
  }



  public UnifiedJobList executionEnvironment(@jakarta.annotation.Nullable Integer executionEnvironment) {
    this.executionEnvironment = JsonNullable.<Integer>of(executionEnvironment);
    
    return this;
  }

  /**
   * The container image to be used for execution.
   * @return executionEnvironment
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getExecutionEnvironment() {
        return executionEnvironment.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXECUTION_ENVIRONMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getExecutionEnvironment_JsonNullable() {
    return executionEnvironment;
  }
  
  @JsonProperty(JSON_PROPERTY_EXECUTION_ENVIRONMENT)
  public void setExecutionEnvironment_JsonNullable(JsonNullable<Integer> executionEnvironment) {
    this.executionEnvironment = executionEnvironment;
  }

  public void setExecutionEnvironment(@jakarta.annotation.Nullable Integer executionEnvironment) {
    this.executionEnvironment = JsonNullable.<Integer>of(executionEnvironment);
  }

  /**
   * The node the job executed on.
   * @return executionNode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXECUTION_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExecutionNode() {
    return executionNode;
  }



  /**
   * Get failed
   * @return failed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FAILED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFailed() {
    return failed;
  }



  /**
   * The date and time the job finished execution.
   * @return finished
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getFinished() {
    
    if (finished == null) {
      finished = JsonNullable.<OffsetDateTime>undefined();
    }
    return finished.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FINISHED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getFinished_JsonNullable() {
    return finished;
  }
  
  @JsonProperty(JSON_PROPERTY_FINISHED)
  private void setFinished_JsonNullable(JsonNullable<OffsetDateTime> finished) {
    this.finished = finished;
  }


  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  /**
   * A status field to indicate the state of the job if it wasn&#39;t able to run and capture stdout
   * @return jobExplanation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOB_EXPLANATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJobExplanation() {
    return jobExplanation;
  }



  /**
   * Get launchType
   * @return launchType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAUNCH_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LaunchTypeEnum getLaunchType() {
    return launchType;
  }



  /**
   * Get launchedBy
   * @return launchedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAUNCHED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLaunchedBy() {
    return launchedBy;
  }



  /**
   * Get modified
   * @return modified
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModified() {
    return modified;
  }



  public UnifiedJobList name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  /**
   * Get related
   * @return related
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelated() {
    return related;
  }



  /**
   * The date and time the job was queued for starting.
   * @return started
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getStarted() {
    
    if (started == null) {
      started = JsonNullable.<OffsetDateTime>undefined();
    }
    return started.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STARTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getStarted_JsonNullable() {
    return started;
  }
  
  @JsonProperty(JSON_PROPERTY_STARTED)
  private void setStarted_JsonNullable(JsonNullable<OffsetDateTime> started) {
    this.started = started;
  }


  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }



  /**
   * Get summaryFields
   * @return summaryFields
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSummaryFields() {
    return summaryFields;
  }



  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }



  /**
   * Get unifiedJobTemplate
   * @return unifiedJobTemplate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNIFIED_JOB_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnifiedJobTemplate() {
    return unifiedJobTemplate;
  }



  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }



  /**
   * The Receptor work unit ID associated with this job.
   * @return workUnitId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getWorkUnitId() {
    
    if (workUnitId == null) {
      workUnitId = JsonNullable.<String>undefined();
    }
    return workUnitId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_WORK_UNIT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getWorkUnitId_JsonNullable() {
    return workUnitId;
  }
  
  @JsonProperty(JSON_PROPERTY_WORK_UNIT_ID)
  private void setWorkUnitId_JsonNullable(JsonNullable<String> workUnitId) {
    this.workUnitId = workUnitId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnifiedJobList unifiedJobList = (UnifiedJobList) o;
    return equalsNullable(this.canceledOn, unifiedJobList.canceledOn) &&
        Objects.equals(this.controllerNode, unifiedJobList.controllerNode) &&
        Objects.equals(this.created, unifiedJobList.created) &&
        equalsNullable(this.description, unifiedJobList.description) &&
        Objects.equals(this.elapsed, unifiedJobList.elapsed) &&
        equalsNullable(this.executionEnvironment, unifiedJobList.executionEnvironment) &&
        Objects.equals(this.executionNode, unifiedJobList.executionNode) &&
        Objects.equals(this.failed, unifiedJobList.failed) &&
        equalsNullable(this.finished, unifiedJobList.finished) &&
        Objects.equals(this.id, unifiedJobList.id) &&
        Objects.equals(this.jobExplanation, unifiedJobList.jobExplanation) &&
        Objects.equals(this.launchType, unifiedJobList.launchType) &&
        Objects.equals(this.launchedBy, unifiedJobList.launchedBy) &&
        Objects.equals(this.modified, unifiedJobList.modified) &&
        Objects.equals(this.name, unifiedJobList.name) &&
        Objects.equals(this.related, unifiedJobList.related) &&
        equalsNullable(this.started, unifiedJobList.started) &&
        Objects.equals(this.status, unifiedJobList.status) &&
        Objects.equals(this.summaryFields, unifiedJobList.summaryFields) &&
        Objects.equals(this.type, unifiedJobList.type) &&
        Objects.equals(this.unifiedJobTemplate, unifiedJobList.unifiedJobTemplate) &&
        Objects.equals(this.url, unifiedJobList.url) &&
        equalsNullable(this.workUnitId, unifiedJobList.workUnitId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(canceledOn), controllerNode, created, hashCodeNullable(description), elapsed, hashCodeNullable(executionEnvironment), executionNode, failed, hashCodeNullable(finished), id, jobExplanation, launchType, launchedBy, modified, name, related, hashCodeNullable(started), status, summaryFields, type, unifiedJobTemplate, url, hashCodeNullable(workUnitId));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnifiedJobList {\n");
    sb.append("    canceledOn: ").append(toIndentedString(canceledOn)).append("\n");
    sb.append("    controllerNode: ").append(toIndentedString(controllerNode)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    elapsed: ").append(toIndentedString(elapsed)).append("\n");
    sb.append("    executionEnvironment: ").append(toIndentedString(executionEnvironment)).append("\n");
    sb.append("    executionNode: ").append(toIndentedString(executionNode)).append("\n");
    sb.append("    failed: ").append(toIndentedString(failed)).append("\n");
    sb.append("    finished: ").append(toIndentedString(finished)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    jobExplanation: ").append(toIndentedString(jobExplanation)).append("\n");
    sb.append("    launchType: ").append(toIndentedString(launchType)).append("\n");
    sb.append("    launchedBy: ").append(toIndentedString(launchedBy)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("    started: ").append(toIndentedString(started)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    summaryFields: ").append(toIndentedString(summaryFields)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    unifiedJobTemplate: ").append(toIndentedString(unifiedJobTemplate)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    workUnitId: ").append(toIndentedString(workUnitId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private UnifiedJobList instance;

    public Builder() {
      this(new UnifiedJobList());
    }

    protected Builder(UnifiedJobList instance) {
      this.instance = instance;
    }

    public UnifiedJobList.Builder canceledOn(OffsetDateTime canceledOn) {
      this.instance.canceledOn = JsonNullable.<OffsetDateTime>of(canceledOn);
      return this;
    }
    public UnifiedJobList.Builder canceledOn(JsonNullable<OffsetDateTime> canceledOn) {
      this.instance.canceledOn = canceledOn;
      return this;
    }
    public UnifiedJobList.Builder controllerNode(String controllerNode) {
      this.instance.controllerNode = controllerNode;
      return this;
    }
    public UnifiedJobList.Builder created(String created) {
      this.instance.created = created;
      return this;
    }
    public UnifiedJobList.Builder description(String description) {
      this.instance.description = JsonNullable.<String>of(description);
      return this;
    }
    public UnifiedJobList.Builder description(JsonNullable<String> description) {
      this.instance.description = description;
      return this;
    }
    public UnifiedJobList.Builder elapsed(BigDecimal elapsed) {
      this.instance.elapsed = elapsed;
      return this;
    }
    public UnifiedJobList.Builder executionEnvironment(Integer executionEnvironment) {
      this.instance.executionEnvironment = JsonNullable.<Integer>of(executionEnvironment);
      return this;
    }
    public UnifiedJobList.Builder executionEnvironment(JsonNullable<Integer> executionEnvironment) {
      this.instance.executionEnvironment = executionEnvironment;
      return this;
    }
    public UnifiedJobList.Builder executionNode(String executionNode) {
      this.instance.executionNode = executionNode;
      return this;
    }
    public UnifiedJobList.Builder failed(Boolean failed) {
      this.instance.failed = failed;
      return this;
    }
    public UnifiedJobList.Builder finished(OffsetDateTime finished) {
      this.instance.finished = JsonNullable.<OffsetDateTime>of(finished);
      return this;
    }
    public UnifiedJobList.Builder finished(JsonNullable<OffsetDateTime> finished) {
      this.instance.finished = finished;
      return this;
    }
    public UnifiedJobList.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public UnifiedJobList.Builder jobExplanation(String jobExplanation) {
      this.instance.jobExplanation = jobExplanation;
      return this;
    }
    public UnifiedJobList.Builder launchType(LaunchTypeEnum launchType) {
      this.instance.launchType = launchType;
      return this;
    }
    public UnifiedJobList.Builder launchedBy(String launchedBy) {
      this.instance.launchedBy = launchedBy;
      return this;
    }
    public UnifiedJobList.Builder modified(String modified) {
      this.instance.modified = modified;
      return this;
    }
    public UnifiedJobList.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public UnifiedJobList.Builder related(String related) {
      this.instance.related = related;
      return this;
    }
    public UnifiedJobList.Builder started(OffsetDateTime started) {
      this.instance.started = JsonNullable.<OffsetDateTime>of(started);
      return this;
    }
    public UnifiedJobList.Builder started(JsonNullable<OffsetDateTime> started) {
      this.instance.started = started;
      return this;
    }
    public UnifiedJobList.Builder status(StatusEnum status) {
      this.instance.status = status;
      return this;
    }
    public UnifiedJobList.Builder summaryFields(String summaryFields) {
      this.instance.summaryFields = summaryFields;
      return this;
    }
    public UnifiedJobList.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public UnifiedJobList.Builder unifiedJobTemplate(String unifiedJobTemplate) {
      this.instance.unifiedJobTemplate = unifiedJobTemplate;
      return this;
    }
    public UnifiedJobList.Builder url(String url) {
      this.instance.url = url;
      return this;
    }
    public UnifiedJobList.Builder workUnitId(String workUnitId) {
      this.instance.workUnitId = JsonNullable.<String>of(workUnitId);
      return this;
    }
    public UnifiedJobList.Builder workUnitId(JsonNullable<String> workUnitId) {
      this.instance.workUnitId = workUnitId;
      return this;
    }


    /**
    * returns a built UnifiedJobList instance.
    *
    * The builder is not reusable.
    */
    public UnifiedJobList build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static UnifiedJobList.Builder builder() {
    return new UnifiedJobList.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public UnifiedJobList.Builder toBuilder() {
    return new UnifiedJobList.Builder()
      .canceledOn(getCanceledOn())
      .controllerNode(getControllerNode())
      .created(getCreated())
      .description(getDescription())
      .elapsed(getElapsed())
      .executionEnvironment(getExecutionEnvironment())
      .executionNode(getExecutionNode())
      .failed(getFailed())
      .finished(getFinished())
      .id(getId())
      .jobExplanation(getJobExplanation())
      .launchType(getLaunchType())
      .launchedBy(getLaunchedBy())
      .modified(getModified())
      .name(getName())
      .related(getRelated())
      .started(getStarted())
      .status(getStatus())
      .summaryFields(getSummaryFields())
      .type(getType())
      .unifiedJobTemplate(getUnifiedJobTemplate())
      .url(getUrl())
      .workUnitId(getWorkUnitId());
  }


}

