/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.LinkedHashSet;
import java.util.Set;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * WorkflowJobNodeList
 */
@JsonPropertyOrder({
  WorkflowJobNodeList.JSON_PROPERTY_ALL_PARENTS_MUST_CONVERGE,
  WorkflowJobNodeList.JSON_PROPERTY_ALWAYS_NODES,
  WorkflowJobNodeList.JSON_PROPERTY_CREATED,
  WorkflowJobNodeList.JSON_PROPERTY_DIFF_MODE,
  WorkflowJobNodeList.JSON_PROPERTY_DO_NOT_RUN,
  WorkflowJobNodeList.JSON_PROPERTY_EXECUTION_ENVIRONMENT,
  WorkflowJobNodeList.JSON_PROPERTY_EXTRA_DATA,
  WorkflowJobNodeList.JSON_PROPERTY_FAILURE_NODES,
  WorkflowJobNodeList.JSON_PROPERTY_FORKS,
  WorkflowJobNodeList.JSON_PROPERTY_ID,
  WorkflowJobNodeList.JSON_PROPERTY_IDENTIFIER,
  WorkflowJobNodeList.JSON_PROPERTY_INVENTORY,
  WorkflowJobNodeList.JSON_PROPERTY_JOB,
  WorkflowJobNodeList.JSON_PROPERTY_JOB_SLICE_COUNT,
  WorkflowJobNodeList.JSON_PROPERTY_JOB_TAGS,
  WorkflowJobNodeList.JSON_PROPERTY_JOB_TYPE,
  WorkflowJobNodeList.JSON_PROPERTY_LIMIT,
  WorkflowJobNodeList.JSON_PROPERTY_MODIFIED,
  WorkflowJobNodeList.JSON_PROPERTY_RELATED,
  WorkflowJobNodeList.JSON_PROPERTY_SCM_BRANCH,
  WorkflowJobNodeList.JSON_PROPERTY_SKIP_TAGS,
  WorkflowJobNodeList.JSON_PROPERTY_SUCCESS_NODES,
  WorkflowJobNodeList.JSON_PROPERTY_SUMMARY_FIELDS,
  WorkflowJobNodeList.JSON_PROPERTY_TIMEOUT,
  WorkflowJobNodeList.JSON_PROPERTY_TYPE,
  WorkflowJobNodeList.JSON_PROPERTY_UNIFIED_JOB_TEMPLATE,
  WorkflowJobNodeList.JSON_PROPERTY_URL,
  WorkflowJobNodeList.JSON_PROPERTY_VERBOSITY,
  WorkflowJobNodeList.JSON_PROPERTY_WORKFLOW_JOB
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class WorkflowJobNodeList implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ALL_PARENTS_MUST_CONVERGE = "all_parents_must_converge";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> allParentsMustConverge = JsonNullable.<Boolean>of(false);

  public static final String JSON_PROPERTY_ALWAYS_NODES = "always_nodes";
  @jakarta.annotation.Nullable
  private Set<Integer> alwaysNodes = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_CREATED = "created";
  @jakarta.annotation.Nullable
  private String created;

  public static final String JSON_PROPERTY_DIFF_MODE = "diff_mode";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> diffMode = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_DO_NOT_RUN = "do_not_run";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> doNotRun = JsonNullable.<Boolean>of(false);

  public static final String JSON_PROPERTY_EXECUTION_ENVIRONMENT = "execution_environment";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> executionEnvironment = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_EXTRA_DATA = "extra_data";
  @jakarta.annotation.Nullable
  private Object extraData;

  public static final String JSON_PROPERTY_FAILURE_NODES = "failure_nodes";
  @jakarta.annotation.Nullable
  private Set<Integer> failureNodes = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_FORKS = "forks";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> forks = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  @jakarta.annotation.Nullable
  private JsonNullable<String> identifier = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_INVENTORY = "inventory";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> inventory = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_JOB = "job";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> job = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_JOB_SLICE_COUNT = "job_slice_count";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> jobSliceCount = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_JOB_TAGS = "job_tags";
  @jakarta.annotation.Nullable
  private JsonNullable<String> jobTags = JsonNullable.<String>undefined();

  /**
   * Gets or Sets jobType
   */
  public enum JobTypeEnum {
    RUN(String.valueOf("run")),
    
    CHECK(String.valueOf("check"));

    private String value;

    JobTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static JobTypeEnum fromValue(String value) {
      for (JobTypeEnum b : JobTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_JOB_TYPE = "job_type";
  @jakarta.annotation.Nullable
  private JsonNullable<JobTypeEnum> jobType = JsonNullable.<JobTypeEnum>undefined();

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @jakarta.annotation.Nullable
  private JsonNullable<String> limit = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  @jakarta.annotation.Nullable
  private String modified;

  public static final String JSON_PROPERTY_RELATED = "related";
  @jakarta.annotation.Nullable
  private String related;

  public static final String JSON_PROPERTY_SCM_BRANCH = "scm_branch";
  @jakarta.annotation.Nullable
  private JsonNullable<String> scmBranch = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SKIP_TAGS = "skip_tags";
  @jakarta.annotation.Nullable
  private JsonNullable<String> skipTags = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SUCCESS_NODES = "success_nodes";
  @jakarta.annotation.Nullable
  private Set<Integer> successNodes = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_SUMMARY_FIELDS = "summary_fields";
  @jakarta.annotation.Nullable
  private String summaryFields;

  public static final String JSON_PROPERTY_TIMEOUT = "timeout";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> timeout = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_UNIFIED_JOB_TEMPLATE = "unified_job_template";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> unifiedJobTemplate = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  /**
   * Gets or Sets verbosity
   */
  public enum VerbosityEnum {
    _0(String.valueOf("0")),
    
    _1(String.valueOf("1")),
    
    _2(String.valueOf("2")),
    
    _3(String.valueOf("3")),
    
    _4(String.valueOf("4")),
    
    _5(String.valueOf("5"));

    private String value;

    VerbosityEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VerbosityEnum fromValue(String value) {
      for (VerbosityEnum b : VerbosityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_VERBOSITY = "verbosity";
  @jakarta.annotation.Nullable
  private JsonNullable<VerbosityEnum> verbosity = JsonNullable.<VerbosityEnum>undefined();

  public static final String JSON_PROPERTY_WORKFLOW_JOB = "workflow_job";
  @jakarta.annotation.Nullable
  private JsonNullable<String> workflowJob = JsonNullable.<String>undefined();

  public WorkflowJobNodeList() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public WorkflowJobNodeList(
    @JsonProperty(JSON_PROPERTY_ALWAYS_NODES) Set<Integer> alwaysNodes, 
    @JsonProperty(JSON_PROPERTY_CREATED) String created, 
    @JsonProperty(JSON_PROPERTY_FAILURE_NODES) Set<Integer> failureNodes, 
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_MODIFIED) String modified, 
    @JsonProperty(JSON_PROPERTY_RELATED) String related, 
    @JsonProperty(JSON_PROPERTY_SUCCESS_NODES) Set<Integer> successNodes, 
    @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS) String summaryFields, 
    @JsonProperty(JSON_PROPERTY_TYPE) String type, 
    @JsonProperty(JSON_PROPERTY_URL) String url
  ) {
    this();
    this.alwaysNodes = alwaysNodes;
    this.created = created;
    this.failureNodes = failureNodes;
    this.id = id;
    this.modified = modified;
    this.related = related;
    this.successNodes = successNodes;
    this.summaryFields = summaryFields;
    this.type = type;
    this.url = url;
  }

  public WorkflowJobNodeList allParentsMustConverge(@jakarta.annotation.Nullable Boolean allParentsMustConverge) {
    this.allParentsMustConverge = JsonNullable.<Boolean>of(allParentsMustConverge);
    
    return this;
  }

  /**
   * If enabled then the node will only run if all of the parent nodes have met the criteria to reach this node
   * @return allParentsMustConverge
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getAllParentsMustConverge() {
        return allParentsMustConverge.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ALL_PARENTS_MUST_CONVERGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getAllParentsMustConverge_JsonNullable() {
    return allParentsMustConverge;
  }
  
  @JsonProperty(JSON_PROPERTY_ALL_PARENTS_MUST_CONVERGE)
  public void setAllParentsMustConverge_JsonNullable(JsonNullable<Boolean> allParentsMustConverge) {
    this.allParentsMustConverge = allParentsMustConverge;
  }

  public void setAllParentsMustConverge(@jakarta.annotation.Nullable Boolean allParentsMustConverge) {
    this.allParentsMustConverge = JsonNullable.<Boolean>of(allParentsMustConverge);
  }

  /**
   * Get alwaysNodes
   * @return alwaysNodes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALWAYS_NODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<Integer> getAlwaysNodes() {
    return alwaysNodes;
  }



  /**
   * Get created
   * @return created
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }



  public WorkflowJobNodeList diffMode(@jakarta.annotation.Nullable Boolean diffMode) {
    this.diffMode = JsonNullable.<Boolean>of(diffMode);
    
    return this;
  }

  /**
   * Get diffMode
   * @return diffMode
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getDiffMode() {
        return diffMode.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DIFF_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getDiffMode_JsonNullable() {
    return diffMode;
  }
  
  @JsonProperty(JSON_PROPERTY_DIFF_MODE)
  public void setDiffMode_JsonNullable(JsonNullable<Boolean> diffMode) {
    this.diffMode = diffMode;
  }

  public void setDiffMode(@jakarta.annotation.Nullable Boolean diffMode) {
    this.diffMode = JsonNullable.<Boolean>of(diffMode);
  }

  public WorkflowJobNodeList doNotRun(@jakarta.annotation.Nullable Boolean doNotRun) {
    this.doNotRun = JsonNullable.<Boolean>of(doNotRun);
    
    return this;
  }

  /**
   * Indicates that a job will not be created when True. Workflow runtime semantics will mark this True if the node is in a path that will decidedly not be ran. A value of False means the node may not run.
   * @return doNotRun
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getDoNotRun() {
        return doNotRun.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DO_NOT_RUN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getDoNotRun_JsonNullable() {
    return doNotRun;
  }
  
  @JsonProperty(JSON_PROPERTY_DO_NOT_RUN)
  public void setDoNotRun_JsonNullable(JsonNullable<Boolean> doNotRun) {
    this.doNotRun = doNotRun;
  }

  public void setDoNotRun(@jakarta.annotation.Nullable Boolean doNotRun) {
    this.doNotRun = JsonNullable.<Boolean>of(doNotRun);
  }

  public WorkflowJobNodeList executionEnvironment(@jakarta.annotation.Nullable Integer executionEnvironment) {
    this.executionEnvironment = JsonNullable.<Integer>of(executionEnvironment);
    
    return this;
  }

  /**
   * The container image to be used for execution.
   * @return executionEnvironment
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getExecutionEnvironment() {
        return executionEnvironment.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXECUTION_ENVIRONMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getExecutionEnvironment_JsonNullable() {
    return executionEnvironment;
  }
  
  @JsonProperty(JSON_PROPERTY_EXECUTION_ENVIRONMENT)
  public void setExecutionEnvironment_JsonNullable(JsonNullable<Integer> executionEnvironment) {
    this.executionEnvironment = executionEnvironment;
  }

  public void setExecutionEnvironment(@jakarta.annotation.Nullable Integer executionEnvironment) {
    this.executionEnvironment = JsonNullable.<Integer>of(executionEnvironment);
  }

  public WorkflowJobNodeList extraData(@jakarta.annotation.Nullable Object extraData) {
    
    this.extraData = extraData;
    return this;
  }

  /**
   * Get extraData
   * @return extraData
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTRA_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getExtraData() {
    return extraData;
  }


  @JsonProperty(JSON_PROPERTY_EXTRA_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtraData(@jakarta.annotation.Nullable Object extraData) {
    this.extraData = extraData;
  }

  /**
   * Get failureNodes
   * @return failureNodes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FAILURE_NODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<Integer> getFailureNodes() {
    return failureNodes;
  }



  public WorkflowJobNodeList forks(@jakarta.annotation.Nullable Integer forks) {
    this.forks = JsonNullable.<Integer>of(forks);
    
    return this;
  }

  /**
   * Get forks
   * minimum: 0
   * @return forks
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getForks() {
        return forks.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FORKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getForks_JsonNullable() {
    return forks;
  }
  
  @JsonProperty(JSON_PROPERTY_FORKS)
  public void setForks_JsonNullable(JsonNullable<Integer> forks) {
    this.forks = forks;
  }

  public void setForks(@jakarta.annotation.Nullable Integer forks) {
    this.forks = JsonNullable.<Integer>of(forks);
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  public WorkflowJobNodeList identifier(@jakarta.annotation.Nullable String identifier) {
    this.identifier = JsonNullable.<String>of(identifier);
    
    return this;
  }

  /**
   * An identifier coresponding to the workflow job template node that this node was created from.
   * @return identifier
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getIdentifier() {
        return identifier.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getIdentifier_JsonNullable() {
    return identifier;
  }
  
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  public void setIdentifier_JsonNullable(JsonNullable<String> identifier) {
    this.identifier = identifier;
  }

  public void setIdentifier(@jakarta.annotation.Nullable String identifier) {
    this.identifier = JsonNullable.<String>of(identifier);
  }

  public WorkflowJobNodeList inventory(@jakarta.annotation.Nullable Integer inventory) {
    this.inventory = JsonNullable.<Integer>of(inventory);
    
    return this;
  }

  /**
   * Inventory applied as a prompt, assuming job template prompts for inventory
   * @return inventory
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getInventory() {
        return inventory.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INVENTORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getInventory_JsonNullable() {
    return inventory;
  }
  
  @JsonProperty(JSON_PROPERTY_INVENTORY)
  public void setInventory_JsonNullable(JsonNullable<Integer> inventory) {
    this.inventory = inventory;
  }

  public void setInventory(@jakarta.annotation.Nullable Integer inventory) {
    this.inventory = JsonNullable.<Integer>of(inventory);
  }

  public WorkflowJobNodeList job(@jakarta.annotation.Nullable Integer job) {
    this.job = JsonNullable.<Integer>of(job);
    
    return this;
  }

  /**
   * Get job
   * @return job
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getJob() {
        return job.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_JOB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getJob_JsonNullable() {
    return job;
  }
  
  @JsonProperty(JSON_PROPERTY_JOB)
  public void setJob_JsonNullable(JsonNullable<Integer> job) {
    this.job = job;
  }

  public void setJob(@jakarta.annotation.Nullable Integer job) {
    this.job = JsonNullable.<Integer>of(job);
  }

  public WorkflowJobNodeList jobSliceCount(@jakarta.annotation.Nullable Integer jobSliceCount) {
    this.jobSliceCount = JsonNullable.<Integer>of(jobSliceCount);
    
    return this;
  }

  /**
   * Get jobSliceCount
   * minimum: 0
   * @return jobSliceCount
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getJobSliceCount() {
        return jobSliceCount.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_JOB_SLICE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getJobSliceCount_JsonNullable() {
    return jobSliceCount;
  }
  
  @JsonProperty(JSON_PROPERTY_JOB_SLICE_COUNT)
  public void setJobSliceCount_JsonNullable(JsonNullable<Integer> jobSliceCount) {
    this.jobSliceCount = jobSliceCount;
  }

  public void setJobSliceCount(@jakarta.annotation.Nullable Integer jobSliceCount) {
    this.jobSliceCount = JsonNullable.<Integer>of(jobSliceCount);
  }

  public WorkflowJobNodeList jobTags(@jakarta.annotation.Nullable String jobTags) {
    this.jobTags = JsonNullable.<String>of(jobTags);
    
    return this;
  }

  /**
   * Get jobTags
   * @return jobTags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getJobTags() {
        return jobTags.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_JOB_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getJobTags_JsonNullable() {
    return jobTags;
  }
  
  @JsonProperty(JSON_PROPERTY_JOB_TAGS)
  public void setJobTags_JsonNullable(JsonNullable<String> jobTags) {
    this.jobTags = jobTags;
  }

  public void setJobTags(@jakarta.annotation.Nullable String jobTags) {
    this.jobTags = JsonNullable.<String>of(jobTags);
  }

  public WorkflowJobNodeList jobType(@jakarta.annotation.Nullable JobTypeEnum jobType) {
    this.jobType = JsonNullable.<JobTypeEnum>of(jobType);
    
    return this;
  }

  /**
   * Get jobType
   * @return jobType
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public JobTypeEnum getJobType() {
        return jobType.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_JOB_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<JobTypeEnum> getJobType_JsonNullable() {
    return jobType;
  }
  
  @JsonProperty(JSON_PROPERTY_JOB_TYPE)
  public void setJobType_JsonNullable(JsonNullable<JobTypeEnum> jobType) {
    this.jobType = jobType;
  }

  public void setJobType(@jakarta.annotation.Nullable JobTypeEnum jobType) {
    this.jobType = JsonNullable.<JobTypeEnum>of(jobType);
  }

  public WorkflowJobNodeList limit(@jakarta.annotation.Nullable String limit) {
    this.limit = JsonNullable.<String>of(limit);
    
    return this;
  }

  /**
   * Get limit
   * @return limit
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getLimit() {
        return limit.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLimit_JsonNullable() {
    return limit;
  }
  
  @JsonProperty(JSON_PROPERTY_LIMIT)
  public void setLimit_JsonNullable(JsonNullable<String> limit) {
    this.limit = limit;
  }

  public void setLimit(@jakarta.annotation.Nullable String limit) {
    this.limit = JsonNullable.<String>of(limit);
  }

  /**
   * Get modified
   * @return modified
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModified() {
    return modified;
  }



  /**
   * Get related
   * @return related
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelated() {
    return related;
  }



  public WorkflowJobNodeList scmBranch(@jakarta.annotation.Nullable String scmBranch) {
    this.scmBranch = JsonNullable.<String>of(scmBranch);
    
    return this;
  }

  /**
   * Get scmBranch
   * @return scmBranch
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getScmBranch() {
        return scmBranch.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SCM_BRANCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getScmBranch_JsonNullable() {
    return scmBranch;
  }
  
  @JsonProperty(JSON_PROPERTY_SCM_BRANCH)
  public void setScmBranch_JsonNullable(JsonNullable<String> scmBranch) {
    this.scmBranch = scmBranch;
  }

  public void setScmBranch(@jakarta.annotation.Nullable String scmBranch) {
    this.scmBranch = JsonNullable.<String>of(scmBranch);
  }

  public WorkflowJobNodeList skipTags(@jakarta.annotation.Nullable String skipTags) {
    this.skipTags = JsonNullable.<String>of(skipTags);
    
    return this;
  }

  /**
   * Get skipTags
   * @return skipTags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getSkipTags() {
        return skipTags.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SKIP_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSkipTags_JsonNullable() {
    return skipTags;
  }
  
  @JsonProperty(JSON_PROPERTY_SKIP_TAGS)
  public void setSkipTags_JsonNullable(JsonNullable<String> skipTags) {
    this.skipTags = skipTags;
  }

  public void setSkipTags(@jakarta.annotation.Nullable String skipTags) {
    this.skipTags = JsonNullable.<String>of(skipTags);
  }

  /**
   * Get successNodes
   * @return successNodes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUCCESS_NODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<Integer> getSuccessNodes() {
    return successNodes;
  }



  /**
   * Get summaryFields
   * @return summaryFields
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUMMARY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSummaryFields() {
    return summaryFields;
  }



  public WorkflowJobNodeList timeout(@jakarta.annotation.Nullable Integer timeout) {
    this.timeout = JsonNullable.<Integer>of(timeout);
    
    return this;
  }

  /**
   * Get timeout
   * @return timeout
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getTimeout() {
        return timeout.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TIMEOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getTimeout_JsonNullable() {
    return timeout;
  }
  
  @JsonProperty(JSON_PROPERTY_TIMEOUT)
  public void setTimeout_JsonNullable(JsonNullable<Integer> timeout) {
    this.timeout = timeout;
  }

  public void setTimeout(@jakarta.annotation.Nullable Integer timeout) {
    this.timeout = JsonNullable.<Integer>of(timeout);
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }



  public WorkflowJobNodeList unifiedJobTemplate(@jakarta.annotation.Nullable Integer unifiedJobTemplate) {
    this.unifiedJobTemplate = JsonNullable.<Integer>of(unifiedJobTemplate);
    
    return this;
  }

  /**
   * Get unifiedJobTemplate
   * @return unifiedJobTemplate
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getUnifiedJobTemplate() {
        return unifiedJobTemplate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_UNIFIED_JOB_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getUnifiedJobTemplate_JsonNullable() {
    return unifiedJobTemplate;
  }
  
  @JsonProperty(JSON_PROPERTY_UNIFIED_JOB_TEMPLATE)
  public void setUnifiedJobTemplate_JsonNullable(JsonNullable<Integer> unifiedJobTemplate) {
    this.unifiedJobTemplate = unifiedJobTemplate;
  }

  public void setUnifiedJobTemplate(@jakarta.annotation.Nullable Integer unifiedJobTemplate) {
    this.unifiedJobTemplate = JsonNullable.<Integer>of(unifiedJobTemplate);
  }

  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }



  public WorkflowJobNodeList verbosity(@jakarta.annotation.Nullable VerbosityEnum verbosity) {
    this.verbosity = JsonNullable.<VerbosityEnum>of(verbosity);
    
    return this;
  }

  /**
   * Get verbosity
   * @return verbosity
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public VerbosityEnum getVerbosity() {
        return verbosity.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VERBOSITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<VerbosityEnum> getVerbosity_JsonNullable() {
    return verbosity;
  }
  
  @JsonProperty(JSON_PROPERTY_VERBOSITY)
  public void setVerbosity_JsonNullable(JsonNullable<VerbosityEnum> verbosity) {
    this.verbosity = verbosity;
  }

  public void setVerbosity(@jakarta.annotation.Nullable VerbosityEnum verbosity) {
    this.verbosity = JsonNullable.<VerbosityEnum>of(verbosity);
  }

  public WorkflowJobNodeList workflowJob(@jakarta.annotation.Nullable String workflowJob) {
    this.workflowJob = JsonNullable.<String>of(workflowJob);
    
    return this;
  }

  /**
   * Get workflowJob
   * @return workflowJob
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getWorkflowJob() {
        return workflowJob.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_WORKFLOW_JOB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getWorkflowJob_JsonNullable() {
    return workflowJob;
  }
  
  @JsonProperty(JSON_PROPERTY_WORKFLOW_JOB)
  public void setWorkflowJob_JsonNullable(JsonNullable<String> workflowJob) {
    this.workflowJob = workflowJob;
  }

  public void setWorkflowJob(@jakarta.annotation.Nullable String workflowJob) {
    this.workflowJob = JsonNullable.<String>of(workflowJob);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowJobNodeList workflowJobNodeList = (WorkflowJobNodeList) o;
    return equalsNullable(this.allParentsMustConverge, workflowJobNodeList.allParentsMustConverge) &&
        Objects.equals(this.alwaysNodes, workflowJobNodeList.alwaysNodes) &&
        Objects.equals(this.created, workflowJobNodeList.created) &&
        equalsNullable(this.diffMode, workflowJobNodeList.diffMode) &&
        equalsNullable(this.doNotRun, workflowJobNodeList.doNotRun) &&
        equalsNullable(this.executionEnvironment, workflowJobNodeList.executionEnvironment) &&
        Objects.equals(this.extraData, workflowJobNodeList.extraData) &&
        Objects.equals(this.failureNodes, workflowJobNodeList.failureNodes) &&
        equalsNullable(this.forks, workflowJobNodeList.forks) &&
        Objects.equals(this.id, workflowJobNodeList.id) &&
        equalsNullable(this.identifier, workflowJobNodeList.identifier) &&
        equalsNullable(this.inventory, workflowJobNodeList.inventory) &&
        equalsNullable(this.job, workflowJobNodeList.job) &&
        equalsNullable(this.jobSliceCount, workflowJobNodeList.jobSliceCount) &&
        equalsNullable(this.jobTags, workflowJobNodeList.jobTags) &&
        equalsNullable(this.jobType, workflowJobNodeList.jobType) &&
        equalsNullable(this.limit, workflowJobNodeList.limit) &&
        Objects.equals(this.modified, workflowJobNodeList.modified) &&
        Objects.equals(this.related, workflowJobNodeList.related) &&
        equalsNullable(this.scmBranch, workflowJobNodeList.scmBranch) &&
        equalsNullable(this.skipTags, workflowJobNodeList.skipTags) &&
        Objects.equals(this.successNodes, workflowJobNodeList.successNodes) &&
        Objects.equals(this.summaryFields, workflowJobNodeList.summaryFields) &&
        equalsNullable(this.timeout, workflowJobNodeList.timeout) &&
        Objects.equals(this.type, workflowJobNodeList.type) &&
        equalsNullable(this.unifiedJobTemplate, workflowJobNodeList.unifiedJobTemplate) &&
        Objects.equals(this.url, workflowJobNodeList.url) &&
        equalsNullable(this.verbosity, workflowJobNodeList.verbosity) &&
        equalsNullable(this.workflowJob, workflowJobNodeList.workflowJob);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(allParentsMustConverge), alwaysNodes, created, hashCodeNullable(diffMode), hashCodeNullable(doNotRun), hashCodeNullable(executionEnvironment), extraData, failureNodes, hashCodeNullable(forks), id, hashCodeNullable(identifier), hashCodeNullable(inventory), hashCodeNullable(job), hashCodeNullable(jobSliceCount), hashCodeNullable(jobTags), hashCodeNullable(jobType), hashCodeNullable(limit), modified, related, hashCodeNullable(scmBranch), hashCodeNullable(skipTags), successNodes, summaryFields, hashCodeNullable(timeout), type, hashCodeNullable(unifiedJobTemplate), url, hashCodeNullable(verbosity), hashCodeNullable(workflowJob));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowJobNodeList {\n");
    sb.append("    allParentsMustConverge: ").append(toIndentedString(allParentsMustConverge)).append("\n");
    sb.append("    alwaysNodes: ").append(toIndentedString(alwaysNodes)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    diffMode: ").append(toIndentedString(diffMode)).append("\n");
    sb.append("    doNotRun: ").append(toIndentedString(doNotRun)).append("\n");
    sb.append("    executionEnvironment: ").append(toIndentedString(executionEnvironment)).append("\n");
    sb.append("    extraData: ").append(toIndentedString(extraData)).append("\n");
    sb.append("    failureNodes: ").append(toIndentedString(failureNodes)).append("\n");
    sb.append("    forks: ").append(toIndentedString(forks)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    inventory: ").append(toIndentedString(inventory)).append("\n");
    sb.append("    job: ").append(toIndentedString(job)).append("\n");
    sb.append("    jobSliceCount: ").append(toIndentedString(jobSliceCount)).append("\n");
    sb.append("    jobTags: ").append(toIndentedString(jobTags)).append("\n");
    sb.append("    jobType: ").append(toIndentedString(jobType)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("    scmBranch: ").append(toIndentedString(scmBranch)).append("\n");
    sb.append("    skipTags: ").append(toIndentedString(skipTags)).append("\n");
    sb.append("    successNodes: ").append(toIndentedString(successNodes)).append("\n");
    sb.append("    summaryFields: ").append(toIndentedString(summaryFields)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    unifiedJobTemplate: ").append(toIndentedString(unifiedJobTemplate)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    verbosity: ").append(toIndentedString(verbosity)).append("\n");
    sb.append("    workflowJob: ").append(toIndentedString(workflowJob)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private WorkflowJobNodeList instance;

    public Builder() {
      this(new WorkflowJobNodeList());
    }

    protected Builder(WorkflowJobNodeList instance) {
      this.instance = instance;
    }

    public WorkflowJobNodeList.Builder allParentsMustConverge(Boolean allParentsMustConverge) {
      this.instance.allParentsMustConverge = JsonNullable.<Boolean>of(allParentsMustConverge);
      return this;
    }
    public WorkflowJobNodeList.Builder allParentsMustConverge(JsonNullable<Boolean> allParentsMustConverge) {
      this.instance.allParentsMustConverge = allParentsMustConverge;
      return this;
    }
    public WorkflowJobNodeList.Builder alwaysNodes(Set<Integer> alwaysNodes) {
      this.instance.alwaysNodes = alwaysNodes;
      return this;
    }
    public WorkflowJobNodeList.Builder created(String created) {
      this.instance.created = created;
      return this;
    }
    public WorkflowJobNodeList.Builder diffMode(Boolean diffMode) {
      this.instance.diffMode = JsonNullable.<Boolean>of(diffMode);
      return this;
    }
    public WorkflowJobNodeList.Builder diffMode(JsonNullable<Boolean> diffMode) {
      this.instance.diffMode = diffMode;
      return this;
    }
    public WorkflowJobNodeList.Builder doNotRun(Boolean doNotRun) {
      this.instance.doNotRun = JsonNullable.<Boolean>of(doNotRun);
      return this;
    }
    public WorkflowJobNodeList.Builder doNotRun(JsonNullable<Boolean> doNotRun) {
      this.instance.doNotRun = doNotRun;
      return this;
    }
    public WorkflowJobNodeList.Builder executionEnvironment(Integer executionEnvironment) {
      this.instance.executionEnvironment = JsonNullable.<Integer>of(executionEnvironment);
      return this;
    }
    public WorkflowJobNodeList.Builder executionEnvironment(JsonNullable<Integer> executionEnvironment) {
      this.instance.executionEnvironment = executionEnvironment;
      return this;
    }
    public WorkflowJobNodeList.Builder extraData(Object extraData) {
      this.instance.extraData = extraData;
      return this;
    }
    public WorkflowJobNodeList.Builder failureNodes(Set<Integer> failureNodes) {
      this.instance.failureNodes = failureNodes;
      return this;
    }
    public WorkflowJobNodeList.Builder forks(Integer forks) {
      this.instance.forks = JsonNullable.<Integer>of(forks);
      return this;
    }
    public WorkflowJobNodeList.Builder forks(JsonNullable<Integer> forks) {
      this.instance.forks = forks;
      return this;
    }
    public WorkflowJobNodeList.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public WorkflowJobNodeList.Builder identifier(String identifier) {
      this.instance.identifier = JsonNullable.<String>of(identifier);
      return this;
    }
    public WorkflowJobNodeList.Builder identifier(JsonNullable<String> identifier) {
      this.instance.identifier = identifier;
      return this;
    }
    public WorkflowJobNodeList.Builder inventory(Integer inventory) {
      this.instance.inventory = JsonNullable.<Integer>of(inventory);
      return this;
    }
    public WorkflowJobNodeList.Builder inventory(JsonNullable<Integer> inventory) {
      this.instance.inventory = inventory;
      return this;
    }
    public WorkflowJobNodeList.Builder job(Integer job) {
      this.instance.job = JsonNullable.<Integer>of(job);
      return this;
    }
    public WorkflowJobNodeList.Builder job(JsonNullable<Integer> job) {
      this.instance.job = job;
      return this;
    }
    public WorkflowJobNodeList.Builder jobSliceCount(Integer jobSliceCount) {
      this.instance.jobSliceCount = JsonNullable.<Integer>of(jobSliceCount);
      return this;
    }
    public WorkflowJobNodeList.Builder jobSliceCount(JsonNullable<Integer> jobSliceCount) {
      this.instance.jobSliceCount = jobSliceCount;
      return this;
    }
    public WorkflowJobNodeList.Builder jobTags(String jobTags) {
      this.instance.jobTags = JsonNullable.<String>of(jobTags);
      return this;
    }
    public WorkflowJobNodeList.Builder jobTags(JsonNullable<String> jobTags) {
      this.instance.jobTags = jobTags;
      return this;
    }
    public WorkflowJobNodeList.Builder jobType(JobTypeEnum jobType) {
      this.instance.jobType = JsonNullable.<JobTypeEnum>of(jobType);
      return this;
    }
    public WorkflowJobNodeList.Builder jobType(JsonNullable<JobTypeEnum> jobType) {
      this.instance.jobType = jobType;
      return this;
    }
    public WorkflowJobNodeList.Builder limit(String limit) {
      this.instance.limit = JsonNullable.<String>of(limit);
      return this;
    }
    public WorkflowJobNodeList.Builder limit(JsonNullable<String> limit) {
      this.instance.limit = limit;
      return this;
    }
    public WorkflowJobNodeList.Builder modified(String modified) {
      this.instance.modified = modified;
      return this;
    }
    public WorkflowJobNodeList.Builder related(String related) {
      this.instance.related = related;
      return this;
    }
    public WorkflowJobNodeList.Builder scmBranch(String scmBranch) {
      this.instance.scmBranch = JsonNullable.<String>of(scmBranch);
      return this;
    }
    public WorkflowJobNodeList.Builder scmBranch(JsonNullable<String> scmBranch) {
      this.instance.scmBranch = scmBranch;
      return this;
    }
    public WorkflowJobNodeList.Builder skipTags(String skipTags) {
      this.instance.skipTags = JsonNullable.<String>of(skipTags);
      return this;
    }
    public WorkflowJobNodeList.Builder skipTags(JsonNullable<String> skipTags) {
      this.instance.skipTags = skipTags;
      return this;
    }
    public WorkflowJobNodeList.Builder successNodes(Set<Integer> successNodes) {
      this.instance.successNodes = successNodes;
      return this;
    }
    public WorkflowJobNodeList.Builder summaryFields(String summaryFields) {
      this.instance.summaryFields = summaryFields;
      return this;
    }
    public WorkflowJobNodeList.Builder timeout(Integer timeout) {
      this.instance.timeout = JsonNullable.<Integer>of(timeout);
      return this;
    }
    public WorkflowJobNodeList.Builder timeout(JsonNullable<Integer> timeout) {
      this.instance.timeout = timeout;
      return this;
    }
    public WorkflowJobNodeList.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public WorkflowJobNodeList.Builder unifiedJobTemplate(Integer unifiedJobTemplate) {
      this.instance.unifiedJobTemplate = JsonNullable.<Integer>of(unifiedJobTemplate);
      return this;
    }
    public WorkflowJobNodeList.Builder unifiedJobTemplate(JsonNullable<Integer> unifiedJobTemplate) {
      this.instance.unifiedJobTemplate = unifiedJobTemplate;
      return this;
    }
    public WorkflowJobNodeList.Builder url(String url) {
      this.instance.url = url;
      return this;
    }
    public WorkflowJobNodeList.Builder verbosity(VerbosityEnum verbosity) {
      this.instance.verbosity = JsonNullable.<VerbosityEnum>of(verbosity);
      return this;
    }
    public WorkflowJobNodeList.Builder verbosity(JsonNullable<VerbosityEnum> verbosity) {
      this.instance.verbosity = verbosity;
      return this;
    }
    public WorkflowJobNodeList.Builder workflowJob(String workflowJob) {
      this.instance.workflowJob = JsonNullable.<String>of(workflowJob);
      return this;
    }
    public WorkflowJobNodeList.Builder workflowJob(JsonNullable<String> workflowJob) {
      this.instance.workflowJob = workflowJob;
      return this;
    }


    /**
    * returns a built WorkflowJobNodeList instance.
    *
    * The builder is not reusable.
    */
    public WorkflowJobNodeList build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static WorkflowJobNodeList.Builder builder() {
    return new WorkflowJobNodeList.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public WorkflowJobNodeList.Builder toBuilder() {
    return new WorkflowJobNodeList.Builder()
      .allParentsMustConverge(getAllParentsMustConverge())
      .alwaysNodes(getAlwaysNodes())
      .created(getCreated())
      .diffMode(getDiffMode())
      .doNotRun(getDoNotRun())
      .executionEnvironment(getExecutionEnvironment())
      .extraData(getExtraData())
      .failureNodes(getFailureNodes())
      .forks(getForks())
      .id(getId())
      .identifier(getIdentifier())
      .inventory(getInventory())
      .job(getJob())
      .jobSliceCount(getJobSliceCount())
      .jobTags(getJobTags())
      .jobType(getJobType())
      .limit(getLimit())
      .modified(getModified())
      .related(getRelated())
      .scmBranch(getScmBranch())
      .skipTags(getSkipTags())
      .successNodes(getSuccessNodes())
      .summaryFields(getSummaryFields())
      .timeout(getTimeout())
      .type(getType())
      .unifiedJobTemplate(getUnifiedJobTemplate())
      .url(getUrl())
      .verbosity(getVerbosity())
      .workflowJob(getWorkflowJob());
  }


}

