/*
 * AWX API
 * AWX API Documentation
 *
 * The version of the OpenAPI document: 
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentprovisioner.client.awx.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.LinkedHashSet;
import java.util.Set;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * WorkflowJobLaunch
 */
@JsonPropertyOrder({
  WorkflowJobLaunch.JSON_PROPERTY_ASK_INVENTORY_ON_LAUNCH,
  WorkflowJobLaunch.JSON_PROPERTY_ASK_LABELS_ON_LAUNCH,
  WorkflowJobLaunch.JSON_PROPERTY_ASK_LIMIT_ON_LAUNCH,
  WorkflowJobLaunch.JSON_PROPERTY_ASK_SCM_BRANCH_ON_LAUNCH,
  WorkflowJobLaunch.JSON_PROPERTY_ASK_SKIP_TAGS_ON_LAUNCH,
  WorkflowJobLaunch.JSON_PROPERTY_ASK_TAGS_ON_LAUNCH,
  WorkflowJobLaunch.JSON_PROPERTY_ASK_VARIABLES_ON_LAUNCH,
  WorkflowJobLaunch.JSON_PROPERTY_CAN_START_WITHOUT_USER_INPUT,
  WorkflowJobLaunch.JSON_PROPERTY_DEFAULTS,
  WorkflowJobLaunch.JSON_PROPERTY_EXTRA_VARS,
  WorkflowJobLaunch.JSON_PROPERTY_INVENTORY,
  WorkflowJobLaunch.JSON_PROPERTY_JOB_TAGS,
  WorkflowJobLaunch.JSON_PROPERTY_LABELS,
  WorkflowJobLaunch.JSON_PROPERTY_LIMIT,
  WorkflowJobLaunch.JSON_PROPERTY_NODE_PROMPTS_REJECTED,
  WorkflowJobLaunch.JSON_PROPERTY_NODE_TEMPLATES_MISSING,
  WorkflowJobLaunch.JSON_PROPERTY_SCM_BRANCH,
  WorkflowJobLaunch.JSON_PROPERTY_SKIP_TAGS,
  WorkflowJobLaunch.JSON_PROPERTY_SURVEY_ENABLED,
  WorkflowJobLaunch.JSON_PROPERTY_VARIABLES_NEEDED_TO_START,
  WorkflowJobLaunch.JSON_PROPERTY_WORKFLOW_JOB_TEMPLATE_DATA
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class WorkflowJobLaunch implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ASK_INVENTORY_ON_LAUNCH = "ask_inventory_on_launch";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> askInventoryOnLaunch = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_ASK_LABELS_ON_LAUNCH = "ask_labels_on_launch";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> askLabelsOnLaunch = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_ASK_LIMIT_ON_LAUNCH = "ask_limit_on_launch";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> askLimitOnLaunch = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_ASK_SCM_BRANCH_ON_LAUNCH = "ask_scm_branch_on_launch";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> askScmBranchOnLaunch = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_ASK_SKIP_TAGS_ON_LAUNCH = "ask_skip_tags_on_launch";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> askSkipTagsOnLaunch = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_ASK_TAGS_ON_LAUNCH = "ask_tags_on_launch";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> askTagsOnLaunch = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_ASK_VARIABLES_ON_LAUNCH = "ask_variables_on_launch";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> askVariablesOnLaunch = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_CAN_START_WITHOUT_USER_INPUT = "can_start_without_user_input";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> canStartWithoutUserInput = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_DEFAULTS = "defaults";
  @jakarta.annotation.Nullable
  private JsonNullable<String> defaults = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_EXTRA_VARS = "extra_vars";
  @jakarta.annotation.Nullable
  private JsonNullable<String> extraVars = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_INVENTORY = "inventory";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> inventory = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_JOB_TAGS = "job_tags";
  @jakarta.annotation.Nullable
  private JsonNullable<String> jobTags = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LABELS = "labels";
  @jakarta.annotation.Nullable
  private JsonNullable<Set<Integer>> labels = JsonNullable.<Set<Integer>>undefined();

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @jakarta.annotation.Nullable
  private JsonNullable<String> limit = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_NODE_PROMPTS_REJECTED = "node_prompts_rejected";
  @jakarta.annotation.Nullable
  private JsonNullable<String> nodePromptsRejected = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_NODE_TEMPLATES_MISSING = "node_templates_missing";
  @jakarta.annotation.Nullable
  private JsonNullable<String> nodeTemplatesMissing = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SCM_BRANCH = "scm_branch";
  @jakarta.annotation.Nullable
  private JsonNullable<String> scmBranch = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SKIP_TAGS = "skip_tags";
  @jakarta.annotation.Nullable
  private JsonNullable<String> skipTags = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SURVEY_ENABLED = "survey_enabled";
  @jakarta.annotation.Nullable
  private JsonNullable<String> surveyEnabled = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_VARIABLES_NEEDED_TO_START = "variables_needed_to_start";
  @jakarta.annotation.Nullable
  private JsonNullable<String> variablesNeededToStart = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_WORKFLOW_JOB_TEMPLATE_DATA = "workflow_job_template_data";
  @jakarta.annotation.Nullable
  private JsonNullable<String> workflowJobTemplateData = JsonNullable.<String>undefined();

  public WorkflowJobLaunch() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public WorkflowJobLaunch(
    @JsonProperty(JSON_PROPERTY_DEFAULTS) String defaults
  ) {
    this();
    this.defaults = defaults == null ? JsonNullable.<String>undefined() : JsonNullable.of(defaults);
  }

  public WorkflowJobLaunch askInventoryOnLaunch(@jakarta.annotation.Nullable Boolean askInventoryOnLaunch) {
    this.askInventoryOnLaunch = JsonNullable.<Boolean>of(askInventoryOnLaunch);
    
    return this;
  }

  /**
   * Get askInventoryOnLaunch
   * @return askInventoryOnLaunch
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getAskInventoryOnLaunch() {
        return askInventoryOnLaunch.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ASK_INVENTORY_ON_LAUNCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getAskInventoryOnLaunch_JsonNullable() {
    return askInventoryOnLaunch;
  }
  
  @JsonProperty(JSON_PROPERTY_ASK_INVENTORY_ON_LAUNCH)
  public void setAskInventoryOnLaunch_JsonNullable(JsonNullable<Boolean> askInventoryOnLaunch) {
    this.askInventoryOnLaunch = askInventoryOnLaunch;
  }

  public void setAskInventoryOnLaunch(@jakarta.annotation.Nullable Boolean askInventoryOnLaunch) {
    this.askInventoryOnLaunch = JsonNullable.<Boolean>of(askInventoryOnLaunch);
  }

  public WorkflowJobLaunch askLabelsOnLaunch(@jakarta.annotation.Nullable Boolean askLabelsOnLaunch) {
    this.askLabelsOnLaunch = JsonNullable.<Boolean>of(askLabelsOnLaunch);
    
    return this;
  }

  /**
   * Get askLabelsOnLaunch
   * @return askLabelsOnLaunch
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getAskLabelsOnLaunch() {
        return askLabelsOnLaunch.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ASK_LABELS_ON_LAUNCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getAskLabelsOnLaunch_JsonNullable() {
    return askLabelsOnLaunch;
  }
  
  @JsonProperty(JSON_PROPERTY_ASK_LABELS_ON_LAUNCH)
  public void setAskLabelsOnLaunch_JsonNullable(JsonNullable<Boolean> askLabelsOnLaunch) {
    this.askLabelsOnLaunch = askLabelsOnLaunch;
  }

  public void setAskLabelsOnLaunch(@jakarta.annotation.Nullable Boolean askLabelsOnLaunch) {
    this.askLabelsOnLaunch = JsonNullable.<Boolean>of(askLabelsOnLaunch);
  }

  public WorkflowJobLaunch askLimitOnLaunch(@jakarta.annotation.Nullable Boolean askLimitOnLaunch) {
    this.askLimitOnLaunch = JsonNullable.<Boolean>of(askLimitOnLaunch);
    
    return this;
  }

  /**
   * Get askLimitOnLaunch
   * @return askLimitOnLaunch
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getAskLimitOnLaunch() {
        return askLimitOnLaunch.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ASK_LIMIT_ON_LAUNCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getAskLimitOnLaunch_JsonNullable() {
    return askLimitOnLaunch;
  }
  
  @JsonProperty(JSON_PROPERTY_ASK_LIMIT_ON_LAUNCH)
  public void setAskLimitOnLaunch_JsonNullable(JsonNullable<Boolean> askLimitOnLaunch) {
    this.askLimitOnLaunch = askLimitOnLaunch;
  }

  public void setAskLimitOnLaunch(@jakarta.annotation.Nullable Boolean askLimitOnLaunch) {
    this.askLimitOnLaunch = JsonNullable.<Boolean>of(askLimitOnLaunch);
  }

  public WorkflowJobLaunch askScmBranchOnLaunch(@jakarta.annotation.Nullable Boolean askScmBranchOnLaunch) {
    this.askScmBranchOnLaunch = JsonNullable.<Boolean>of(askScmBranchOnLaunch);
    
    return this;
  }

  /**
   * Get askScmBranchOnLaunch
   * @return askScmBranchOnLaunch
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getAskScmBranchOnLaunch() {
        return askScmBranchOnLaunch.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ASK_SCM_BRANCH_ON_LAUNCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getAskScmBranchOnLaunch_JsonNullable() {
    return askScmBranchOnLaunch;
  }
  
  @JsonProperty(JSON_PROPERTY_ASK_SCM_BRANCH_ON_LAUNCH)
  public void setAskScmBranchOnLaunch_JsonNullable(JsonNullable<Boolean> askScmBranchOnLaunch) {
    this.askScmBranchOnLaunch = askScmBranchOnLaunch;
  }

  public void setAskScmBranchOnLaunch(@jakarta.annotation.Nullable Boolean askScmBranchOnLaunch) {
    this.askScmBranchOnLaunch = JsonNullable.<Boolean>of(askScmBranchOnLaunch);
  }

  public WorkflowJobLaunch askSkipTagsOnLaunch(@jakarta.annotation.Nullable Boolean askSkipTagsOnLaunch) {
    this.askSkipTagsOnLaunch = JsonNullable.<Boolean>of(askSkipTagsOnLaunch);
    
    return this;
  }

  /**
   * Get askSkipTagsOnLaunch
   * @return askSkipTagsOnLaunch
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getAskSkipTagsOnLaunch() {
        return askSkipTagsOnLaunch.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ASK_SKIP_TAGS_ON_LAUNCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getAskSkipTagsOnLaunch_JsonNullable() {
    return askSkipTagsOnLaunch;
  }
  
  @JsonProperty(JSON_PROPERTY_ASK_SKIP_TAGS_ON_LAUNCH)
  public void setAskSkipTagsOnLaunch_JsonNullable(JsonNullable<Boolean> askSkipTagsOnLaunch) {
    this.askSkipTagsOnLaunch = askSkipTagsOnLaunch;
  }

  public void setAskSkipTagsOnLaunch(@jakarta.annotation.Nullable Boolean askSkipTagsOnLaunch) {
    this.askSkipTagsOnLaunch = JsonNullable.<Boolean>of(askSkipTagsOnLaunch);
  }

  public WorkflowJobLaunch askTagsOnLaunch(@jakarta.annotation.Nullable Boolean askTagsOnLaunch) {
    this.askTagsOnLaunch = JsonNullable.<Boolean>of(askTagsOnLaunch);
    
    return this;
  }

  /**
   * Get askTagsOnLaunch
   * @return askTagsOnLaunch
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getAskTagsOnLaunch() {
        return askTagsOnLaunch.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ASK_TAGS_ON_LAUNCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getAskTagsOnLaunch_JsonNullable() {
    return askTagsOnLaunch;
  }
  
  @JsonProperty(JSON_PROPERTY_ASK_TAGS_ON_LAUNCH)
  public void setAskTagsOnLaunch_JsonNullable(JsonNullable<Boolean> askTagsOnLaunch) {
    this.askTagsOnLaunch = askTagsOnLaunch;
  }

  public void setAskTagsOnLaunch(@jakarta.annotation.Nullable Boolean askTagsOnLaunch) {
    this.askTagsOnLaunch = JsonNullable.<Boolean>of(askTagsOnLaunch);
  }

  public WorkflowJobLaunch askVariablesOnLaunch(@jakarta.annotation.Nullable Boolean askVariablesOnLaunch) {
    this.askVariablesOnLaunch = JsonNullable.<Boolean>of(askVariablesOnLaunch);
    
    return this;
  }

  /**
   * Get askVariablesOnLaunch
   * @return askVariablesOnLaunch
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getAskVariablesOnLaunch() {
        return askVariablesOnLaunch.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ASK_VARIABLES_ON_LAUNCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getAskVariablesOnLaunch_JsonNullable() {
    return askVariablesOnLaunch;
  }
  
  @JsonProperty(JSON_PROPERTY_ASK_VARIABLES_ON_LAUNCH)
  public void setAskVariablesOnLaunch_JsonNullable(JsonNullable<Boolean> askVariablesOnLaunch) {
    this.askVariablesOnLaunch = askVariablesOnLaunch;
  }

  public void setAskVariablesOnLaunch(@jakarta.annotation.Nullable Boolean askVariablesOnLaunch) {
    this.askVariablesOnLaunch = JsonNullable.<Boolean>of(askVariablesOnLaunch);
  }

  public WorkflowJobLaunch canStartWithoutUserInput(@jakarta.annotation.Nullable Boolean canStartWithoutUserInput) {
    this.canStartWithoutUserInput = JsonNullable.<Boolean>of(canStartWithoutUserInput);
    
    return this;
  }

  /**
   * Get canStartWithoutUserInput
   * @return canStartWithoutUserInput
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getCanStartWithoutUserInput() {
        return canStartWithoutUserInput.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CAN_START_WITHOUT_USER_INPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getCanStartWithoutUserInput_JsonNullable() {
    return canStartWithoutUserInput;
  }
  
  @JsonProperty(JSON_PROPERTY_CAN_START_WITHOUT_USER_INPUT)
  public void setCanStartWithoutUserInput_JsonNullable(JsonNullable<Boolean> canStartWithoutUserInput) {
    this.canStartWithoutUserInput = canStartWithoutUserInput;
  }

  public void setCanStartWithoutUserInput(@jakarta.annotation.Nullable Boolean canStartWithoutUserInput) {
    this.canStartWithoutUserInput = JsonNullable.<Boolean>of(canStartWithoutUserInput);
  }

  /**
   * Get defaults
   * @return defaults
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDefaults() {
    
    if (defaults == null) {
      defaults = JsonNullable.<String>undefined();
    }
    return defaults.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DEFAULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDefaults_JsonNullable() {
    return defaults;
  }
  
  @JsonProperty(JSON_PROPERTY_DEFAULTS)
  private void setDefaults_JsonNullable(JsonNullable<String> defaults) {
    this.defaults = defaults;
  }


  public WorkflowJobLaunch extraVars(@jakarta.annotation.Nullable String extraVars) {
    this.extraVars = JsonNullable.<String>of(extraVars);
    
    return this;
  }

  /**
   * Get extraVars
   * @return extraVars
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getExtraVars() {
        return extraVars.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXTRA_VARS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getExtraVars_JsonNullable() {
    return extraVars;
  }
  
  @JsonProperty(JSON_PROPERTY_EXTRA_VARS)
  public void setExtraVars_JsonNullable(JsonNullable<String> extraVars) {
    this.extraVars = extraVars;
  }

  public void setExtraVars(@jakarta.annotation.Nullable String extraVars) {
    this.extraVars = JsonNullable.<String>of(extraVars);
  }

  public WorkflowJobLaunch inventory(@jakarta.annotation.Nullable Integer inventory) {
    this.inventory = JsonNullable.<Integer>of(inventory);
    
    return this;
  }

  /**
   * Get inventory
   * @return inventory
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getInventory() {
        return inventory.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INVENTORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getInventory_JsonNullable() {
    return inventory;
  }
  
  @JsonProperty(JSON_PROPERTY_INVENTORY)
  public void setInventory_JsonNullable(JsonNullable<Integer> inventory) {
    this.inventory = inventory;
  }

  public void setInventory(@jakarta.annotation.Nullable Integer inventory) {
    this.inventory = JsonNullable.<Integer>of(inventory);
  }

  public WorkflowJobLaunch jobTags(@jakarta.annotation.Nullable String jobTags) {
    this.jobTags = JsonNullable.<String>of(jobTags);
    
    return this;
  }

  /**
   * Get jobTags
   * @return jobTags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getJobTags() {
        return jobTags.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_JOB_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getJobTags_JsonNullable() {
    return jobTags;
  }
  
  @JsonProperty(JSON_PROPERTY_JOB_TAGS)
  public void setJobTags_JsonNullable(JsonNullable<String> jobTags) {
    this.jobTags = jobTags;
  }

  public void setJobTags(@jakarta.annotation.Nullable String jobTags) {
    this.jobTags = JsonNullable.<String>of(jobTags);
  }

  public WorkflowJobLaunch labels(@jakarta.annotation.Nullable Set<Integer> labels) {
    this.labels = JsonNullable.<Set<Integer>>of(labels);
    
    return this;
  }

  public WorkflowJobLaunch addLabelsItem(Integer labelsItem) {
    if (this.labels == null || !this.labels.isPresent()) {
      this.labels = JsonNullable.<Set<Integer>>of(new LinkedHashSet<>());
    }
    try {
      this.labels.get().add(labelsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get labels
   * @return labels
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Set<Integer> getLabels() {
        return labels.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Set<Integer>> getLabels_JsonNullable() {
    return labels;
  }
  
  @JsonProperty(JSON_PROPERTY_LABELS)
  public void setLabels_JsonNullable(JsonNullable<Set<Integer>> labels) {
    this.labels = labels;
  }

  public void setLabels(@jakarta.annotation.Nullable Set<Integer> labels) {
    this.labels = JsonNullable.<Set<Integer>>of(labels);
  }

  public WorkflowJobLaunch limit(@jakarta.annotation.Nullable String limit) {
    this.limit = JsonNullable.<String>of(limit);
    
    return this;
  }

  /**
   * Get limit
   * @return limit
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getLimit() {
        return limit.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLimit_JsonNullable() {
    return limit;
  }
  
  @JsonProperty(JSON_PROPERTY_LIMIT)
  public void setLimit_JsonNullable(JsonNullable<String> limit) {
    this.limit = limit;
  }

  public void setLimit(@jakarta.annotation.Nullable String limit) {
    this.limit = JsonNullable.<String>of(limit);
  }

  public WorkflowJobLaunch nodePromptsRejected(@jakarta.annotation.Nullable String nodePromptsRejected) {
    this.nodePromptsRejected = JsonNullable.<String>of(nodePromptsRejected);
    
    return this;
  }

  /**
   * Get nodePromptsRejected
   * @return nodePromptsRejected
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getNodePromptsRejected() {
        return nodePromptsRejected.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NODE_PROMPTS_REJECTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getNodePromptsRejected_JsonNullable() {
    return nodePromptsRejected;
  }
  
  @JsonProperty(JSON_PROPERTY_NODE_PROMPTS_REJECTED)
  public void setNodePromptsRejected_JsonNullable(JsonNullable<String> nodePromptsRejected) {
    this.nodePromptsRejected = nodePromptsRejected;
  }

  public void setNodePromptsRejected(@jakarta.annotation.Nullable String nodePromptsRejected) {
    this.nodePromptsRejected = JsonNullable.<String>of(nodePromptsRejected);
  }

  public WorkflowJobLaunch nodeTemplatesMissing(@jakarta.annotation.Nullable String nodeTemplatesMissing) {
    this.nodeTemplatesMissing = JsonNullable.<String>of(nodeTemplatesMissing);
    
    return this;
  }

  /**
   * Get nodeTemplatesMissing
   * @return nodeTemplatesMissing
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getNodeTemplatesMissing() {
        return nodeTemplatesMissing.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NODE_TEMPLATES_MISSING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getNodeTemplatesMissing_JsonNullable() {
    return nodeTemplatesMissing;
  }
  
  @JsonProperty(JSON_PROPERTY_NODE_TEMPLATES_MISSING)
  public void setNodeTemplatesMissing_JsonNullable(JsonNullable<String> nodeTemplatesMissing) {
    this.nodeTemplatesMissing = nodeTemplatesMissing;
  }

  public void setNodeTemplatesMissing(@jakarta.annotation.Nullable String nodeTemplatesMissing) {
    this.nodeTemplatesMissing = JsonNullable.<String>of(nodeTemplatesMissing);
  }

  public WorkflowJobLaunch scmBranch(@jakarta.annotation.Nullable String scmBranch) {
    this.scmBranch = JsonNullable.<String>of(scmBranch);
    
    return this;
  }

  /**
   * Get scmBranch
   * @return scmBranch
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getScmBranch() {
        return scmBranch.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SCM_BRANCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getScmBranch_JsonNullable() {
    return scmBranch;
  }
  
  @JsonProperty(JSON_PROPERTY_SCM_BRANCH)
  public void setScmBranch_JsonNullable(JsonNullable<String> scmBranch) {
    this.scmBranch = scmBranch;
  }

  public void setScmBranch(@jakarta.annotation.Nullable String scmBranch) {
    this.scmBranch = JsonNullable.<String>of(scmBranch);
  }

  public WorkflowJobLaunch skipTags(@jakarta.annotation.Nullable String skipTags) {
    this.skipTags = JsonNullable.<String>of(skipTags);
    
    return this;
  }

  /**
   * Get skipTags
   * @return skipTags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getSkipTags() {
        return skipTags.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SKIP_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSkipTags_JsonNullable() {
    return skipTags;
  }
  
  @JsonProperty(JSON_PROPERTY_SKIP_TAGS)
  public void setSkipTags_JsonNullable(JsonNullable<String> skipTags) {
    this.skipTags = skipTags;
  }

  public void setSkipTags(@jakarta.annotation.Nullable String skipTags) {
    this.skipTags = JsonNullable.<String>of(skipTags);
  }

  public WorkflowJobLaunch surveyEnabled(@jakarta.annotation.Nullable String surveyEnabled) {
    this.surveyEnabled = JsonNullable.<String>of(surveyEnabled);
    
    return this;
  }

  /**
   * Get surveyEnabled
   * @return surveyEnabled
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getSurveyEnabled() {
        return surveyEnabled.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SURVEY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSurveyEnabled_JsonNullable() {
    return surveyEnabled;
  }
  
  @JsonProperty(JSON_PROPERTY_SURVEY_ENABLED)
  public void setSurveyEnabled_JsonNullable(JsonNullable<String> surveyEnabled) {
    this.surveyEnabled = surveyEnabled;
  }

  public void setSurveyEnabled(@jakarta.annotation.Nullable String surveyEnabled) {
    this.surveyEnabled = JsonNullable.<String>of(surveyEnabled);
  }

  public WorkflowJobLaunch variablesNeededToStart(@jakarta.annotation.Nullable String variablesNeededToStart) {
    this.variablesNeededToStart = JsonNullable.<String>of(variablesNeededToStart);
    
    return this;
  }

  /**
   * Get variablesNeededToStart
   * @return variablesNeededToStart
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getVariablesNeededToStart() {
        return variablesNeededToStart.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VARIABLES_NEEDED_TO_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getVariablesNeededToStart_JsonNullable() {
    return variablesNeededToStart;
  }
  
  @JsonProperty(JSON_PROPERTY_VARIABLES_NEEDED_TO_START)
  public void setVariablesNeededToStart_JsonNullable(JsonNullable<String> variablesNeededToStart) {
    this.variablesNeededToStart = variablesNeededToStart;
  }

  public void setVariablesNeededToStart(@jakarta.annotation.Nullable String variablesNeededToStart) {
    this.variablesNeededToStart = JsonNullable.<String>of(variablesNeededToStart);
  }

  public WorkflowJobLaunch workflowJobTemplateData(@jakarta.annotation.Nullable String workflowJobTemplateData) {
    this.workflowJobTemplateData = JsonNullable.<String>of(workflowJobTemplateData);
    
    return this;
  }

  /**
   * Get workflowJobTemplateData
   * @return workflowJobTemplateData
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getWorkflowJobTemplateData() {
        return workflowJobTemplateData.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_WORKFLOW_JOB_TEMPLATE_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getWorkflowJobTemplateData_JsonNullable() {
    return workflowJobTemplateData;
  }
  
  @JsonProperty(JSON_PROPERTY_WORKFLOW_JOB_TEMPLATE_DATA)
  public void setWorkflowJobTemplateData_JsonNullable(JsonNullable<String> workflowJobTemplateData) {
    this.workflowJobTemplateData = workflowJobTemplateData;
  }

  public void setWorkflowJobTemplateData(@jakarta.annotation.Nullable String workflowJobTemplateData) {
    this.workflowJobTemplateData = JsonNullable.<String>of(workflowJobTemplateData);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowJobLaunch workflowJobLaunch = (WorkflowJobLaunch) o;
    return equalsNullable(this.askInventoryOnLaunch, workflowJobLaunch.askInventoryOnLaunch) &&
        equalsNullable(this.askLabelsOnLaunch, workflowJobLaunch.askLabelsOnLaunch) &&
        equalsNullable(this.askLimitOnLaunch, workflowJobLaunch.askLimitOnLaunch) &&
        equalsNullable(this.askScmBranchOnLaunch, workflowJobLaunch.askScmBranchOnLaunch) &&
        equalsNullable(this.askSkipTagsOnLaunch, workflowJobLaunch.askSkipTagsOnLaunch) &&
        equalsNullable(this.askTagsOnLaunch, workflowJobLaunch.askTagsOnLaunch) &&
        equalsNullable(this.askVariablesOnLaunch, workflowJobLaunch.askVariablesOnLaunch) &&
        equalsNullable(this.canStartWithoutUserInput, workflowJobLaunch.canStartWithoutUserInput) &&
        equalsNullable(this.defaults, workflowJobLaunch.defaults) &&
        equalsNullable(this.extraVars, workflowJobLaunch.extraVars) &&
        equalsNullable(this.inventory, workflowJobLaunch.inventory) &&
        equalsNullable(this.jobTags, workflowJobLaunch.jobTags) &&
        equalsNullable(this.labels, workflowJobLaunch.labels) &&
        equalsNullable(this.limit, workflowJobLaunch.limit) &&
        equalsNullable(this.nodePromptsRejected, workflowJobLaunch.nodePromptsRejected) &&
        equalsNullable(this.nodeTemplatesMissing, workflowJobLaunch.nodeTemplatesMissing) &&
        equalsNullable(this.scmBranch, workflowJobLaunch.scmBranch) &&
        equalsNullable(this.skipTags, workflowJobLaunch.skipTags) &&
        equalsNullable(this.surveyEnabled, workflowJobLaunch.surveyEnabled) &&
        equalsNullable(this.variablesNeededToStart, workflowJobLaunch.variablesNeededToStart) &&
        equalsNullable(this.workflowJobTemplateData, workflowJobLaunch.workflowJobTemplateData);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(askInventoryOnLaunch), hashCodeNullable(askLabelsOnLaunch), hashCodeNullable(askLimitOnLaunch), hashCodeNullable(askScmBranchOnLaunch), hashCodeNullable(askSkipTagsOnLaunch), hashCodeNullable(askTagsOnLaunch), hashCodeNullable(askVariablesOnLaunch), hashCodeNullable(canStartWithoutUserInput), hashCodeNullable(defaults), hashCodeNullable(extraVars), hashCodeNullable(inventory), hashCodeNullable(jobTags), hashCodeNullable(labels), hashCodeNullable(limit), hashCodeNullable(nodePromptsRejected), hashCodeNullable(nodeTemplatesMissing), hashCodeNullable(scmBranch), hashCodeNullable(skipTags), hashCodeNullable(surveyEnabled), hashCodeNullable(variablesNeededToStart), hashCodeNullable(workflowJobTemplateData));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowJobLaunch {\n");
    sb.append("    askInventoryOnLaunch: ").append(toIndentedString(askInventoryOnLaunch)).append("\n");
    sb.append("    askLabelsOnLaunch: ").append(toIndentedString(askLabelsOnLaunch)).append("\n");
    sb.append("    askLimitOnLaunch: ").append(toIndentedString(askLimitOnLaunch)).append("\n");
    sb.append("    askScmBranchOnLaunch: ").append(toIndentedString(askScmBranchOnLaunch)).append("\n");
    sb.append("    askSkipTagsOnLaunch: ").append(toIndentedString(askSkipTagsOnLaunch)).append("\n");
    sb.append("    askTagsOnLaunch: ").append(toIndentedString(askTagsOnLaunch)).append("\n");
    sb.append("    askVariablesOnLaunch: ").append(toIndentedString(askVariablesOnLaunch)).append("\n");
    sb.append("    canStartWithoutUserInput: ").append(toIndentedString(canStartWithoutUserInput)).append("\n");
    sb.append("    defaults: ").append(toIndentedString(defaults)).append("\n");
    sb.append("    extraVars: ").append(toIndentedString(extraVars)).append("\n");
    sb.append("    inventory: ").append(toIndentedString(inventory)).append("\n");
    sb.append("    jobTags: ").append(toIndentedString(jobTags)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    nodePromptsRejected: ").append(toIndentedString(nodePromptsRejected)).append("\n");
    sb.append("    nodeTemplatesMissing: ").append(toIndentedString(nodeTemplatesMissing)).append("\n");
    sb.append("    scmBranch: ").append(toIndentedString(scmBranch)).append("\n");
    sb.append("    skipTags: ").append(toIndentedString(skipTags)).append("\n");
    sb.append("    surveyEnabled: ").append(toIndentedString(surveyEnabled)).append("\n");
    sb.append("    variablesNeededToStart: ").append(toIndentedString(variablesNeededToStart)).append("\n");
    sb.append("    workflowJobTemplateData: ").append(toIndentedString(workflowJobTemplateData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private WorkflowJobLaunch instance;

    public Builder() {
      this(new WorkflowJobLaunch());
    }

    protected Builder(WorkflowJobLaunch instance) {
      this.instance = instance;
    }

    public WorkflowJobLaunch.Builder askInventoryOnLaunch(Boolean askInventoryOnLaunch) {
      this.instance.askInventoryOnLaunch = JsonNullable.<Boolean>of(askInventoryOnLaunch);
      return this;
    }
    public WorkflowJobLaunch.Builder askInventoryOnLaunch(JsonNullable<Boolean> askInventoryOnLaunch) {
      this.instance.askInventoryOnLaunch = askInventoryOnLaunch;
      return this;
    }
    public WorkflowJobLaunch.Builder askLabelsOnLaunch(Boolean askLabelsOnLaunch) {
      this.instance.askLabelsOnLaunch = JsonNullable.<Boolean>of(askLabelsOnLaunch);
      return this;
    }
    public WorkflowJobLaunch.Builder askLabelsOnLaunch(JsonNullable<Boolean> askLabelsOnLaunch) {
      this.instance.askLabelsOnLaunch = askLabelsOnLaunch;
      return this;
    }
    public WorkflowJobLaunch.Builder askLimitOnLaunch(Boolean askLimitOnLaunch) {
      this.instance.askLimitOnLaunch = JsonNullable.<Boolean>of(askLimitOnLaunch);
      return this;
    }
    public WorkflowJobLaunch.Builder askLimitOnLaunch(JsonNullable<Boolean> askLimitOnLaunch) {
      this.instance.askLimitOnLaunch = askLimitOnLaunch;
      return this;
    }
    public WorkflowJobLaunch.Builder askScmBranchOnLaunch(Boolean askScmBranchOnLaunch) {
      this.instance.askScmBranchOnLaunch = JsonNullable.<Boolean>of(askScmBranchOnLaunch);
      return this;
    }
    public WorkflowJobLaunch.Builder askScmBranchOnLaunch(JsonNullable<Boolean> askScmBranchOnLaunch) {
      this.instance.askScmBranchOnLaunch = askScmBranchOnLaunch;
      return this;
    }
    public WorkflowJobLaunch.Builder askSkipTagsOnLaunch(Boolean askSkipTagsOnLaunch) {
      this.instance.askSkipTagsOnLaunch = JsonNullable.<Boolean>of(askSkipTagsOnLaunch);
      return this;
    }
    public WorkflowJobLaunch.Builder askSkipTagsOnLaunch(JsonNullable<Boolean> askSkipTagsOnLaunch) {
      this.instance.askSkipTagsOnLaunch = askSkipTagsOnLaunch;
      return this;
    }
    public WorkflowJobLaunch.Builder askTagsOnLaunch(Boolean askTagsOnLaunch) {
      this.instance.askTagsOnLaunch = JsonNullable.<Boolean>of(askTagsOnLaunch);
      return this;
    }
    public WorkflowJobLaunch.Builder askTagsOnLaunch(JsonNullable<Boolean> askTagsOnLaunch) {
      this.instance.askTagsOnLaunch = askTagsOnLaunch;
      return this;
    }
    public WorkflowJobLaunch.Builder askVariablesOnLaunch(Boolean askVariablesOnLaunch) {
      this.instance.askVariablesOnLaunch = JsonNullable.<Boolean>of(askVariablesOnLaunch);
      return this;
    }
    public WorkflowJobLaunch.Builder askVariablesOnLaunch(JsonNullable<Boolean> askVariablesOnLaunch) {
      this.instance.askVariablesOnLaunch = askVariablesOnLaunch;
      return this;
    }
    public WorkflowJobLaunch.Builder canStartWithoutUserInput(Boolean canStartWithoutUserInput) {
      this.instance.canStartWithoutUserInput = JsonNullable.<Boolean>of(canStartWithoutUserInput);
      return this;
    }
    public WorkflowJobLaunch.Builder canStartWithoutUserInput(JsonNullable<Boolean> canStartWithoutUserInput) {
      this.instance.canStartWithoutUserInput = canStartWithoutUserInput;
      return this;
    }
    public WorkflowJobLaunch.Builder defaults(String defaults) {
      this.instance.defaults = JsonNullable.<String>of(defaults);
      return this;
    }
    public WorkflowJobLaunch.Builder defaults(JsonNullable<String> defaults) {
      this.instance.defaults = defaults;
      return this;
    }
    public WorkflowJobLaunch.Builder extraVars(String extraVars) {
      this.instance.extraVars = JsonNullable.<String>of(extraVars);
      return this;
    }
    public WorkflowJobLaunch.Builder extraVars(JsonNullable<String> extraVars) {
      this.instance.extraVars = extraVars;
      return this;
    }
    public WorkflowJobLaunch.Builder inventory(Integer inventory) {
      this.instance.inventory = JsonNullable.<Integer>of(inventory);
      return this;
    }
    public WorkflowJobLaunch.Builder inventory(JsonNullable<Integer> inventory) {
      this.instance.inventory = inventory;
      return this;
    }
    public WorkflowJobLaunch.Builder jobTags(String jobTags) {
      this.instance.jobTags = JsonNullable.<String>of(jobTags);
      return this;
    }
    public WorkflowJobLaunch.Builder jobTags(JsonNullable<String> jobTags) {
      this.instance.jobTags = jobTags;
      return this;
    }
    public WorkflowJobLaunch.Builder labels(Set<Integer> labels) {
      this.instance.labels = JsonNullable.<Set<Integer>>of(labels);
      return this;
    }
    public WorkflowJobLaunch.Builder labels(JsonNullable<Set<Integer>> labels) {
      this.instance.labels = labels;
      return this;
    }
    public WorkflowJobLaunch.Builder limit(String limit) {
      this.instance.limit = JsonNullable.<String>of(limit);
      return this;
    }
    public WorkflowJobLaunch.Builder limit(JsonNullable<String> limit) {
      this.instance.limit = limit;
      return this;
    }
    public WorkflowJobLaunch.Builder nodePromptsRejected(String nodePromptsRejected) {
      this.instance.nodePromptsRejected = JsonNullable.<String>of(nodePromptsRejected);
      return this;
    }
    public WorkflowJobLaunch.Builder nodePromptsRejected(JsonNullable<String> nodePromptsRejected) {
      this.instance.nodePromptsRejected = nodePromptsRejected;
      return this;
    }
    public WorkflowJobLaunch.Builder nodeTemplatesMissing(String nodeTemplatesMissing) {
      this.instance.nodeTemplatesMissing = JsonNullable.<String>of(nodeTemplatesMissing);
      return this;
    }
    public WorkflowJobLaunch.Builder nodeTemplatesMissing(JsonNullable<String> nodeTemplatesMissing) {
      this.instance.nodeTemplatesMissing = nodeTemplatesMissing;
      return this;
    }
    public WorkflowJobLaunch.Builder scmBranch(String scmBranch) {
      this.instance.scmBranch = JsonNullable.<String>of(scmBranch);
      return this;
    }
    public WorkflowJobLaunch.Builder scmBranch(JsonNullable<String> scmBranch) {
      this.instance.scmBranch = scmBranch;
      return this;
    }
    public WorkflowJobLaunch.Builder skipTags(String skipTags) {
      this.instance.skipTags = JsonNullable.<String>of(skipTags);
      return this;
    }
    public WorkflowJobLaunch.Builder skipTags(JsonNullable<String> skipTags) {
      this.instance.skipTags = skipTags;
      return this;
    }
    public WorkflowJobLaunch.Builder surveyEnabled(String surveyEnabled) {
      this.instance.surveyEnabled = JsonNullable.<String>of(surveyEnabled);
      return this;
    }
    public WorkflowJobLaunch.Builder surveyEnabled(JsonNullable<String> surveyEnabled) {
      this.instance.surveyEnabled = surveyEnabled;
      return this;
    }
    public WorkflowJobLaunch.Builder variablesNeededToStart(String variablesNeededToStart) {
      this.instance.variablesNeededToStart = JsonNullable.<String>of(variablesNeededToStart);
      return this;
    }
    public WorkflowJobLaunch.Builder variablesNeededToStart(JsonNullable<String> variablesNeededToStart) {
      this.instance.variablesNeededToStart = variablesNeededToStart;
      return this;
    }
    public WorkflowJobLaunch.Builder workflowJobTemplateData(String workflowJobTemplateData) {
      this.instance.workflowJobTemplateData = JsonNullable.<String>of(workflowJobTemplateData);
      return this;
    }
    public WorkflowJobLaunch.Builder workflowJobTemplateData(JsonNullable<String> workflowJobTemplateData) {
      this.instance.workflowJobTemplateData = workflowJobTemplateData;
      return this;
    }


    /**
    * returns a built WorkflowJobLaunch instance.
    *
    * The builder is not reusable.
    */
    public WorkflowJobLaunch build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static WorkflowJobLaunch.Builder builder() {
    return new WorkflowJobLaunch.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public WorkflowJobLaunch.Builder toBuilder() {
    return new WorkflowJobLaunch.Builder()
      .askInventoryOnLaunch(getAskInventoryOnLaunch())
      .askLabelsOnLaunch(getAskLabelsOnLaunch())
      .askLimitOnLaunch(getAskLimitOnLaunch())
      .askScmBranchOnLaunch(getAskScmBranchOnLaunch())
      .askSkipTagsOnLaunch(getAskSkipTagsOnLaunch())
      .askTagsOnLaunch(getAskTagsOnLaunch())
      .askVariablesOnLaunch(getAskVariablesOnLaunch())
      .canStartWithoutUserInput(getCanStartWithoutUserInput())
      .defaults(getDefaults())
      .extraVars(getExtraVars())
      .inventory(getInventory())
      .jobTags(getJobTags())
      .labels(getLabels())
      .limit(getLimit())
      .nodePromptsRejected(getNodePromptsRejected())
      .nodeTemplatesMissing(getNodeTemplatesMissing())
      .scmBranch(getScmBranch())
      .skipTags(getSkipTags())
      .surveyEnabled(getSurveyEnabled())
      .variablesNeededToStart(getVariablesNeededToStart())
      .workflowJobTemplateData(getWorkflowJobTemplateData());
  }


}

