server:
  port: 8080
logging:
  level:
    org.springframework: INFO
    org.opendevstack.component_provisioner.server.controllers: INFO
spring:
  security:
    user:
      name: ${SPRING_SECURITY_PROVISIONER_USERNAME}
      password: ${SPRING_SECURITY_PROVISIONER_PASSWORD}
      roles: PROVISIONER
  profiles:
    active: dev
  http:
    client:
      factory: jdk
  jackson:
    date-format: org.opendevstack.component_provisioner.util.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  cloud:
    azure:
      active-directory:
        enabled: true
        session-stateless: true
        credential:
          client-id: ${SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_CREDENTIAL_CLIENT_ID}
        app-id-uri: ${SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_APP_ID_URI}
management:
  endpoints:
    web:
      exposure:
        include: health
catalog-collection:
  id: ${CATALOG_COLLECTION_ID}
user-actions:
  id: ${USER_ACTIONS_ID}
component-provisioner:
  awx:
    service:
      base-rest-url: ${AWX_SERVICE_BASE_REST_URL}
      username: ${AWX_SERVICE_USERNAME}
      password: ${AWX_SERVICE_PASSWORD}
  component-catalog:
    service:
      base-rest-url: ${COMPONENT_CATALOG_SERVICE_BASE_REST_URL}
    project-components:
      username: ${COMPONENT_CATALOG_PROVISIONER_USERNAME}
      password: ${COMPONENT_CATALOG_PROVISIONER_PASSWORD}
  support:
    create-incident-workflow-id: ${CREATE_INCIDENT_WORKFLOW_ID}
  parameters:
    blacklist: ${SENSITIVE_PARAMETERS_BLACKLIST}
