# See: README.md for details about setting up your local environment
logging:
  level:
    org.springframework: DEBUG
    org.springframework.expression: INFO
    org.springframework.beans.factory: DEBUG
    com.azure.spring.cloud.autoconfigure: DEBUG
    org.opendevstack.component_provisioner.server.controllers: INFO
    org.opendevstack.component_provisioner.server.services.org.opendevstack.component_provisioner.server.services.AWXService: DEBUG
    org.springframework.web.client : DEBUG
    org.opendevstack.component_provisioner.server.controllers.interceptors: DEBUG
    org.modelmapper: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui, beans, caches, configprops, env, health, httpexchanges, info, loggers, mappings
  endpoint:
    configprops:
      show-values: always
    env:
      show-values: always
    loggers:
      access: unrestricted
  info:
    git:
      # Show all build-time generated file git.properties info on /actuator/info endpoint
      mode: full
  httpexchanges:
    recording:
      # Show all available info in /actuator/httpexchanges and also in Swagger
      include: request-headers, response-headers, authorization_header, cookie_headers, principal, remote_address, session_id, time_taken
springdoc:
  show-actuator: true
  swagger-ui:
    doc-expansion: none
    try-it-out-enabled: true
    filter: true
    tags-sorter: alpha
    operations-sorter: alpha

