server:
  port: 8080
logging:
  level:
    org.springframework: INFO
    org.opendevstack.component_provisioner.server.controllers: INFO
spring:
  security:
    user:
      name: ${SPRING_SECURITY_PROVISIONER_USERNAME}
      password: ${SPRING_SECURITY_PROVISIONER_PASSWORD}
      roles: PROVISIONER
  profiles:
    active: dev
  http:
    client:
      factory: jdk
  jackson:
    date-format: org.opendevstack.component_provisioner.util.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  cloud:
    azure:
      active-directory:
        enabled: true
        session-stateless: true
        credential:
          client-id: ${SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_CREDENTIAL_CLIENT_ID}
        app-id-uri: ${SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_APP_ID_URI}
management:
  endpoints:
    web:
      exposure:
        include: health

catalog:
  user-action:
    groups-restriction:
      prefix:
        - BI-AS-ATLASSIAN
      suffix:
        - MANAGER
        - TEAM

catalog-collection:
  id: ${CATALOG_COLLECTION_ID}
user-actions:
  id: ${USER_ACTIONS_ID}

component-provisioner:
  azure:
    token:
      url: ${AZURE_TOKEN_URL}
  caching:
    projects-info-services-cache:
      enabled: true
      eviction-interval: ${CACHING_PROJECTS_INFO_SERVICE_CACHE_EVICTION_INTERVAL}
      max-size: ${CACHING_PROJECTS_INFO_SERVICE_CACHE_MAX_SIZE}
    component-catalog-cache:
      enabled: true
      eviction-interval: ${CACHING_PROJECTS_INFO_SERVICE_CACHE_EVICTION_INTERVAL}
      max-size: ${CACHING_PROJECTS_INFO_SERVICE_CACHE_MAX_SIZE}
  projects-info-service:
    service:
      base-rest-url: ${PROJECTS_INFO_SERVICE_BASE_REST_URL}
  awx:
    service:
      base-rest-url: ${AWX_SERVICE_BASE_REST_URL}
      username: ${AWX_SERVICE_USERNAME}
      password: ${AWX_SERVICE_PASSWORD}
    workflows:
      create-incident-workflow-id: ${CREATE_INCIDENT_WORKFLOW_ID}
      deletion-wrapper-workflow-id: ${DELETION_WRAPPER_WORKFLOW_ID}
  component-catalog:
    service:
      base-rest-url: ${COMPONENT_CATALOG_SERVICE_BASE_REST_URL}
    project-components:
      username: ${COMPONENT_CATALOG_PROVISIONER_USERNAME}
      password: ${COMPONENT_CATALOG_PROVISIONER_PASSWORD}
  ods-api-service:
    enabled: ${ODS_API_SERVICE_ENABLED}
    service:
      base-rest-url: ${ODS_API_SERVICE_SERVICE_BASE_REST_URL}
    params:
      client_id: ${DEVSTACK_MARKETPLACE_API_CLIENT_ID}
      client_secret: ${DEVSTACK_MARKETPLACE_API_CLIENT_SECRET}
      scope: ${ODS_API_SERVICE_SERVICE_PARAMS_SCOPE}
      override: ${ODS_API_SERVICE_SERVICE_PARAMS_OVERRIDE}
  parameters:
    blacklist: ${SENSITIVE_PARAMETERS_BLACKLIST}


devstack:
  marketplace-api:
    scope: ${DEVSTACK_MARKETPLACE_API_SCOPE}